.TH "Casino.h" 3 "Sun Nov 20 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Casino.h \- Declares the casino class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'Table\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayerNotLoggedException\fP"
.br
.RI "Exception for signalling player not logged in\&. "
.ti -1c
.RI "class \fBExistingTableException\fP"
.br
.RI "Exception for signalling that a table with the specified ID already exists\&. "
.ti -1c
.RI "class \fBTableNotInCasinoException\fP"
.br
.RI "Exception for signalling that the table is not in the casino\&. "
.ti -1c
.RI "class \fBCasino\fP"
.br
.RI "A casino\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declares the casino class\&. 


.PP
Definition in file \fBCasino\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
