.TH "DealerStillOnTableException" 3 "Sun Nov 20 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DealerStillOnTableException \- Exception for signalling that dealer is still on a table\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dealer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDealerStillOnTableException\fP (\fBDealer\fP *dealer)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "unsigned int \fBgetTableID\fP () const"
.br
.RI "Gets table identifier\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception for signalling that dealer is still on a table\&. 


.PP
\fBAuthor:\fP
.RS 4
M\&. Francisca Pauperio 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 443 of file Dealer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DealerStillOnTableException::DealerStillOnTableException (\fBDealer\fP * dealer)"

.PP
Constructor\&. 
.PP
\fBAuthor:\fP
.RS 4
M\&. Francisca Pauperio 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdealer\fP Pointer to the dealer\&. 
.RE
.PP

.PP
Definition at line 167 of file Dealer\&.cpp\&.
.PP
References Dealer::getID(), and Dealer::getTableOn()\&.
.PP
.nf
167                                                                         {
168     this->dealerID = dealer->getID();
169     this->tableID = dealer->getTableOn();
170 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "unsigned int DealerStillOnTableException::getTableID () const"

.PP
Gets table identifier\&. 
.PP
\fBAuthor:\fP
.RS 4
M\&. Francisca Pauperio 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016
.RE
.PP
\fBReturns:\fP
.RS 4
The table identifier\&. 
.RE
.PP

.PP
Definition at line 172 of file Dealer\&.cpp\&.
.PP
Referenced by Casino::eliminate()\&.
.PP
.nf
172                                                            {
173     return this->tableID;
174 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
