.TH "Dealer.h" 3 "Sat Nov 19 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dealer.h \- Declares the dealer class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Player\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDealer\fP"
.br
.RI "A dealer\&. The dealer is responsible to deal cards to the players and to himself\&. He is the one that holds that deck and reshufles it\&. "
.ti -1c
.RI "class \fBDealerNotExistException\fP"
.br
.RI "Exception for signalling that the dealer doest not exist\&. "
.ti -1c
.RI "class \fBDealerAlreadyExistException\fP"
.br
.RI "Exception for signalling that the dealer already exists\&. "
.ti -1c
.RI "class \fBDealerIsOnTableAlreadyException\fP"
.br
.RI "Exception for signalling that the dealer is already on a table\&. "
.ti -1c
.RI "class \fBDealerStillOnTableException\fP"
.br
.RI "Exception for signalling that dealer is still on a table\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declares the dealer class\&. 


.PP
Definition in file \fBDealer\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
