.TH "DealerAlreadyExistException" 3 "Sun Nov 20 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DealerAlreadyExistException \- Exception for signalling that the dealer already exists\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dealer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDealerAlreadyExistException\fP (\fBDealer\fP *dealer)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "int \fBgetID\fP () const"
.br
.RI "Gets the identifier\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception for signalling that the dealer already exists\&. 


.PP
\fBAuthor:\fP
.RS 4
M\&. Francisca Pauperio 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 372 of file Dealer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DealerAlreadyExistException::DealerAlreadyExistException (\fBDealer\fP * dealer)"

.PP
Constructor\&. 
.PP
\fBAuthor:\fP
.RS 4
M\&. Francisca Pauperio 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdealer\fP A pointer to the dealer\&. 
.RE
.PP

.PP
Definition at line 159 of file Dealer\&.cpp\&.
.PP
References Dealer::getID()\&.
.PP
.nf
159                                                                         {
160     this->dealerID = dealer->getID();
161 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "int DealerAlreadyExistException::getID () const"

.PP
Gets the identifier\&. 
.PP
\fBAuthor:\fP
.RS 4
M\&. Francisca Pauperio 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016
.RE
.PP
\fBReturns:\fP
.RS 4
The identifier\&. 
.RE
.PP

.PP
Definition at line 163 of file Dealer\&.cpp\&.
.PP
Referenced by Casino::readDealersFile()\&.
.PP
.nf
163                                              {
164     return dealerID;
165 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
