.TH "DealerNotExistException" 3 "Sat Nov 19 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DealerNotExistException \- Exception for signalling that the dealer doest not exist\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dealer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDealerNotExistException\fP (\fBDealer\fP *dealer)"
.br
.RI "Constructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception for signalling that the dealer doest not exist\&. 


.PP
\fBAuthor:\fP
.RS 4
M\&. Francisca Pauperio 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 343 of file Dealer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DealerNotExistException::DealerNotExistException (\fBDealer\fP * dealer)"

.PP
Constructor\&. 
.PP
\fBAuthor:\fP
.RS 4
M\&. Francisca Pauperio 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdealer\fP Pointer to the dealer\&. 
.RE
.PP

.PP
Definition at line 150 of file Dealer\&.cpp\&.
.PP
References Dealer::getID()\&.
.PP
.nf
150                                                                {
151     this->dealerID = dealer->getID();
152 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
