.TH "ExistingTableException" 3 "Sat Nov 19 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExistingTableException \- Exception for signalling that a table with the specified ID already exists\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Casino\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExistingTableException\fP (\fBTable\fP *table)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "void \fBwhat\fP ()"
.br
.RI "Displays in terminal what caused this exception to be thrown\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception for signalling that a table with the specified ID already exists\&. 


.PP
\fBAuthor:\fP
.RS 4
Ineeve 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 68 of file Casino\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExistingTableException::ExistingTableException (\fBTable\fP * table)"

.PP
Constructor\&. 
.PP
\fBAuthor:\fP
.RS 4
Ineeve 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016
.RE
.PP
\fBParameters:\fP
.RS 4
\fItable\fP Pointer to the table\&. 
.RE
.PP

.PP
Definition at line 976 of file Casino\&.cpp\&.
.PP
References Table::getTableID()\&.
.PP
.nf
977 {
978     id = table->getTableID();
979 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void ExistingTableException::what ()"

.PP
Displays in terminal what caused this exception to be thrown\&. 
.PP
\fBAuthor:\fP
.RS 4
Ineeve 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 981 of file Casino\&.cpp\&.
.PP
Referenced by Casino::addTableToCasino()\&.
.PP
.nf
982 {
983     cout << "Table ID\&." << id << " already exists in this casino\n";
984 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
