.TH "HumanOnTableException" 3 "Sun Nov 20 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HumanOnTableException \- Exception for signalling that there is a human on the table\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Player\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHumanOnTableException\fP (\fBPlayer\fP *player)"
.br
.RI "Constructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception for signalling that there is a human on the table\&. 


.PP
\fBAuthor:\fP
.RS 4
Joao Carvalho 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 215 of file Player\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HumanOnTableException::HumanOnTableException (\fBPlayer\fP * player)"

.PP
Constructor\&. 
.PP
\fBAuthor:\fP
.RS 4
Joao Carvalho 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016
.RE
.PP
\fBParameters:\fP
.RS 4
\fIplayer\fP Pointer to the player\&. 
.RE
.PP

.PP
Definition at line 1036 of file Player\&.cpp\&.
.PP
References Player::getName()\&.
.PP
.nf
1036                                                             {
1037     this->name = player->getName();
1038 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
