.TH "main.cpp" 3 "Sun Nov 20 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <exception>\fP
.br
\fC#include 'Casino\&.h'\fP
.br
\fC#include 'cmdUI\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 13 of file main\&.cpp\&.
.PP
References Casino::addPlayersToCasino(), Casino::addPlayersToTable(), Casino::addTableToCasino(), centerWindow(), NoPlayersOnTableException::getID(), Casino::getTableToPlay(), Casino::manage(), Table::play(), Casino::readDealersFile(), Casino::readPlayersFile(), Casino::readTablesFile(), readUnsignedInt(), saveChanges(), Casino::saveDealersFile(), Casino::savePlayersFile(), Casino::saveTablesFile(), Casino::selectTable(), Casino::setDealersFile(), Casino::setPlayersFile(), Casino::setTablesFile(), Casino::setTableToPlay(), Casino::showStatistics(), Table::simulation(), start_menu(), and Users()\&.
.PP
.nf
13           {
14     //Center window
15     pair <int, int> xy;
16     xy = centerWindow();
17 
18     //users
19     vector <int> usersVEC;
20     int user = 0;
21     Users(usersVEC, user);
22 
23     //do the code just here
24     //creat a casino
25     string playersFileName = "players\&.txt", dealersFileName = "dealers\&.txt", tablesFileName = "tables\&.txt";
26     Casino casino(100000);
27 
28     //read files names
29     /*cout << "Write file name of players" << endl;
30     readNameOfFile(playersFileName);
31     cout << "Write file name of dealers" << endl;
32     readNameOfFile(dealersFileName);
33     cout << "Write file name of tables" << endl;
34     readNameOfFile(tablesFileName);*/
35 
36     //set files name on casino
37     casino\&.setPlayersFile(playersFileName);
38     casino\&.setDealersFile(dealersFileName);
39     casino\&.setTablesFile(tablesFileName);
40 
41     casino\&.readPlayersFile();
42     casino\&.readDealersFile();
43     casino\&.readTablesFile();
44     /*DEGUB*/
45     /*cout << "Players: " << endl;
46     casino\&.showPlayers();
47     cout << "Dealers: " << endl;
48     casino\&.showDealers();
49     cout << "Tables: " << endl;
50     casino\&.showTables();
51     system("pause");*/
52 
53     unsigned int minBet = 2;
54     unsigned int maxBet = 1000;
55     unsigned int moneyOfTable = 30000;
56     unsigned int maxNumberOfPlayers = 6;
57     Dealer *pro = new Dealer;
58     Table * table1 = new Table(minBet, maxBet, moneyOfTable, maxNumberOfPlayers, pro);
59     vector<Player *> playersVector;
60     playersVector\&.push_back(new Bot0("Kika", 1000));
61     playersVector\&.push_back(new Bot1("Renato", 1000));
62     playersVector\&.push_back(new Bot1("Joao", 1000));
63     playersVector\&.push_back(new Bot0("Rui", 1000));
64     casino\&.addTableToCasino(table1);
65     casino\&.addPlayersToCasino(playersVector);
66     casino\&.addPlayersToTable(playersVector, table1);
67     casino\&.setTableToPlay(-1);
68 
69     /*END OF DEBUG*/
70     int choice, exit = 0;
71     unsigned int roundsToPlay;
72     bool found = false;
73     while (!exit)
74     {
75         start_menu(xy, choice);
76         switch (choice)
77         {
78         case 1:
79             system("CLS");
80             //TODO: play (game run in normal mode with a human player)
81             try
82             {
83                 casino\&.getTableToPlay()->play(xy, user);
84                 system("pause");
85             }
86             catch (TableNotInCasinoException)
87             {
88                 cout << "Please select a table first" << endl;
89                 system("pause");
90             }
91             catch (NoPlayersOnTableException NoPlayersOnTableException)
92             {
93                 cout << "The table: " << NoPlayersOnTableException\&.getID() << " dont have players" << endl;
94                 cout << "Please select a table with players first" << endl;
95                 system("pause");
96             }
97             catch (TooManyPlayersException)
98             {
99                 cout << "You can't play on table selected" << endl;
100                 cout << "The table is full" << endl;
101                 system("pause");
102             }
103             break;
104         case 2:
105             //TODO: simulation (game run all alone for n cycles)
106             cout << "How many rounds do you want to simulate?" << endl;
107             roundsToPlay = readUnsignedInt();
108             try
109             {
110                 casino\&.getTableToPlay()->simulation(roundsToPlay);
111                 casino\&.showStatistics();
112                 system("pause");
113             }
114             catch (TableNotInCasinoException)
115             {
116                 cout << "Please select a table first" << endl;
117                 system("pause");
118             }
119             catch (NoPlayersOnTableException noPlayerOnTable)
120             {
121                 cout << "The table: " << noPlayerOnTable\&.getID() << " dont have players" << endl;
122                 cout << "Please select a table with players first" << endl;
123                 system("pause");
124             }
125             catch (HumanOnTableException)
126             {
127                 cout << "The table has a human" << endl;
128                 cout << "Please select a table with no humans" << endl;
129                 system("pause");
130             }
131             break;
132         case 3:
133             //TODO: choose table (selection one table to play on simulation or normal mode)
134             try
135             {
136                 casino\&.selectTable(xy);
137             }
138             catch (TableNotInCasinoException)
139             {
140                 cout << "This table not exist" << endl;
141             }
142             system("pause");
143             break;
144         case 4:
145             //TODO: menu to creat table, define employee of table, and bots to tables, choose files\&.\&.\&.
146             casino\&.manage(xy);
147             break;
148         case 0:
149             exit = 1;
150             break;
151         default:
152             break;
153         }
154     }
155 
156     //save changes of files
157     int save;
158     saveChanges(usersVEC, user, xy, save);
159     if (save)
160     {
161         casino\&.savePlayersFile();
162         casino\&.saveDealersFile();
163         casino\&.saveTablesFile();
164     }
165 
166     return 0;
167 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
