.TH "NameTooShortException" 3 "Sun Nov 20 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NameTooShortException \- Exception for signalling too short names errors\&. The name is considered to be too short if it has less than 3 characters\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Player\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBwhat\fP ()"
.br
.RI "Displays on terminal what throwed this exception\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception for signalling too short names errors\&. The name is considered to be too short if it has less than 3 characters\&. 


.PP
\fBAuthor:\fP
.RS 4
Joao Carvalho 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 34 of file Player\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void NameTooShortException::what ()"

.PP
Displays on terminal what throwed this exception\&. 
.PP
\fBAuthor:\fP
.RS 4
Joao Carvalho 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 8 of file Player\&.cpp\&.
.PP
Referenced by Human::Human()\&.
.PP
.nf
9 {
10     cout << "Error - A name shoud have no less than 3 characters\n";
11 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
