.TH "Player.cpp" 3 "Sat Nov 19 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Player\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBsurrender\fP (\fBTable\fP &table)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool surrender (\fBTable\fP & table)"

.PP
Definition at line 25 of file Player\&.cpp\&.
.PP
.nf
25                              {
26     return false;
27 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
