.TH "PlayerNotLoggedException" 3 "Sat Nov 19 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerNotLoggedException \- Exception for signalling player not logged in\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Casino\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerNotLoggedException\fP (\fBPlayer\fP *player1)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "void \fBwhat\fP ()"
.br
.RI "Displays in terminal what caused this exception to be thrown\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception for signalling player not logged in\&. 


.PP
\fBAuthor:\fP
.RS 4
Ineeve 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 28 of file Casino\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlayerNotLoggedException::PlayerNotLoggedException (\fBPlayer\fP * player1)"

.PP
Constructor\&. 
.PP
\fBAuthor:\fP
.RS 4
Ineeve 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016
.RE
.PP
\fBParameters:\fP
.RS 4
\fIplayer1\fP Pointer to the player\&. 
.RE
.PP

.PP
Definition at line 966 of file Casino\&.cpp\&.
.PP
References Player::getName()\&.
.PP
.nf
967 {
968     name = player1->getName();
969 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void PlayerNotLoggedException::what ()"

.PP
Displays in terminal what caused this exception to be thrown\&. 
.PP
\fBAuthor:\fP
.RS 4
Ineeve 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 971 of file Casino\&.cpp\&.
.PP
Referenced by Casino::addPlayerToTable()\&.
.PP
.nf
972 {
973     cout << name << " is not logged in this Casino, try to log in first\&.\n";
974 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
