.TH "Player.cpp" 3 "Sun Nov 20 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Player\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBsurrender\fP (\fBTable\fP &table)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool surrender (\fBTable\fP & table)"

.PP
Definition at line 30 of file Player\&.cpp\&.
.PP
.nf
30                              {
31     return false;
32 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
