.TH "PlayerNotExistException" 3 "Sun Nov 20 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerNotExistException \- Exception for signalling that the player does not exist\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Player\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerNotExistException\fP (string name)"
.br
.RI "Constructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception for signalling that the player does not exist\&. 


.PP
\fBAuthor:\fP
.RS 4
Joao Carvalho 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 113 of file Player\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlayerNotExistException::PlayerNotExistException (string name)"

.PP
Constructor\&. 
.PP
\fBAuthor:\fP
.RS 4
Joao Carvalho 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016
.RE
.PP
\fBParameters:\fP
.RS 4
\fIname\fP The player's name\&. 
.RE
.PP

.PP
Definition at line 1019 of file Player\&.cpp\&.
.PP
.nf
1019                                                             {
1020     this->name = name;
1021 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
