.TH "Table.h" 3 "Sat Nov 19 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Table.h \- Declares the table class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Dealer\&.h'\fP
.br
\fC#include 'cmdUI\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTooManyPlayersException\fP"
.br
.RI "Exception for signalling too many players in a table errors\&. "
.ti -1c
.RI "class \fBNoPlayersOnTableException\fP"
.br
.RI "Exception for signalling no players on table errors\&. "
.ti -1c
.RI "class \fBTable\fP"
.br
.RI "A table\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declares the table class\&. 


.PP
Definition in file \fBTable\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
