.TH "TooYoungException" 3 "Sun Nov 20 2016" "Version 1.0.0.0" "Aeda-Casino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TooYoungException \- Exception for signalling age errors\&. A player is considered to be too young if he is less than 18 years old\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Player\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBwhat\fP ()"
.br
.RI "Displays on terminal what throwed this exception\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception for signalling age errors\&. A player is considered to be too young if he is less than 18 years old\&. 


.PP
\fBAuthor:\fP
.RS 4
Joao Carvalho 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 60 of file Player\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void TooYoungException::what ()"

.PP
Displays on terminal what throwed this exception\&. 
.PP
\fBAuthor:\fP
.RS 4
Joao Carvalho 
.RE
.PP
\fBDate:\fP
.RS 4
19/11/2016 
.RE
.PP

.PP
Definition at line 13 of file Player\&.cpp\&.
.PP
Referenced by Human::Human()\&.
.PP
.nf
14 {
15     cout << "Error - In order to play you should be at least 18 years old\n";
16 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Aeda-Casino from the source code\&.
