Aeda-Casino: Casino.cpp File Reference
Casino.cpp File Reference
#include "Casino.h"
Functions
bool sortFunctionPlayers (Player *p1, Player *p2)
bool sortFunctionTables (Table *t1, Table *t2)
bool sortFunctionDealers (Dealer *d1, Dealer *d2)
bool cmpPlayerPointers (Player *p1, Player *p2)
Function Documentation
cmpPlayerPointers()
bool cmpPlayerPointers (Player * p1, Player * p2)
Definition at line 1525 of file Casino.cpp.
References Player::getAverageProfit().
 {
     return p1->getAverageProfit() <= p2->getAverageProfit();
 }
sortFunctionDealers()
bool sortFunctionDealers (Dealer * d1, Dealer * d2)
Definition at line 13 of file Casino.cpp.
References Dealer::getID(), and Dealer::getTableOn().
Referenced by Casino::readTablesFile().
{
     if (d1->getTableOn() == -1 && d2->getTableOn() != -1)
     {
         return true;
     }
     else if (d1->getTableOn() == -1 && d2->getTableOn() == -1)
     {
         return d1->getID() < d2->getID();
     }
     else if (d1->getTableOn() != -1 && d2->getTableOn() != -1)
     {
         return d1->getID() < d2->getID();
     }
     else
     {
         return false;
     }
 }
sortFunctionPlayers()
bool sortFunctionPlayers (Player * p1, Player * p2)
Definition at line 5 of file Casino.cpp.
References Player::getName().
Referenced by Casino::readPlayersFile().
{
     return p1->getName() < p2->getName();
 }
sortFunctionTables()
bool sortFunctionTables (Table * t1, Table * t2)
Definition at line 9 of file Casino.cpp.
References Table::getTableID().
Referenced by Casino::addTableToCasino().
{
     return t1->getTableID() < t2->getTableID();
 }