Aeda-Casino: Player Class Reference
Player Class Reference abstract
A player. Abstract Class. Player is the base class.
#include <Player.h>
Public Member Functions
void hit (Card newCard)
Hits the given new card. Saves the card on the hand. Updates the handscore.
void hit2 (Card newCard)
Hits the given new card. Saves the card on the hand2. Updates the hand2score.
virtual bool takeInsurance (Table &table)
Take insurance.
virtual bool surrender (Table &table)
Surrenders or not. When this method is called, it will check if the player wants to surrender.
virtual bool split (Dealer *dealerOfTable)
Splits his hand or not. When this method is called it will apply an algorithm depending on the type of player, to check if the player wants to split his hand.
void doubleDown ()
Double down. Doubles down the current bet. When a player doubles down, he will hit a new card, double is bet, and won't be allowed to play anymore until the end of the round.
vector< Card > & getHand ()
Gets the hand.
vector< Card > & getHand2 ()
Gets the second hand.
unsigned int getHandSize () const
Gets hand size.
unsigned int getRoundsPlayed () const
Gets rounds played.
float getCurrentMoney () const
Gets current money.
float getAverageProfit () const
Gets average profit.
unsigned int getHandScore () const
Gets hand score.
unsigned int getHand2Score () const
Gets second hand score.
unsigned int getInitialMoney () const
Gets initial money.
string getName () const
Gets the name.
void setAverageProfit (float averageProfit)
Sets the average profit of the player.
void setName (string newName)
Sets a name.
unsigned int setHandScore ()
Sets hand score.
unsigned int setHand2Score ()
Sets second hand score.
void setCurrentMoney (float money)
Sets current money.
void setRoundsPlayed (unsigned int rounds)
Sets rounds played.
void setInitialMoney (unsigned int money)
Sets initial money.
void addMoney (float value)
Adds money to the player.
void showStatistics ()
Shows the statistics.
virtual unsigned int bet (Table &table)
Bets an amount of money. If player is a kind of bot, it will bet accordingly to algorithms that are available on the internet.
void clearHand ()
Clears the hand.
void clearHand2 ()
Clears the second hand.
void setActualBet (unsigned int bet)
Sets actual bet.
unsigned int getActualBet ()
Gets actual bet.
virtual string play (Table &table)=0
Play consists of a method that decides what is the best move. All the bots have different implementations of this method.
virtual int getCurrentCount () const
Gets current count. Different kinds of players may hold different counts.
virtual void addCount (Card &card1)
Updates the current count with a given card.
virtual void resetCount ()
Resets the current count. Should be called when the deck is reshuffled or the table closes.
unsigned int getAge () const
Gets the age.
void setAge (unsigned int age)
Sets an age.
void setOnTable (int tableID)
Sits on a table. -1 if the player is not on any table.
int getOnTable () const
Gets if the player is on table or not.
void removeCardFromFirstHandAndSetItOnSecondHand ()
Removes the card from first hand sets it on the second hand.
virtual void setUserID (unsigned int userID)
Does nothing in class Player. But it is necessary for the human class.
virtual unsigned int getUserID () const
Returns 0;.
virtual ostream & saveInfo (ostream &out)
Writes player info to stream.
Private Attributes
string name
The name.
unsigned int initialMoney
The initial money.
float currentMoney
The current money.
vector< Card > hand
Gets the hand.
vector< Card > hand2
Gets the second hand. A player only has second hand if he decides to split.
unsigned int handScore
The hand score.
unsigned int hand2Score
The second hand score.
unsigned int roundsPlayed
The rounds played.
float averageProfit
The average profit.
unsigned int age
The age.
int onTable
ID of the table that the player is on. -1 if not on any table.
int actualBet
The actual bet.
Detailed Description
A player. Abstract Class. Player is the base class.
Author
Joao Carvalho
Date
19/11/2016
Definition at line 245 of file Player.h.
Member Function Documentation
addCount()
void Player::addCount (Card & card1) virtual
Updates the current count with a given card.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] card1 The card that will try to update the count.
Reimplemented in Bot2, and Bot1.
Definition at line 217 of file Player.cpp.
 {
 }
addMoney()
void Player::addMoney (float value)
Adds money to the player.
Author
Joao Carvalho
Date
19/11/2016
Parameters
value The amount of money to be added.
Definition at line 153 of file Player.cpp.
Referenced by Table::payToPlayer().
 {
     currentMoney += value;
 }
bet()
unsigned int Player::bet (Table & table) virtual
Bets an amount of money. If player is a kind of bot, it will bet accordingly to algorithms that are available on the internet.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
An int.
Reimplemented in Human, Bot2, and Bot1.
Definition at line 178 of file Player.cpp.
References Table::getMinBet().
 {
     if (getCurrentMoney() < table.getMinBet()) {
         return 0; //0 means kick the player from the table;
     }
     unsigned int betValue = table.getMinBet();
     setCurrentMoney(getCurrentMoney() - betValue);
     cout << name << " bets " << betValue << "$\n";
     setActualBet(betValue);
     return betValue;
 }
clearHand()
void Player::clearHand ()
Clears the hand.
Author
Joao Carvalho
Date
19/11/2016
Definition at line 190 of file Player.cpp.
 {
     hand.clear();
     this->setHandScore();
 }
clearHand2()
void Player::clearHand2 ()
Clears the second hand.
Author
Joao Carvalho
Date
19/11/2016
Definition at line 196 of file Player.cpp.
 {
     hand2.clear();
     this->setHand2Score();
 }
doubleDown()
void Player::doubleDown ()
Double down. Doubles down the current bet. When a player doubles down, he will hit a new card, double is bet, and won't be allowed to play anymore until the end of the round.
Author
Joao Carvalho
Date
19/11/2016
Definition at line 35 of file Player.cpp.
{
     throw "Not yet implemented";
 }
getActualBet()
unsigned int Player::getActualBet ()
Gets actual bet.
Author
Joao Carvalho
Date
19/11/2016
Returns
The actual bet.
Definition at line 207 of file Player.cpp.
 {
     return actualBet;
 }
getAge()
unsigned int Player::getAge () const
Gets the age.
Author
Joao Carvalho
Date
19/11/2016
Returns
The player's age.
Definition at line 227 of file Player.cpp.
Referenced by CompareByAge::operator()().
{
     return this->age;
 }
getAverageProfit()
float Player::getAverageProfit () const
Gets average profit.
Author
Joao Carvalho
Date
19/11/2016
Returns
The average profit.
Definition at line 112 of file Player.cpp.
Referenced by cmpPlayerPointers(), and CompareByAverageProfit::operator()().
 {
     return averageProfit;
 }
getCurrentCount()
int Player::getCurrentCount () const virtual
Gets current count. Different kinds of players may hold different counts.
Author
Joao Carvalho
Date
19/11/2016
Returns
The current count.
Reimplemented in Bot2, and Bot1.
Definition at line 212 of file Player.cpp.
 {
     return 0;
 }
getCurrentMoney()
float Player::getCurrentMoney () const
Gets current money.
Author
Joao Carvalho
Date
19/11/2016
Returns
The current money.
Definition at line 123 of file Player.cpp.
 {
     return currentMoney;
 }
getHand()
vector< Card > & Player::getHand ()
Gets the hand.
Author
Joao Carvalho
Date
19/11/2016
Returns
The hand.
Definition at line 39 of file Player.cpp.
 {
     return hand;
 }
getHand2()
vector< Card > & Player::getHand2 ()
Gets the second hand.
Author
Joao Carvalho
Date
19/11/2016
Returns
The second hand.
Definition at line 44 of file Player.cpp.
 {
     return hand2;
 }
getHand2Score()
unsigned int Player::getHand2Score () const
Gets second hand score.
Author
Joao Carvalho
Date
19/11/2016
Returns
The second hand score.
Definition at line 92 of file Player.cpp.
 {
     return hand2Score;
 }
getHandScore()
unsigned int Player::getHandScore () const
Gets hand score.
Author
Joao Carvalho
Date
19/11/2016
Returns
The hand score.
Definition at line 87 of file Player.cpp.
 {
     return handScore;
 }
getHandSize()
unsigned int Player::getHandSize () const
Gets hand size.
Author
Joao Carvalho
Date
19/11/2016
Returns
The hand size.
Definition at line 49 of file Player.cpp.
 {
     return hand.size();
 }
getInitialMoney()
unsigned int Player::getInitialMoney () const
Gets initial money.
Author
Joao Carvalho
Date
19/11/2016
Returns
The initial money.
Definition at line 128 of file Player.cpp.
 {
     return initialMoney;
 }
getName()
string Player::getName () const
Gets the name.
Author
Joao Carvalho
Date
19/11/2016
Returns
The name.
Definition at line 97 of file Player.cpp.
Referenced by Casino::addPlayerToCasino(), HumanOnTableException::HumanOnTableException(), CompareByAge::operator()(), CompareByName::operator()(), CompareByIntelligence::operator()(), PlayerAlreadyExistException::PlayerAlreadyExistException(), PlayerNotLoggedException::PlayerNotLoggedException(), PlayerStillOnTableException::PlayerStillOnTableException(), Casino::readTablesFile(), and sortFunctionPlayers().
 {
     return name;
 }
getOnTable()
int Player::getOnTable () const
Gets if the player is on table or not.
Author
Joao Carvalho
Date
19/11/2016
Returns
ID of the table. -1 if the player is not on any table.
Definition at line 239 of file Player.cpp.
Referenced by PlayerStillOnTableException::PlayerStillOnTableException().
{
     return this->onTable;
 }
getRoundsPlayed()
unsigned int Player::getRoundsPlayed () const
Gets rounds played.
Author
Joao Carvalho
Date
19/11/2016
Returns
The rounds played.
Definition at line 135 of file Player.cpp.
 {
     return roundsPlayed;
 }
getUserID()
unsigned int Player::getUserID () const inline virtual
Returns 0;.
Returns
0.
Author
Joao Carvalho
Date
19/11/2016
Reimplemented in Human.
Definition at line 833 of file Player.h.
 { return 0; }
hit()
void Player::hit (Card newCard)
Hits the given new card. Saves the card on the hand. Updates the handscore.
Author
Joao Carvalho
Date
19/11/2016
Parameters
newCard The new card.
Definition at line 20 of file Player.cpp.
{
     hand.push_back(newCard);
     setHandScore();
 }
hit2()
void Player::hit2 (Card newCard)
Hits the given new card. Saves the card on the hand2. Updates the hand2score.
Author
Joao Carvalho
Date
19/11/2016
Parameters
newCard The new card.
Definition at line 25 of file Player.cpp.
{
     hand2.push_back(newCard);
     setHand2Score();
 }
play()
string Player::play (Table & table) pure virtual
Play consists of a method that decides what is the best move. All the bots have different implementations of this method.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table that the player is on.
Returns
A string with the option selected, "hit","stand" or "double".
Implemented in Human, Bot2, Bot1, and Bot0.
removeCardFromFirstHandAndSetItOnSecondHand()
void Player::removeCardFromFirstHandAndSetItOnSecondHand ()
Removes the card from first hand sets it on the second hand.
Author
Joao Carvalho
Date
19/11/2016
Definition at line 243 of file Player.cpp.
 {
     Card secondCard = hand.at(1);
     hand.pop_back();
     hand2.push_back(secondCard);
 }
resetCount()
void Player::resetCount () virtual
Resets the current count. Should be called when the deck is reshuffled or the table closes.
Author
Joao Carvalho
Date
19/11/2016
Reimplemented in Bot2, and Bot1.
Definition at line 222 of file Player.cpp.
 {
 }
saveInfo()
ostream & Player::saveInfo (ostream & out) virtual
Writes player info to stream.
Parameters
[in,out] out ostream in which player info will be saved.
Returns
Player info in a ostream
Author
Joao Carvalho
Date
19/11/2016
Reimplemented in Human, Bot2, Bot1, and Bot0.
Definition at line 250 of file Player.cpp.
Referenced by Bot0::saveInfo(), Bot1::saveInfo(), Bot2::saveInfo(), and Human::saveInfo().
{
     out << name << "; " << initialMoney << "; " << setprecision(2) << fixed << currentMoney << "; ";
     if (hand.size() != 0)
     {
         out << "{";
     }
     for (size_t i = 0; i < hand.size(); i++)
     {
         out << hand.at(i).rank << "/" << hand.at(i).suits << "/" << hand.at(i).score << "; ";
     }
     if (hand.size() != 0)
     {
         out << "}; ";
     }
     if (hand2.size() != 0)
     {
         out << "{";
     }
     for (size_t i = 0; i < hand2.size(); i++)
     {
         out << hand2.at(i).rank << "/" << hand2.at(i).suits << "/" << hand2.at(i).score << "; ";
     }
     if (hand2.size() != 0)
     {
         out << "}; ";
     }
     out << roundsPlayed << "; " << age << "; " << onTable << "; " << actualBet << "; ";
     return out;
 }
setActualBet()
void Player::setActualBet (unsigned int bet)
Sets actual bet.
Author
Joao Carvalho
Date
19/11/2016
Parameters
bet The money to bet.
Definition at line 202 of file Player.cpp.
 {
     actualBet = bet;
 }
setAge()
void Player::setAge (unsigned int age)
Sets an age.
Author
Joao Carvalho
Date
19/11/2016
Parameters
age The age.
Definition at line 231 of file Player.cpp.
{
     this->age = age;
 }
setAverageProfit()
void Player::setAverageProfit (float averageProfit)
Sets the average profit of the player.
Author
Joao Carvalho
Date
27/12/2016
Parameters
averageProfit Average profit of the player.
Definition at line 102 of file Player.cpp.
 {
     this->averageProfit = averageProfit;
 }
setCurrentMoney()
void Player::setCurrentMoney (float money)
Sets current money.
Author
Joao Carvalho
Date
19/11/2016
Parameters
money The money.
Definition at line 117 of file Player.cpp.
 {
     currentMoney = money;
 }
setHand2Score()
unsigned int Player::setHand2Score ()
Sets second hand score.
Author
Joao Carvalho
Date
19/11/2016
Returns
The second hand score.
Definition at line 70 of file Player.cpp.
 {
     this->hand2Score = 0;
     for (size_t i = 0; i < hand2.size(); i++)
     {
         this->hand2Score += hand2.at(i).score;
     }
     if (hand2Score > 21) {
         for (size_t i = 0; i < hand2.size(); i++) {
             if (hand2.at(i).score == 11 && hand2Score > 21) {
                 this->hand2Score -= 10;
             }
         }
     }
     return this->hand2Score;
 }
setHandScore()
unsigned int Player::setHandScore ()
Sets hand score.
Author
Joao Carvalho
Date
19/11/2016
Returns
The current hand score.
Definition at line 54 of file Player.cpp.
{
     this->handScore = 0;
     for (size_t i = 0; i < hand.size(); i++)
     {
         this->handScore += hand.at(i).score;
     }
     if (handScore > 21) {
         for (size_t i = 0; i < hand.size(); i++) {
             if (hand.at(i).score == 11 && handScore > 21) {
                 this->handScore -= 10;
             }
         }
     }
     return this->handScore;
 }
setInitialMoney()
void Player::setInitialMoney (unsigned int money)
Sets initial money.
Author
Joao Carvalho
Date
19/11/2016
Parameters
money The money.
Definition at line 145 of file Player.cpp.
Referenced by Casino::readPlayersFile().
 {
     initialMoney = money;
     currentMoney = initialMoney;
     averageProfit = 0;
     roundsPlayed = 0;
 }
setName()
void Player::setName (string newName)
Sets a name.
Author
Joao Carvalho
Date
19/11/2016
Parameters
newName Name of the player.
Definition at line 107 of file Player.cpp.
 {
     name = newName;
 }
setOnTable()
void Player::setOnTable (int tableID)
Sits on a table. -1 if the player is not on any table.
Author
Joao Carvalho
Date
19/11/2016
Parameters
tableID Identifier for the table.
Definition at line 235 of file Player.cpp.
Referenced by Table::addPlayer(), and Casino::readPlayersFile().
{
     this->onTable = tableID;
 }
setRoundsPlayed()
void Player::setRoundsPlayed (unsigned int rounds)
Sets rounds played.
Author
Joao Carvalho
Date
19/11/2016
Parameters
rounds The number of rounds.
Definition at line 140 of file Player.cpp.
 {
     roundsPlayed = rounds;
 }
setUserID()
void Player::setUserID (unsigned int userID) inline virtual
Does nothing in class Player. But it is necessary for the human class.
Author
Joao Carvalho
Date
19/11/2016
Reimplemented in Human.
Definition at line 822 of file Player.h.
 {}
showStatistics()
void Player::showStatistics ()
Shows the statistics.
Author
Joao Carvalho
Date
19/11/2016
Definition at line 158 of file Player.cpp.
 {
     Bot0 *bot0 = dynamic_cast<Bot0*> (this);
     Bot1 *bot1 = dynamic_cast<Bot1*> (this);
     Bot2 *bot2 = dynamic_cast<Bot2*> (this);
     cout << setw(15) << "Bot " << name;
     if (bot0 != nullptr) {
         cout << setw(25-name.length()) << "0";
     }
     else if (bot1 != nullptr){
         cout << setw(25 - name.length()) << "1";
     }
     else if (bot2 != nullptr) {
         cout << setw(25 - name.length()) << "2";
     }
     cout << setw(15) << roundsPlayed << setw(10) << setprecision(2) << averageProfit << " $/rnd" <<setw(15) << age << "\n";
 }
split()
bool Player::split (Dealer * dealerOfTable) virtual
Splits his hand or not. When this method is called it will apply an algorithm depending on the type of player, to check if the player wants to split his hand.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] dealerOfTable Pointer to the dealer of the table.
Returns
True if it succeeds, false if it fails.
Reimplemented in Human, Bot2, and Bot1.
Definition at line 289 of file Player.cpp.
{
     return false;
 }
surrender()
bool Player::surrender (Table & table) virtual
Surrenders or not. When this method is called, it will check if the player wants to surrender.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table that the player is on.
Returns
True if it succeeds, false if it fails.
Reimplemented in Bot2, and Bot1.
Definition at line 284 of file Player.cpp.
 {
     return false;
 }
takeInsurance()
bool Player::takeInsurance (Table & table) virtual
Take insurance.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table that the player is on.
Returns
True if it succeeds, false if it fails.
Reimplemented in Human, Bot2, Bot1, and Bot0.
Definition at line 280 of file Player.cpp.
{
     return false;
 }
Member Data Documentation
actualBet
int Player::actualBet private
The actual bet.
Definition at line 288 of file Player.h.
age
unsigned int Player::age private
The age.
Definition at line 284 of file Player.h.
averageProfit
float Player::averageProfit private
The average profit.
Definition at line 282 of file Player.h.
currentMoney
float Player::currentMoney private
The current money.
Definition at line 252 of file Player.h.
hand
vector< Card > Player::hand private
Gets the hand.
Returns
The hand.
Definition at line 262 of file Player.h.
hand2
vector< Card > Player::hand2 private
Gets the second hand. A player only has second hand if he decides to split.
Returns
The second hand.
Definition at line 274 of file Player.h.
hand2Score
unsigned int Player::hand2Score private
The second hand score.
Definition at line 278 of file Player.h.
handScore
unsigned int Player::handScore private
The hand score.
Definition at line 276 of file Player.h.
initialMoney
unsigned int Player::initialMoney private
The initial money.
Definition at line 250 of file Player.h.
name
string Player::name private
The name.
Definition at line 248 of file Player.h.
onTable
int Player::onTable private
ID of the table that the player is on. -1 if not on any table.
Definition at line 286 of file Player.h.
roundsPlayed
unsigned int Player::roundsPlayed private
The rounds played.
Definition at line 280 of file Player.h.
The documentation for this class was generated from the following files:
Player.h
Player.cpp