Aeda-Casino: TooManyPlayersException Class Reference
TooManyPlayersException Class Reference
Exception for signalling too many players in a table errors.
#include <Table.h>
Public Member Functions
TooManyPlayersException (unsigned int maxNumberOfPlayers, unsigned int actualNumOfPlayers)
Constructor.
void what ()
Displays information about this exception.
Detailed Description
Exception for signalling too many players in a table errors.
Author
Renato Campos
Date
18/11/2016
Definition at line 32 of file Table.h.
Constructor & Destructor Documentation
TooManyPlayersException()
TooManyPlayersException::TooManyPlayersException (unsigned int maxNumberOfPlayers, unsigned int actualNumOfPlayers)
Constructor.
Author
Renato Campos
Date
18/11/2016
Parameters
maxNumberOfPlayers The maximum number of players.
actualNumOfPlayers The actual number of players.
Definition at line 1057 of file Table.cpp.
Referenced by Table::addPlayers(), and Table::play().
 {
     this->maxNumberOfPlayers = maxNumberOfPlayers;
     this->actualNumOfPlayers = actualNumOfPlayers;
 }
Member Function Documentation
what()
void TooManyPlayersException::what ()
Displays information about this exception.
Author
Renato Campos
Date
18/11/2016
Definition at line 8 of file Table.cpp.
Referenced by Casino::addPlayerToTable().
 {
     cout << "Error while loading players to table\n";
     cout << "The table already has " << actualNumOfPlayers << "out of " << maxNumberOfPlayers << " players\n";
 }
The documentation for this class was generated from the following files:
Table.h
Table.cpp