Aeda-Casino: Bot2 Class Reference
Bot2 Class Reference
Bot of type 2. This bot plays using the Ace/Five Count strategy guide.
#include <Player.h>
Public Member Functions
Bot2 (string name, unsigned int initialMoney)
Constructor.
Bot2 (string &line)
Constructor.
unsigned int bet (Table &table)
Bets according to the Ace/Five guidelines.
string play (Table &table)
Plays according to the Ace/Five rules.
bool takeInsurance (Table &table)
Ckeck if bot2 wants to take insurance. Bot2 never takes insurance.
bool split (Dealer *dealerOfTable)
Checks if the bot wants to split. Bot2 never splits.
virtual bool surrender (Table &table)
Surrenders or not.
int getCurrentCount () const
Gets the current count.
void addCount (Card &card1)
Updates the counter with a given card.
void resetCount ()
Resets the counter.
void setLastBetValue (unsigned int lastBet)
Sets last bet value.
virtual ostream & saveInfo (ostream &out)
Writes Bot2 info to stream.
Public Member Functions inherited from Player
void hit (Card newCard)
Hits the given new card. Saves the card on the hand. Updates the handscore.
void hit2 (Card newCard)
Hits the given new card. Saves the card on the hand2. Updates the hand2score.
void doubleDown ()
Double down. Doubles down the current bet. When a player doubles down, he will hit a new card, double is bet, and won't be allowed to play anymore until the end of the round.
vector< Card > & getHand ()
Gets the hand.
vector< Card > & getHand2 ()
Gets the second hand.
unsigned int getHandSize () const
Gets hand size.
unsigned int getRoundsPlayed () const
Gets rounds played.
float getCurrentMoney () const
Gets current money.
float getAverageProfit () const
Gets average profit.
unsigned int getHandScore () const
Gets hand score.
unsigned int getHand2Score () const
Gets second hand score.
unsigned int getInitialMoney () const
Gets initial money.
string getName () const
Gets the name.
void setAverageProfit (float averageProfit)
Sets the average profit of the player.
void setName (string newName)
Sets a name.
unsigned int setHandScore ()
Sets hand score.
unsigned int setHand2Score ()
Sets second hand score.
void setCurrentMoney (float money)
Sets current money.
void setRoundsPlayed (unsigned int rounds)
Sets rounds played.
void setInitialMoney (unsigned int money)
Sets initial money.
void addMoney (float value)
Adds money to the player.
void showStatistics ()
Shows the statistics.
void clearHand ()
Clears the hand.
void clearHand2 ()
Clears the second hand.
void setActualBet (unsigned int bet)
Sets actual bet.
unsigned int getActualBet ()
Gets actual bet.
unsigned int getAge () const
Gets the age.
void setAge (unsigned int age)
Sets an age.
void setOnTable (int tableID)
Sits on a table. -1 if the player is not on any table.
int getOnTable () const
Gets if the player is on table or not.
void removeCardFromFirstHandAndSetItOnSecondHand ()
Removes the card from first hand sets it on the second hand.
virtual void setUserID (unsigned int userID)
Does nothing in class Player. But it is necessary for the human class.
virtual unsigned int getUserID () const
Returns 0;.
Private Attributes
int currentCount
Current counter.
unsigned int lastBetValue
The last bet value.
Detailed Description
Bot of type 2. This bot plays using the Ace/Five Count strategy guide.
Author
Joao Carvalho
Date
19/11/2016
Definition at line 1126 of file Player.h.
Constructor & Destructor Documentation
Bot2() [1/2]
Bot2::Bot2 (string name, unsigned int initialMoney)
Constructor.
Author
Joao Carvalho
Date
19/11/2016
Parameters
name The name.
initialMoney The initial money.
Definition at line 694 of file Player.cpp.
 {
     this->setOnTable(-1);
     setName(name);
     setInitialMoney(initialMoney);
     currentCount = 0;
 }
Bot2() [2/2]
Bot2::Bot2 (string & line)
Constructor.
Author
Joao Carvalho
Date
19/11/2016
Parameters
line Line contains all information.
Definition at line 702 of file Player.cpp.
References Card::rank, Card::score, and Card::suits.
{
     line.erase(0, line.find_first_of(";") + 2);
     this->setName(line.substr(0, line.find_first_of(";")));
     line.erase(0, line.find_first_of(";") + 2);
     this->setInitialMoney(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setCurrentMoney(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->clearHand();
     if (line.at(0) == '{')
     {
         line.erase(0, 1);
         Card newCard;
         while (line.at(0) != '}')
         {
             newCard.rank = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.suits = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.score = stoi(line.substr(0, line.find_first_of(";")));
             line.erase(0, line.find_first_of(";") + 2);
             this->hit(newCard);
         }
         line.erase(0, line.find_first_of(";") + 2);
     }
     this->clearHand2();
     if (line.at(0) == '{')
     {
         line.erase(0, 1);
         Card newCard;
         while (line.at(0) != '}')
         {
             newCard.rank = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.suits = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.score = stoi(line.substr(0, line.find_first_of(";")));
             line.erase(0, line.find_first_of(";") + 2);
             this->hit2(newCard);
         }
         line.erase(0, line.find_first_of(";") + 2);
     }
     this->setRoundsPlayed(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setAge(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setOnTable(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setActualBet(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->currentCount = stoi(line.substr(0, line.find_first_of(";")));
     line.erase(0, line.find_first_of(";") + 2);
     this->lastBetValue = stoi(line.substr(0, line.find_first_of(";")));
     line.erase(0, line.find_first_of(";") + 2);
 }
Member Function Documentation
addCount()
void Bot2::addCount (Card & card1) virtual
Updates the counter with a given card.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] card1 The card to update the counter.
Reimplemented from Player.
Definition at line 828 of file Player.cpp.
References Card::score.
 {
     if (card1.score == 5) {
         currentCount++;
     }
     else if (card1.score == 11) {
         currentCount--;
     }
 }
bet()
unsigned int Bot2::bet (Table & table) virtual
Bets according to the Ace/Five guidelines.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
The initial bet value.
Reimplemented from Player.
Definition at line 758 of file Player.cpp.
References Table::getMaxBet(), and Table::getMinBet().
 {
     unsigned int betValue;
     if (getCurrentMoney() < table.getMinBet()) {
         return 0; //0 means kick the player from the table;
     }
     if (currentCount < 2) {
         betValue = table.getMinBet();
     }
     else
     {
         betValue = 2 * lastBetValue;
         if (betValue > table.getMaxBet()) {
             betValue = table.getMaxBet();
         }
     }
     if (betValue > getCurrentMoney()) {
         betValue = getCurrentMoney();
     }
     lastBetValue = betValue;
     setCurrentMoney(getCurrentMoney() - betValue);
     setActualBet(betValue);
     return betValue;
 }
getCurrentCount()
int Bot2::getCurrentCount () const virtual
Gets the current count.
Author
Joao Carvalho
Date
19/11/2016
Returns
The current count.
Reimplemented from Player.
Definition at line 823 of file Player.cpp.
 {
     return currentCount;
 }
play()
string Bot2::play (Table & table) virtual
Plays according to the Ace/Five rules.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
A string.
Implements Player.
Definition at line 783 of file Player.cpp.
References Dealer::discard(), Table::getDealer(), and Table::getPlayers().
 {
     string options[] = { "hit","stand" };
     unsigned int handScore = getHandScore();
     if (handScore < 17) {
         hit(table.getDealer()->discard(table.getPlayers()));
         return options[0]; // 0 means hit
     }
     return options[1]; // means stand
 }
resetCount()
void Bot2::resetCount () virtual
Resets the counter.
Author
Joao Carvalho
Date
19/11/2016
Reimplemented from Player.
Definition at line 838 of file Player.cpp.
 {
     currentCount = 0;
 }
saveInfo()
ostream & Bot2::saveInfo (ostream & out) virtual
Writes Bot2 info to stream.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] out ostream in which Bot2 info will be saved.
Returns
Bot2 info in a ostream.
Reimplemented from Player.
Definition at line 848 of file Player.cpp.
References Player::saveInfo().
{
     out << "2; ";
     Player::saveInfo(out);
     out << currentCount << "; " << lastBetValue << "; ";
     return out;
 }
setLastBetValue()
void Bot2::setLastBetValue (unsigned int lastBet)
Sets last bet value.
Author
Joao Carvalho
Date
19/11/2016
Parameters
lastBet The last bet.
Definition at line 843 of file Player.cpp.
 {
     lastBetValue = lastBet;
 }
split()
bool Bot2::split (Dealer * dealerOfTable) virtual
Checks if the bot wants to split. Bot2 never splits.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] dealerOfTable Pointer to the dealer of the table.
Returns
False.
Reimplemented from Player.
Definition at line 798 of file Player.cpp.
{
     return false;
 }
surrender()
bool Bot2::surrender (Table & table) virtual
Surrenders or not.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
True if it surrenders, false if it does not.
Reimplemented from Player.
Definition at line 802 of file Player.cpp.
References Table::getDealer(), and Dealer::getHandScore().
 {
     //based on fab4 surrender guides
     unsigned int dealerHandScore = table.getDealer()->getHandScore();
     unsigned int personalScore = getHandScore();
     if (personalScore == 14 && dealerHandScore == 10 && currentCount >= 3) {
         return true;
     }
     else if (personalScore == 15 && dealerHandScore == 10 && currentCount >= 0) {
         return true;
     }
     else if (personalScore == 15 && dealerHandScore == 9 && currentCount >= 2) {
         return true;
     }
     else if (personalScore == 15 && dealerHandScore == 11 && currentCount >= 1) {
         return true;
     }
     return false;
 }
takeInsurance()
bool Bot2::takeInsurance (Table & table) virtual
Ckeck if bot2 wants to take insurance. Bot2 never takes insurance.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
False.
Reimplemented from Player.
Definition at line 794 of file Player.cpp.
{
     return false;
 }
Member Data Documentation
currentCount
int Bot2::currentCount private
Current counter.
Definition at line 1129 of file Player.h.
lastBetValue
unsigned int Bot2::lastBetValue private
The last bet value.
Definition at line 1131 of file Player.h.
The documentation for this class was generated from the following files:
Player.h
Player.cpp