Aeda-Casino: Bot1 Class Reference
Bot1 Class Reference
Bot of type 1. This bot plays using the hi-lo counting system. His decisions are based on the illustrious18 and the fab4 surrender guides.
#include <Player.h>
Public Member Functions
unsigned int bet (Table &table)
Places an initial bet that depends on the current count.
Bot1 (string name, unsigned int initialMoney)
Constructor.
Bot1 (string &line)
Constructor.
string play (Table &table)
Plays using the illustrious18 guides.
bool takeInsurance (Table &table)
Take insurance if current count >= 3;.
int getCurrentCount () const
Gets current count.
void addCount (Card &card1)
Updates the current counter with a new card.
void resetCount ()
Resets the current counter.
bool split (Dealer *dealerOfTable)
Splits the hand or not.
virtual bool surrender (Table &table)
Surrenders or not. Surrender algorithm is based on the fab4 surrender guides.
virtual ostream & saveInfo (ostream &out)
Writes Bot1 info to stream.
Public Member Functions inherited from Player
void hit (Card newCard)
Hits the given new card. Saves the card on the hand. Updates the handscore.
void hit2 (Card newCard)
Hits the given new card. Saves the card on the hand2. Updates the hand2score.
void doubleDown ()
Double down. Doubles down the current bet. When a player doubles down, he will hit a new card, double is bet, and won't be allowed to play anymore until the end of the round.
vector< Card > & getHand ()
Gets the hand.
vector< Card > & getHand2 ()
Gets the second hand.
unsigned int getHandSize () const
Gets hand size.
unsigned int getRoundsPlayed () const
Gets rounds played.
float getCurrentMoney () const
Gets current money.
float getAverageProfit () const
Gets average profit.
unsigned int getHandScore () const
Gets hand score.
unsigned int getHand2Score () const
Gets second hand score.
unsigned int getInitialMoney () const
Gets initial money.
string getName () const
Gets the name.
void setAverageProfit (float averageProfit)
Sets the average profit of the player.
void setName (string newName)
Sets a name.
unsigned int setHandScore ()
Sets hand score.
unsigned int setHand2Score ()
Sets second hand score.
void setCurrentMoney (float money)
Sets current money.
void setRoundsPlayed (unsigned int rounds)
Sets rounds played.
void setInitialMoney (unsigned int money)
Sets initial money.
void addMoney (float value)
Adds money to the player.
void showStatistics ()
Shows the statistics.
void clearHand ()
Clears the hand.
void clearHand2 ()
Clears the second hand.
void setActualBet (unsigned int bet)
Sets actual bet.
unsigned int getActualBet ()
Gets actual bet.
unsigned int getAge () const
Gets the age.
void setAge (unsigned int age)
Sets an age.
void setOnTable (int tableID)
Sits on a table. -1 if the player is not on any table.
int getOnTable () const
Gets if the player is on table or not.
void removeCardFromFirstHandAndSetItOnSecondHand ()
Removes the card from first hand sets it on the second hand.
virtual void setUserID (unsigned int userID)
Does nothing in class Player. But it is necessary for the human class.
virtual unsigned int getUserID () const
Returns 0;.
Private Attributes
int currentCount
The current count.
Detailed Description
Bot of type 1. This bot plays using the hi-lo counting system. His decisions are based on the illustrious18 and the fab4 surrender guides.
Author
Joao Carvalho
Date
19/11/2016
Definition at line 956 of file Player.h.
Constructor & Destructor Documentation
Bot1() [1/2]
Bot1::Bot1 (string name, unsigned int initialMoney)
Constructor.
Author
Joao Carvalho
Date
19/11/2016
Parameters
name The name.
initialMoney The initial money.
Definition at line 494 of file Player.cpp.
 {
     this->setOnTable(-1);
     this->setName(name);
     this->setInitialMoney(initialMoney);
 }
Bot1() [2/2]
Bot1::Bot1 (string & line)
Constructor.
Author
Joao Carvalho
Date
19/11/2016
Parameters
line Line containes all information.
Definition at line 501 of file Player.cpp.
References Card::rank, Card::score, and Card::suits.
{
     line.erase(0, line.find_first_of(";") + 2);
     this->setName(line.substr(0, line.find_first_of(";")));
     line.erase(0, line.find_first_of(";") + 2);
     this->setInitialMoney(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setCurrentMoney(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->clearHand();
     if (line.at(0) == '{')
     {
         line.erase(0, 1);
         Card newCard;
         while (line.at(0) != '}')
         {
             newCard.rank = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.suits = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.score = stoi(line.substr(0, line.find_first_of(";")));
             line.erase(0, line.find_first_of(";") + 2);
             this->hit(newCard);
         }
         line.erase(0, line.find_first_of(";") + 2);
     }
     this->clearHand2();
     if (line.at(0) == '{')
     {
         line.erase(0, 1);
         Card newCard;
         while (line.at(0) != '}')
         {
             newCard.rank = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.suits = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.score = stoi(line.substr(0, line.find_first_of(";")));
             line.erase(0, line.find_first_of(";") + 2);
             this->hit2(newCard);
         }
         line.erase(0, line.find_first_of(";") + 2);
     }
     this->setRoundsPlayed(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setAge(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setOnTable(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setActualBet(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->currentCount = stoi(line.substr(0, line.find_first_of(";")));
     line.erase(0, line.find_first_of(";") + 2);
 }
Member Function Documentation
addCount()
void Bot1::addCount (Card & card1) virtual
Updates the current counter with a new card.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] card1 The card to update the counter.
Reimplemented from Player.
Definition at line 676 of file Player.cpp.
References Card::score.
 {
     int score = card1.score;
     if (card1.score <= 6) {
         currentCount++;
     }
     else if (card1.score >= 10) {
         currentCount--;
     }
 }
bet()
unsigned int Bot1::bet (Table & table) virtual
Places an initial bet that depends on the current count.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
The amount bet.
Reimplemented from Player.
Definition at line 436 of file Player.cpp.
References Table::getMaxBet(), and Table::getMinBet().
{
     float currentMoney = getCurrentMoney();
     if (currentMoney < table.getMinBet()){
         return 0; //0 means kick the player from the table;
     }
     int trueCount = currentCount;
     cout << "Current running count =" << trueCount << ".\n";
     unsigned int betValue;
     if (trueCount <= 0) {
         betValue = table.getMinBet();
     }
     else if (trueCount == 1) {
         if (2 * table.getMinBet() > table.getMaxBet()) {
             betValue = table.getMaxBet();
         }
         else {
             betValue = 2 * table.getMinBet();
         }
     }
     else if (trueCount == 2) {
         if (3 * table.getMinBet() > table.getMaxBet()) {
             betValue = table.getMaxBet();
         }
         else { betValue = 3 * table.getMinBet(); }
     }
     else if (trueCount == 3) {
         if (4 * table.getMinBet() > table.getMaxBet()) {
             betValue = table.getMaxBet();
         }
         else {
             betValue = 4 * table.getMinBet();
         }
     }
     else if (trueCount == 4) {
         if (5 * table.getMinBet() > table.getMaxBet()) {
             betValue = table.getMaxBet();
         }
         else {
             betValue = 5 * table.getMinBet();
         }
     }
     else if (trueCount >= 5) {
         if (6 * table.getMinBet() > table.getMaxBet()) {
             betValue = table.getMaxBet();
         }
         else {
             betValue = 6 * table.getMinBet();
         }
     }
     if (betValue > currentMoney) {
         betValue = currentMoney;
     }
     setCurrentMoney(currentMoney - betValue);
     cout << getName() << " bets " << betValue << "$\n";
     setActualBet(betValue);
     return betValue;
 }
getCurrentCount()
int Bot1::getCurrentCount () const virtual
Gets current count.
Author
Joao Carvalho
Date
19/11/2016
Returns
The current count.
Reimplemented from Player.
Definition at line 671 of file Player.cpp.
 {
     return currentCount;
 }
play()
string Bot1::play (Table & table) virtual
Plays using the illustrious18 guides.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
A string: "hit","stand" or "double"
Implements Player.
Definition at line 555 of file Player.cpp.
References Table::addMoneyToTable(), Dealer::discard(), Table::getDealer(), Dealer::getHand(), Table::getPlayers(), and Card::score.
 {
     string options[] = {"hit", "stand","double"};
     string option;
     Dealer * dealerOfTable = table.getDealer();
     unsigned int botHandScore = getHandScore();
     Card dealerCard1 = dealerOfTable->getHand().at(0);
     int runningCount = currentCount;
     if (botHandScore == 16 && dealerCard1.score == 10) {
         if (runningCount < 0) {
             option = options[0];
         }else option = options[1];
     }
     else if (botHandScore == 15 && dealerCard1.score == 10) {
         if (runningCount < 4) {
             option =  options[0];
         } else option = options[1];
     }
     else if (botHandScore == 10 && dealerCard1.score == 10) {
         if (runningCount < 4) {
             option = options[0];
         }
         else option = options[2];
     }
     else if (botHandScore == 12 && dealerCard1.score == 3) {
         if (runningCount < 2) {
             option =  options[0];
         }else
         option =  options[1];
     }
     else if (botHandScore == 12 && dealerCard1.score == 2) {
         if (runningCount < 3) {
             option =  options[0];
         }else
         option =  options[1];
     }
     else if (botHandScore == 11 && dealerCard1.score == 11) {
         if (runningCount < 1) {
             option = options[0];
         }
         else
             option = options[2];
     }
     else if (botHandScore == 9 && dealerCard1.score==2) {
         if (runningCount < 1) {
             option = options[0];
         }
         else
             option = options[2];
     }
     else if (botHandScore == 10 && dealerCard1.score == 11){
         if (runningCount < 4) {
             option = options[0];
         }
         else
             option = options[2];
     }
     else if (botHandScore == 9 && dealerCard1.score == 7) {
         if (runningCount < 3) {
             option = options[0];
         }
         else
             option = options[2];
     }
     else if (botHandScore == 13 && dealerCard1.score == 2) {
         if (runningCount < -1) {
             option =  options[0];
         }else
         option =  options[1];
     }
     else if (botHandScore == 12 && dealerCard1.score == 4) {
             if (runningCount < 0) {
                 option =  options[0];
             }else
             option =  options[1];
         }
     else if (botHandScore == 12 && dealerCard1.score == 5) {
             if (runningCount < -2) {
                 option =  options[0];
             }else
             option =  options[1];
         }
     else if (botHandScore == 12 && dealerCard1.score == 6) {
             if (runningCount < -1) {
                 option =  options[0];
             }else
             option =  options[1];
     }
     else if (botHandScore == 13 && dealerCard1.score == 3){
         if (runningCount < -2){
             option =  options[0];
         }else
         option =  options[1];
     }
     else if (botHandScore < 17) {
         option =  options[0];
     }
     else {
         option = options[1];
     }
     if (option == options[0]) {
         hit(dealerOfTable->discard(table.getPlayers()));
     }
     if (option == options[2]) {
         hit(dealerOfTable->discard(table.getPlayers()));
         setCurrentMoney(getCurrentMoney() - getActualBet());
         table.addMoneyToTable(getActualBet());
         setActualBet(2 * getActualBet());
     }
     return option; // means stand
 }
resetCount()
void Bot1::resetCount () virtual
Resets the current counter.
Author
Joao Carvalho
Date
19/11/2016
Reimplemented from Player.
Definition at line 687 of file Player.cpp.
 {
     currentCount = 0;
 }
saveInfo()
ostream & Bot1::saveInfo (ostream & out) virtual
Writes Bot1 info to stream.
Author
Joao Carvalho
Date
19/11/2016
Parameters
out ostream in which Bot1 info will be saved.
Returns
[in,out] Bot1 info in a ostream.
Reimplemented from Player.
Definition at line 429 of file Player.cpp.
References Player::saveInfo().
{
     out << "1; ";
     Player::saveInfo(out);
     out << currentCount << "; ";
     return out;
 }
split()
bool Bot1::split (Dealer * dealerOfTable) virtual
Splits the hand or not.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] dealerOfTable Poiner to the dealer of the table.
Returns
True if it splits, false if it does not.
Reimplemented from Player.
Definition at line 387 of file Player.cpp.
References Dealer::getHand(), and Card::score.
{
     vector<Card> hand1 = getHand();
     Card dealerFirstCard = dealerOfTable->getHand().at(0);
     if (hand1.at(0) == hand1.at(1)) {
         if (hand1.at(0).score == 10) {
             if (currentCount >= 5 && dealerFirstCard.score == 5) {
                 removeCardFromFirstHandAndSetItOnSecondHand();
                 setHand2Score();
                 setHandScore();
                 return true;
             }
             else if (currentCount >= 4 && dealerFirstCard.score == 6) {
                 removeCardFromFirstHandAndSetItOnSecondHand();
                 setHand2Score();
                 setHandScore();
                 return true;
             }
         }
     }
     return false;
 }
surrender()
bool Bot1::surrender (Table & table) virtual
Surrenders or not. Surrender algorithm is based on the fab4 surrender guides.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
True if it surrenders, false if it does not.
Reimplemented from Player.
Definition at line 410 of file Player.cpp.
References Table::getDealer(), and Dealer::getHandScore().
 {   //based on fab4 surrender guides
     unsigned int dealerHandScore = table.getDealer()->getHandScore();
     unsigned int personalScore = getHandScore();
     if (personalScore == 14 && dealerHandScore == 10 && currentCount >= 3) {
         return true;
     }
     else if (personalScore == 15 && dealerHandScore == 10 && currentCount >= 0) {
         return true;
     }
     else if (personalScore == 15 && dealerHandScore == 9 && currentCount >= 2) {
         return true;
     }
     else if (personalScore == 15 && dealerHandScore == 11 && currentCount >= 1) {
         return true;
     }
     return false;
 }
takeInsurance()
bool Bot1::takeInsurance (Table & table) virtual
Take insurance if current count >= 3;.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
True if it takes insurance, false if it does not.
Reimplemented from Player.
Definition at line 378 of file Player.cpp.
{
     unsigned int insurance = getActualBet() / 2;
     if (currentCount >= 3) {
         setCurrentMoney(getCurrentMoney() - insurance);
         return true;
     }
     return false;;
 }
Member Data Documentation
currentCount
int Bot1::currentCount private
The current count.
Definition at line 959 of file Player.h.
The documentation for this class was generated from the following files:
Player.h
Player.cpp