Aeda-Casino: Human Class Reference
Human Class Reference
A Human player.
#include <Player.h>
Public Member Functions
Human (string name, unsigned int age, int userID)
Constructor.
Human (string &line)
Constructor.
unsigned int bet (Table &table)
Asks the human player to place his bet.
string play (Table &table)
Ask the human player to hit or stand.
bool takeInsurance (Table &table)
Ask the human player for insurance.
bool split (Dealer *dealerOfTable)
Ask human if he want to split his hand.
void setUserID (unsigned int userID)
Sets user identifier.
unsigned int getUserID () const
Gets user identifier.
virtual ostream & saveInfo (ostream &out)
Writes Human info to stream.
Public Member Functions inherited from Player
void hit (Card newCard)
Hits the given new card. Saves the card on the hand. Updates the handscore.
void hit2 (Card newCard)
Hits the given new card. Saves the card on the hand2. Updates the hand2score.
virtual bool surrender (Table &table)
Surrenders or not. When this method is called, it will check if the player wants to surrender.
void doubleDown ()
Double down. Doubles down the current bet. When a player doubles down, he will hit a new card, double is bet, and won't be allowed to play anymore until the end of the round.
vector< Card > & getHand ()
Gets the hand.
vector< Card > & getHand2 ()
Gets the second hand.
unsigned int getHandSize () const
Gets hand size.
unsigned int getRoundsPlayed () const
Gets rounds played.
float getCurrentMoney () const
Gets current money.
float getAverageProfit () const
Gets average profit.
unsigned int getHandScore () const
Gets hand score.
unsigned int getHand2Score () const
Gets second hand score.
unsigned int getInitialMoney () const
Gets initial money.
string getName () const
Gets the name.
void setAverageProfit (float averageProfit)
Sets the average profit of the player.
void setName (string newName)
Sets a name.
unsigned int setHandScore ()
Sets hand score.
unsigned int setHand2Score ()
Sets second hand score.
void setCurrentMoney (float money)
Sets current money.
void setRoundsPlayed (unsigned int rounds)
Sets rounds played.
void setInitialMoney (unsigned int money)
Sets initial money.
void addMoney (float value)
Adds money to the player.
void showStatistics ()
Shows the statistics.
void clearHand ()
Clears the hand.
void clearHand2 ()
Clears the second hand.
void setActualBet (unsigned int bet)
Sets actual bet.
unsigned int getActualBet ()
Gets actual bet.
virtual int getCurrentCount () const
Gets current count. Different kinds of players may hold different counts.
virtual void addCount (Card &card1)
Updates the current count with a given card.
virtual void resetCount ()
Resets the current count. Should be called when the deck is reshuffled or the table closes.
unsigned int getAge () const
Gets the age.
void setAge (unsigned int age)
Sets an age.
void setOnTable (int tableID)
Sits on a table. -1 if the player is not on any table.
int getOnTable () const
Gets if the player is on table or not.
void removeCardFromFirstHandAndSetItOnSecondHand ()
Removes the card from first hand sets it on the second hand.
Private Attributes
unsigned int userID
User identifier.
string username
The username.
Detailed Description
A Human player.
Author
Joao Carvalho
Date
19/11/2016
Definition at line 1313 of file Player.h.
Constructor & Destructor Documentation
Human() [1/2]
Human::Human (string name, unsigned int age, int userID)
Constructor.
Author
Joao Carvalho
Date
19/11/2016
Parameters
name The name.
age The age.
userID The user identifier.
Definition at line 902 of file Player.cpp.
References NameTooShortException::what(), and TooYoungException::what().
 {
     try {
         if (name.length() < 3) {
             throw NameTooShortException();
         }
         setName(name);
         if (age < 18) {
             throw TooYoungException();
         }
         this->setAge(age);
         setInitialMoney(1000);
         this->setOnTable(-1);
         this->userID = userID;
     }
     catch (NameTooShortException &n) {
         n.what();
     }
     catch (TooYoungException &y) {
         y.what();
     }
 }
Human() [2/2]
Human::Human (string & line)
Constructor.
Author
Joao Carvalho
Date
19/11/2016
Parameters
line Line that contains all information.
Definition at line 925 of file Player.cpp.
References Card::rank, Card::score, and Card::suits.
{
     line.erase(0, line.find_first_of(";") + 2);
     this->setName(line.substr(0, line.find_first_of(";")));
     line.erase(0, line.find_first_of(";") + 2);
     this->setInitialMoney(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setCurrentMoney(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->clearHand();
     if (line.at(0) == '{')
     {
         line.erase(0, 1);
         Card newCard;
         while (line.at(0) != '}')
         {
             newCard.rank = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.suits = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.score = stoi(line.substr(0, line.find_first_of(";")));
             line.erase(0, line.find_first_of(";") + 2);
             this->hit(newCard);
         }
         line.erase(0, line.find_first_of(";") + 2);
     }
     this->clearHand2();
     if (line.at(0) == '{')
     {
         line.erase(0, 1);
         Card newCard;
         while (line.at(0) != '}')
         {
             newCard.rank = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.suits = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.score = stoi(line.substr(0, line.find_first_of(";")));
             line.erase(0, line.find_first_of(";") + 2);
             this->hit2(newCard);
         }
         line.erase(0, line.find_first_of(";") + 2);
     }
     this->setRoundsPlayed(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setAge(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setOnTable(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->setActualBet(stoi(line.substr(0, line.find_first_of(";"))));
     line.erase(0, line.find_first_of(";") + 2);
     this->userID = stoi(line.substr(0, line.find_first_of(";")));
     line.erase(0, line.find_first_of(";") + 2);
 }
Member Function Documentation
bet()
unsigned int Human::bet (Table & table) virtual
Asks the human player to place his bet.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
The human bet.
Reimplemented from Player.
Definition at line 980 of file Player.cpp.
References Table::getMaxBet(), Table::getMinBet(), and readUnsignedIntBetween().
 {
     float maxbet = getCurrentMoney();
     if (maxbet < table.getMinBet()) {
         return 0; //0 means kick the player from the table;
     }
     unsigned int betValue;
     cout << "Your Turn " << getName() << "\n";
     if (maxbet > table.getMaxBet())
     {
         maxbet = table.getMaxBet();
     }
     betValue = readUnsignedIntBetween(table.getMinBet(), maxbet);
     this->setActualBet(betValue);
     this->setCurrentMoney(this->getCurrentMoney() - betValue);
     return betValue;
 }
getUserID()
unsigned int Human::getUserID () const virtual
Gets user identifier.
Author
Joao Carvalho
Date
19/11/2016
Returns
User identifier.
Reimplemented from Player.
Definition at line 891 of file Player.cpp.
Referenced by Table::play().
{
     return this->userID;
 }
play()
string Human::play (Table & table) virtual
Ask the human player to hit or stand.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
A string: "hit" or "stand";
Implements Player.
Definition at line 998 of file Player.cpp.
References Dealer::discard(), Table::getDealer(), getHumanPlay(), and Table::getPlayers().
 {
     if (getHandScore() >= 21)
     {
         return "stand";
     }
     string option;
     cout << "Your Turn -> In your hand you have the following:\n";
     for (size_t i = 0; i < getHandSize(); i++)
     {
         cout << getHand().at(i).rank << " of " << getHand().at(i).suits << "\n";
     }
     cout << "Current hand score-> " << getHandScore() << "\n";
     cout << "Current money-> " << getCurrentMoney() << "\n";
     cout << "To hit write 'hit' to stand write 'stand' : ";
     option = getHumanPlay();
     if (option == "hit")
     {
         hit(table.getDealer()->discard(table.getPlayers()));
     }
     return option;
 }
saveInfo()
ostream & Human::saveInfo (ostream & out) virtual
Writes Human info to stream.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] out ostream in which Human info will be saved.
Returns
Human info in a ostream.
Reimplemented from Player.
Definition at line 895 of file Player.cpp.
References Player::saveInfo().
{
     out << "3; ";
     Player::saveInfo(out);
     out << userID << "; ";
     return out;
 }
setUserID()
void Human::setUserID (unsigned int userID) virtual
Sets user identifier.
Author
Joao Carvalho
Date
19/11/2016
Parameters
userID New user identifier.
Reimplemented from Player.
Definition at line 887 of file Player.cpp.
{
     this->userID = userID;
 }
split()
bool Human::split (Dealer * dealerOfTable) virtual
Ask human if he want to split his hand.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] dealerOfTable Pointer to the dealer of the table.
Returns
True if human splits, false otherwise.
Reimplemented from Player.
Definition at line 870 of file Player.cpp.
References readBinary().
{
     unsigned int split;
     vector<Card> hand = getHand();
     if (hand.at(0) == hand.at(1)) {
         cout << "Do you want split?\n 0 - No    1 - Yes\n";
         split = readBinary();
         vector<Card> hand = getHand();
         if (split == 1) {
             removeCardFromFirstHandAndSetItOnSecondHand();
             return true;
         }
     }
     return false;
 }
takeInsurance()
bool Human::takeInsurance (Table & table) virtual
Ask the human player for insurance.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
True if human takes insurance, false if it does not.
Reimplemented from Player.
Definition at line 856 of file Player.cpp.
References readBinary().
{
     unsigned int insurance;
     cout << "Do you want insurance?\n 0 - No    1 - Yes\n";
     insurance=readBinary();
     if(insurance == 1){
         insurance = bet(table)/2;
         setCurrentMoney(getCurrentMoney() - insurance);
         return true;
     }
     return false;
 }
Member Data Documentation
userID
unsigned int Human::userID private
User identifier.
Definition at line 1316 of file Player.h.
username
string Human::username private
The username.
Definition at line 1318 of file Player.h.
The documentation for this class was generated from the following files:
Player.h
Player.cpp