Aeda-Casino: Dealer Class Reference
Dealer Class Reference
A dealer. The dealer is responsible to deal cards to the players and to himself. He is the one that holds that deck and reshufles it.
#include <Dealer.h>
Public Member Functions
Dealer ()
Default constructor. Creates a default deck of 52 cards.
Dealer (unsigned int ID)
Constructor. Creates a default deck of 52 cards.
Dealer (vector< Card > newDeck)
Constructor.
void shuffleDeck ()
Shuffle deck.
Card discard (vector< Player *> players)
Removes a Card from the end of the deck and returns it. Additionaly pushes the Card to the deckDiscarded vector.
Card & hit (vector< Player *> players)
Places a Card in the Dealer hand and updates the handscore.
unsigned int setHandScore ()
Updates dealer's handscore.
vector< Card > & getDeck ()
Gets the deck.
vector< Card > & getHand ()
Gets the hand.
void addCardsToDeck (vector< Card > &cards)
Adds cards to the deck.
vector< Card > & getDiscardedDeck ()
Gets discarded deck.
unsigned int getHandScore () const
Gets handscore.
void clearDiscardedDeck ()
Clears the discarded deck.
void clearHand ()
Clears the hand.
bool hasCardInHand (Card &c)
Query if dealer has card in hand.
string play (Table &table)
Calculates dealer next move. Dealer will stand if handscore >= 17.
unsigned int getID () const
Gets the Dealer's identifier.
void setTable (int tableID)
Associates a table to this dealer.
int getTableOn () const
Gets identifier of the table that the dealer is on.
Static Public Member Functions
static void setNextID (unsigned int ID)
Sets next identifier.
static unsigned int getNextID ()
Gets the next identifier.
Private Attributes
unsigned int ID
The identifier.
vector< Card > hand
The hand.
unsigned int handScore
The hand score.
unsigned int nextPlayer
The next player.(Deprecated)
vector< Card > deck
The deck.
vector< Card > deckDiscarded
The discarded deck.
int TableID
Identifier for the table that the dealer is on.
Static Private Attributes
static unsigned int nextID = 0
Identifier for the next Dealer.
Detailed Description
A dealer. The dealer is responsible to deal cards to the players and to himself. He is the one that holds that deck and reshufles it.
Author
M. Francisca Pauperio
Date
19/11/2016
Definition at line 30 of file Dealer.h.
Constructor & Destructor Documentation
Dealer() [1/3]
Dealer::Dealer ()
Default constructor. Creates a default deck of 52 cards.
Author
M. Francisca Pauperio
Date
19/11/2016
Definition at line 8 of file Dealer.cpp.
References createDeck(), deck, ID, nextID, shuffleDeck(), and TableID.
 {
     deck = createDeck();
     shuffleDeck();
     TableID = -1;
     ID = nextID;
     nextID++;
 }
Dealer() [2/3]
Dealer::Dealer (unsigned int ID)
Constructor. Creates a default deck of 52 cards.
Author
M. Francisca Pauperio
Date
19/11/2016
Parameters
ID The identifier.
Definition at line 17 of file Dealer.cpp.
References createDeck(), deck, ID, shuffleDeck(), and TableID.
{
     deck = createDeck();
     shuffleDeck();
     TableID = -1;
     this->ID = ID;
 }
Dealer() [3/3]
Dealer::Dealer (vector< Card > newDeck)
Constructor.
Author
M. Francisca Pauperio
Date
19/11/2016
Parameters
newDeck The new deck.
Definition at line 24 of file Dealer.cpp.
References deck, ID, nextID, shuffleDeck(), and TableID.
{
     TableID = -1;
     this->deck = newDeck;
     shuffleDeck();
     ID = nextID;
     nextID++;
 }
Member Function Documentation
addCardsToDeck()
void Dealer::addCardsToDeck (vector< Card > & cards)
Adds cards to the deck.
Author
M. Francisca Pauperio
Date
19/11/2016
Parameters
[in,out] cards Vector of cards to be added to the deck.
Definition at line 84 of file Dealer.cpp.
References deck, and shuffleDeck().
 {
     deck.insert(deck.end(), cards.begin(), cards.end());
     shuffleDeck();
 }
clearDiscardedDeck()
void Dealer::clearDiscardedDeck ()
Clears the discarded deck.
Author
M. Francisca Pauperio
Date
19/11/2016
Definition at line 100 of file Dealer.cpp.
References deckDiscarded.
 {
     deckDiscarded.clear();
 }
clearHand()
void Dealer::clearHand ()
Clears the hand.
Author
M. Francisca Pauperio
Date
19/11/2016
Definition at line 105 of file Dealer.cpp.
References hand, and setHandScore().
 {
     hand.clear();
     this->setHandScore();
 }
discard()
Card Dealer::discard (vector< Player *> players)
Removes a Card from the end of the deck and returns it. Additionaly pushes the Card to the deckDiscarded vector.
Author
M. Francisca Pauperio
Date
19/11/2016
Parameters
[in,out] players A vector of pointers to the players.
Returns
The discarded Card.
Definition at line 36 of file Dealer.cpp.
References deck, and deckDiscarded.
Referenced by hit(), Bot0::play(), Bot1::play(), Bot2::play(), and Human::play().
{
     Card nextCard;
     nextCard = deck.back();
     deckDiscarded.push_back(nextCard);
     deck.pop_back();
     for (size_t i = 0; i < players.size(); i++) {
         players.at(i)->addCount(nextCard);
     }
     return nextCard;
 }
getDeck()
vector< Card > & Dealer::getDeck ()
Gets the deck.
Author
M. Francisca Pauperio
Date
19/11/2016
Returns
The deck.
Definition at line 74 of file Dealer.cpp.
References deck.
 {
     return deck;
 }
getDiscardedDeck()
vector< Card > & Dealer::getDiscardedDeck ()
Gets discarded deck.
Author
M. Francisca Pauperio
Date
19/11/2016
Returns
The discarded deck.
Definition at line 90 of file Dealer.cpp.
References deckDiscarded.
 {
     return deckDiscarded;
 }
getHand()
vector< Card > & Dealer::getHand ()
Gets the hand.
Author
M. Francisca Pauperio
Date
19/11/2016
Returns
The hand.
Definition at line 79 of file Dealer.cpp.
References hand.
Referenced by Bot1::play(), and Bot1::split().
 {
     return hand;
 }
getHandScore()
unsigned int Dealer::getHandScore () const
Gets handscore.
Author
M. Francisca Pauperio
Date
19/11/2016
Returns
The handscore.
Definition at line 95 of file Dealer.cpp.
References handScore.
Referenced by Bot1::surrender(), and Bot2::surrender().
 {
     return handScore;
 }
getID()
unsigned int Dealer::getID () const
Gets the Dealer's identifier.
Author
M. Francisca Pauperio
Date
19/11/2016
Returns
The identifier.
Definition at line 131 of file Dealer.cpp.
References ID.
Referenced by Casino::addDealerToCasino(), DealerAlreadyExistException::DealerAlreadyExistException(), DealerIsOnTableAlreadyException::DealerIsOnTableAlreadyException(), DealerNotExistException::DealerNotExistException(), DealerStillOnTableException::DealerStillOnTableException(), dealersComparasion::operator()(), Casino::removeDealerFromCasino(), and sortFunctionDealers().
{
     return this->ID;
 }
getNextID()
static unsigned int Dealer::getNextID () static
Gets the next identifier.
Author
M. Francisca Pauperio
Date
19/11/2016
Returns
The next identifier.
Definition at line 147 of file Dealer.cpp.
References nextID.
Referenced by Casino::saveDealersFile().
{
     return nextID;
 }
getTableOn()
int Dealer::getTableOn () const
Gets identifier of the table that the dealer is on.
Author
M. Francisca Pauperio
Date
19/11/2016
Returns
The table that the dealer is on. -1 if Dealer is not on any table.
Definition at line 139 of file Dealer.cpp.
References TableID.
Referenced by Casino::create(), DealerStillOnTableException::DealerStillOnTableException(), dealersComparasion::operator()(), and sortFunctionDealers().
{
     return this->TableID;
 }
hasCardInHand()
bool Dealer::hasCardInHand (Card & c)
Query if dealer has card in hand.
Author
M. Francisca Pauperio
Date
19/11/2016
Parameters
[in,out] c The Card to process.
Returns
True if the card is in the dealer's hand, false if not.
Definition at line 111 of file Dealer.cpp.
References hand.
 {
     for (size_t i = 0; i < hand.size(); i++) {
         if (hand.at(i) == c) {
             return true;
         }
     }
     return false;
 }
hit()
Card & Dealer::hit (vector< Player *> players)
Places a Card in the Dealer hand and updates the handscore.
Author
M. Francisca Pauperio
Date
19/11/2016
Parameters
[in,out] players A vector of pointers to the players.
Returns
A reference to the dealer's new Card.
Definition at line 47 of file Dealer.cpp.
References discard(), hand, and setHandScore().
Referenced by play().
{
     hand.push_back(discard(players));
     setHandScore();
     return hand.back();
 }
play()
string Dealer::play (Table & table)
Calculates dealer next move. Dealer will stand if handscore >= 17.
Author
M. Francisca Pauperio
Date
19/11/2016
Parameters
[in,out] table The table that the dealer is on.
Returns
A string: "hit" or "stand"
Definition at line 122 of file Dealer.cpp.
References Table::getPlayers(), handScore, and hit().
 {
     if (handScore < 17) {
         hit(table.getPlayers());
         return "hit"; //means hit
     }
     else return "stand"; //means stand
 }
setHandScore()
unsigned int Dealer::setHandScore ()
Updates dealer's handscore.
Author
M. Francisca Pauperio
Date
19/11/2016
Returns
The updated handscore.
Definition at line 57 of file Dealer.cpp.
References hand, and handScore.
Referenced by clearHand(), and hit().
{
     this->handScore = 0;
     for (size_t i = 0; i < hand.size(); i++)
     {
         this->handScore += hand.at(i).score;
     }
     if (handScore > 21) {
         for (size_t i = 0; i < hand.size(); i++) {
             if (hand.at(i).score == 11 && handScore > 21) {
                 this->handScore -= 10;
             }
         }
     }
     return this->handScore;
 }
setNextID()
static void Dealer::setNextID (unsigned int ID) static
Sets next identifier.
Author
M. Francisca Pauperio
Date
19/11/2016
Parameters
ID The identifier.
Definition at line 143 of file Dealer.cpp.
References ID, and nextID.
Referenced by Casino::readDealersFile().
{
     nextID = ID;
 }
setTable()
void Dealer::setTable (int tableID)
Associates a table to this dealer.
Author
M. Francisca Pauperio
Date
19/11/2016
Parameters
tableID Identifier for the table.
Definition at line 135 of file Dealer.cpp.
References TableID.
Referenced by Table::setDealer().
{
     this->TableID = tableID;
 }
shuffleDeck()
void Dealer::shuffleDeck ()
Shuffle deck.
Author
M. Francisca Pauperio
Date
19/11/2016
Definition at line 32 of file Dealer.cpp.
References deck.
Referenced by addCardsToDeck(), and Dealer().
{
     random_shuffle(deck.begin(), deck.end());
 }
Member Data Documentation
deck
vector<Card> Dealer::deck private
The deck.
Definition at line 43 of file Dealer.h.
Referenced by addCardsToDeck(), Dealer(), discard(), getDeck(), and shuffleDeck().
deckDiscarded
vector<Card> Dealer::deckDiscarded private
The discarded deck.
Definition at line 45 of file Dealer.h.
Referenced by clearDiscardedDeck(), discard(), and getDiscardedDeck().
hand
vector<Card> Dealer::hand private
The hand.
Definition at line 37 of file Dealer.h.
Referenced by clearHand(), getHand(), hasCardInHand(), hit(), and setHandScore().
handScore
unsigned int Dealer::handScore private
The hand score.
Definition at line 39 of file Dealer.h.
Referenced by getHandScore(), play(), and setHandScore().
ID
unsigned int Dealer::ID private
The identifier.
Definition at line 35 of file Dealer.h.
Referenced by Dealer(), getID(), and setNextID().
nextID
unsigned int Dealer::nextID = 0 static private
Identifier for the next Dealer.
Definition at line 33 of file Dealer.h.
Referenced by Dealer(), getNextID(), and setNextID().
nextPlayer
unsigned int Dealer::nextPlayer private
The next player.(Deprecated)
Definition at line 41 of file Dealer.h.
TableID
int Dealer::TableID private
Identifier for the table that the dealer is on.
Definition at line 47 of file Dealer.h.
Referenced by Dealer(), getTableOn(), and setTable().
The documentation for this class was generated from the following files:
Dealer.h
Dealer.cpp