Aeda-Casino: PlayerStillOnTableException Class Reference
PlayerStillOnTableException Class Reference
Exception for signalling that the player is still on table.
#include <Player.h>
Public Member Functions
PlayerStillOnTableException (Player *player)
Constructor.
unsigned int getTableId () const
Gets table identifier.
Private Attributes
string name
The name.
unsigned int tableID
Identifier for the table.
Detailed Description
Exception for signalling that the player is still on table.
Author
Joao Carvalho
Date
19/11/2016
Definition at line 142 of file Player.h.
Constructor & Destructor Documentation
PlayerStillOnTableException()
PlayerStillOnTableException::PlayerStillOnTableException (Player * player)
Constructor.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] player Pointer to the player.
Definition at line 1029 of file Player.cpp.
References Player::getName(), and Player::getOnTable().
{
     this->name = player->getName();
     this->tableID = player->getOnTable();
 }
Member Function Documentation
getTableId()
unsigned int PlayerStillOnTableException::getTableId () const
Gets table identifier.
Author
Joao Carvalho
Date
19/11/2016
Returns
The table identifier.
Definition at line 1034 of file Player.cpp.
Referenced by Casino::eliminate().
{
     return this->tableID;
 }
Member Data Documentation
name
string PlayerStillOnTableException::name private
The name.
Definition at line 145 of file Player.h.
tableID
unsigned int PlayerStillOnTableException::tableID private
Identifier for the table.
Definition at line 147 of file Player.h.
The documentation for this class was generated from the following files:
Player.h
Player.cpp