Aeda-Casino: Table Class Reference
Table Class Reference
A Casino's table.
#include <Table.h>
Public Member Functions
Table (int ID)
Constructor.
Table (unsigned int, unsigned int, unsigned int, unsigned int, Dealer *)
Constructor.
~Table ()
Destructor.
void setMinBet (unsigned int minBet)
Sets minimum bet.
void setMaxBet (unsigned int maxBet)
Sets maximum bet.
void setDealer (Dealer *dealerOfTable)
Sets a dealer.
void setID (int ID)
Sets an identifier.
void addPlayer (Player *newPlayer)
Adds a player to this table.
void addPlayers (vector< Player *> newPlayers)
Adds the players to this table.
void removePlayer (string &name)
Removes the player described by his name.
void play (pair< short, short > xy, unsigned int userID, string userName)
Plays Blackjack allowing humans to play against bots and other humans too.
void simulation (unsigned int roundsLeft)
Simulates a blackjack game for the given rounds.
unsigned int getInitialMoney () const
Gets initial money of this table.
int getTableID () const
Gets table identifier.
unsigned int getMinBet () const
Gets minimum bet.
unsigned int getMaxBet () const
Gets maximum bet.
unsigned int getNumberMaxOfPlayers () const
Gets maximum number of players.
void getInitialBets ()
Ask players for their initial bets.
Dealer * getDealer ()
Gets the dealer.
vector< Player * > getPlayers () const
Gets the players.
void dealOneCardToAllPlayers ()
Deal one card to all players.
void payToPlayer (Player *player1, float value)
Pay to player a given amount.
unsigned int restartDeck ()
Restart deck.
void showTableInfo (pair< short, short > xy)
Shows the table information.
void kickPlayer (unsigned int index)
Kicks a player.
void resetBot1Counters ()
Resets All bots of type 1 counters.
void addMoneyToTable (unsigned int money)
Adds money to this table.
float closeTable ()
Closes the table. Resets all bot counters.
void readTableFile ()
Reads the table file.
void writeTableFile ()
Writes the table file.
void showPlay (pair< short, short > xy)
Plays and Displays in terminal the blackjack game.
Static Public Member Functions
static void setNextID (unsigned int tableNextID)
Sets next identifier.
static unsigned int getNextId ()
Gets the next identifier of the tables.
Private Attributes
unsigned int minBet
The minimum bet.
unsigned int maxBet
The maximum bet.
unsigned int initialMoney
The initial money.
float moneyOfTable
The money of the table.
unsigned int maxNumberOfPlayers
The maximum number of players.
int tableID
Identifier for the table.
Dealer * dealerOfTable
The dealer of table.
vector< Player * > players
The players.
vector< Player * > actualPlayers
The actual players.
unsigned int nextPlayerIndex
unsigned int bossUserID
unsigned int phaseOfPlaying
Static Private Attributes
static unsigned int nextID = 0
Identifier of the next table.
Detailed Description
A Casino's table.
Author
Renato Campos
Date
18/11/2016
Definition at line 117 of file Table.h.
Constructor & Destructor Documentation
Table() [1/2]
Table::Table (int ID)
Constructor.
Author
Renato Campos
Date
18/11/2016
Parameters
ID The identifier.
Definition at line 15 of file Table.cpp.
                    {
     this->tableID = ID;
 }
Table() [2/2]
Table::Table (unsigned int minBet, unsigned int maxBet, unsigned int moneyOfTable, unsigned int numberOfMaxPlayers, Dealer * newDealer)
Constructor.
Author
Renato Campos
Date
18/11/2016
Parameters
minBet The minimum bet.
maxBet The maximum bet.
moneyOfTable Initial money of the table.
numberOfMaxPlayers The maximum number of players allowed to join the table.
[in,out] newDealer Pointer to the Dealer to be assigned to this table.
Definition at line 19 of file Table.cpp.
References TooManyPlayersException::maxNumberOfPlayers.
{
     this->minBet = minBet;
     this->maxBet = maxBet;
     this->moneyOfTable = moneyOfTable;
     this->maxNumberOfPlayers = numberOfMaxPlayers;
     this->dealerOfTable = newDealer;
     this->nextPlayerIndex = 0;
     this->phaseOfPlaying = 0;
     initialMoney = moneyOfTable;
     tableID = nextID;
     nextID++;
 }
~Table()
Table::~Table ()
Destructor.
Author
Renato Campos
Date
18/11/2016
Definition at line 32 of file Table.cpp.
               {
     this->closeTable();
     for (size_t i = 0; i < players.size(); i++)
     {
         players.at(i)->setOnTable(-1);
     }
     dealerOfTable->setTable(-1);
 }
Member Function Documentation
addMoneyToTable()
void Table::addMoneyToTable (unsigned int money)
Adds money to this table.
Author
Renato Campos
Date
18/11/2016
Parameters
money The amount of money to be added.
Definition at line 648 of file Table.cpp.
Referenced by Bot1::play().
 {
     moneyOfTable += money;
 }
addPlayer()
void Table::addPlayer (Player * newPlayer)
Adds a player to this table.
Author
Renato Campos
Date
18/11/2016
Parameters
[in,out] newPlayer Pointer to the new player.
Definition at line 56 of file Table.cpp.
References Player::setOnTable().
Referenced by Casino::addPlayerToTable(), and Casino::readTablesFile().
{
     this->players.push_back(newPlayer);
     newPlayer->setOnTable(this->getTableID());
 }
addPlayers()
void Table::addPlayers (vector< Player *> newPlayers)
Adds the players to this table.
Author
Renato Campos
Date
18/11/2016
Parameters
[in,out] newPlayers Vector of pointers to the new players.
Definition at line 61 of file Table.cpp.
References TooManyPlayersException::maxNumberOfPlayers, and TooManyPlayersException::TooManyPlayersException().
{
     if (newPlayers.size() + players.size() > maxNumberOfPlayers) {
         throw TooManyPlayersException (maxNumberOfPlayers,players.size());
     }
     players.insert(players.end(), newPlayers.begin(), newPlayers.end());
     for (size_t i = 0; i < newPlayers.size(); i++)
     {
         newPlayers.at(i)->setOnTable(this->getTableID());
     }
 }
closeTable()
float Table::closeTable ()
Closes the table. Resets all bot counters.
Author
Renato Campos
Date
18/11/2016
Returns
moneyOfTable The final money of the table that should be added to the casino.
Definition at line 661 of file Table.cpp.
 {
     players = actualPlayers;
     for (size_t i = 0; i < players.size(); i++) {
         players.at(i)->resetCount();
     }
     //update averageProfits
     for (auto i = players.begin(); i != players.end(); i++) {
         float avgProfit = ((float)(*i)->getCurrentMoney() - (*i)->getInitialMoney()) /  (*i)->getRoundsPlayed();
         (*i)->setAverageProfit(avgProfit);
     }
     cout << "Table ID." << tableID << " has been CLOSED\n";
     cout << "Profit of table " << tableID << " : " << setprecision(2) <<moneyOfTable - initialMoney << "$\n";
     return moneyOfTable;
 }
dealOneCardToAllPlayers()
void Table::dealOneCardToAllPlayers ()
Deal one card to all players.
Author
Renato Campos
Date
18/11/2016
Definition at line 550 of file Table.cpp.
{
     for (size_t i = 0; i < actualPlayers.size(); i++) {
         Card discarded = dealerOfTable->discard(players);
         actualPlayers.at(i)->hit(discarded);
     }
 }
getDealer()
Dealer * Table::getDealer ()
Gets the dealer.
Author
Renato Campos
Date
18/11/2016
Returns
A pointer to the dealer.
Definition at line 540 of file Table.cpp.
Referenced by Bot0::play(), Bot1::play(), Bot2::play(), Human::play(), Bot1::surrender(), and Bot2::surrender().
 {
     return dealerOfTable;
 }
getInitialBets()
void Table::getInitialBets ()
Ask players for their initial bets.
Author
Renato Campos
Date
18/11/2016
Definition at line 525 of file Table.cpp.
 {
     unsigned int actualBet;
     for (size_t i = 0; i < players.size(); i++) {
         actualBet = players.at(i)->bet(*this);
         if (actualBet == 0) { //kick the player
             cout << players.at(i)->getName() << " we enjoyed your money ! Come back when you have some more...\n";
             kickPlayer(i);
             cout << players.at(i)->getName() << " has been kicked from table " << tableID << ".\n";
             i--;
         }
         moneyOfTable += actualBet;
     }
 }
getInitialMoney()
unsigned int Table::getInitialMoney () const
Gets initial money of this table.
Author
Renato Campos
Date
18/11/2016
Returns
The initial money.
Definition at line 515 of file Table.cpp.
Referenced by Casino::addTableToCasino().
 {
     return initialMoney;
 }
getMaxBet()
unsigned int Table::getMaxBet () const
Gets maximum bet.
Author
Renato Campos
Date
18/11/2016
Returns
The maximum bet.
Definition at line 379 of file Table.cpp.
Referenced by Bot1::bet(), Bot2::bet(), and Human::bet().
 {
     return maxBet;
 }
getMinBet()
unsigned int Table::getMinBet () const
Gets minimum bet.
Author
Renato Campos
Date
18/11/2016
Returns
The minimum bet.
Definition at line 374 of file Table.cpp.
Referenced by Player::bet(), Bot1::bet(), Bot2::bet(), and Human::bet().
 {
     return minBet;
 }
getNextId()
static unsigned int Table::getNextId () static
Gets the next identifier of the tables.
Author
Renato Campos
Date
18/11/2016
Returns
The next identifier.
Definition at line 682 of file Table.cpp.
Referenced by Casino::saveTablesFile().
{
     return nextID;
 }
getNumberMaxOfPlayers()
unsigned int Table::getNumberMaxOfPlayers () const
Gets maximum number of players.
Author
Renato Campos
Date
18/11/2016
Returns
The maximum number of players.
Definition at line 384 of file Table.cpp.
References TooManyPlayersException::maxNumberOfPlayers.
{
     return this->maxNumberOfPlayers;
 }
getPlayers()
vector< Player * > Table::getPlayers () const
Gets the players.
Author
Renato Campos
Date
18/11/2016
Returns
A vector of pointers to the players in the table.
Definition at line 545 of file Table.cpp.
Referenced by Casino::manageTables(), Dealer::play(), Bot0::play(), Bot1::play(), Bot2::play(), and Human::play().
 {
     return players;
 }
getTableID()
int Table::getTableID () const
Gets table identifier.
Author
Renato Campos
Date
18/11/2016
Returns
The table identifier.
Definition at line 520 of file Table.cpp.
Referenced by ExistingTableException::ExistingTableException(), NoPlayersOnTableException::NoPlayersOnTableException(), Casino::removeTableFromCasino(), sortFunctionTables(), and TableNotInCasinoException::TableNotInCasinoException().
 {
     return tableID;
 }
kickPlayer()
void Table::kickPlayer (unsigned int index)
Kicks a player.
Author
Renato Campos
Date
18/11/2016
Parameters
index Zero-based index of the player to kick.
Definition at line 634 of file Table.cpp.
 {
     players.at(index)->setOnTable(-1);
     players.erase(players.begin() + index);
     actualPlayers.erase(actualPlayers.begin() + index);
 }
payToPlayer()
void Table::payToPlayer (Player * player1, float value)
Pay to player a given amount.
Author
Renato Campos
Date
18/11/2016
Parameters
[in,out] player1 A pointer to a player.
value The value to pay to the player.
Definition at line 653 of file Table.cpp.
References Player::addMoney().
 {
     player1->addMoney(value);
     moneyOfTable -= value;
 }
play()
void Table::play (pair< short, short > xy, unsigned int userID, string userName)
Plays Blackjack allowing humans to play against bots and other humans too.
Author
Renato Campos
Date
18/11/2016
Definition at line 85 of file Table.cpp.
References cursorxy(), FileExist(), Human::getUserID(), TooManyPlayersException::maxNumberOfPlayers, readCharYorN(), readUnsignedIntBetween(), TooManyPlayersException::TooManyPlayersException(), and waitXTime().
Referenced by main().
{
     system("cls");
     stringstream sstream;
     string tableFILE;
     bool dealerBlackJack = false;
     if (this->maxNumberOfPlayers == this->getPlayers().size())
     {
         throw TooManyPlayersException(maxNumberOfPlayers, maxNumberOfPlayers + 1);
     }
     //create human player
     unsigned int ageOfPlayer;
     cout << "What is your age?" << endl;
     ageOfPlayer = readUnsignedIntBetween(0, 100);
     if (ageOfPlayer < 18)
     {
         throw TooYoungException();
     }
     Human *humanPlayer = new Human(userName, ageOfPlayer, userID);
     //verify if file exist, if not create a file for table
     sstream << this->tableID;
     sstream >> tableFILE;
     tableFILE.insert(0, "table");
     tableFILE += "_temp.txt";
     if (FileExist(tableFILE))
     {
         this->readTableFile();
         while (phaseOfPlaying != 0)
         {
             waitXTime(1);
             this->readTableFile();
             this->showPlay(xy);
             cout << "Waiting end of round";
         }
     }
     else
     {
         bossUserID = userID;
     }
     this->addPlayer(humanPlayer);
     this->writeTableFile();
     //realplay
     system("cls");
     bool exit = false;
     while (!exit)
     {
         this->readTableFile();
         while (bossUserID != userID)
         {
             waitXTime(1);
             this->readTableFile();
             this->showPlay(xy);
             cout << "Waiting for other players...";
             cursorxy(0, 23);
         }
         if (nextPlayerIndex == 0 && phaseOfPlaying == 0)
         {
             //TODO: prepare round to play
             actualPlayers.clear();
             for (size_t i = 0; i < players.size(); i++)
             {
                 if (players.at(i)->getCurrentMoney() >= minBet)
                 {
                     actualPlayers.push_back(players.at(i));
                 }
                 else if (players.at(i)->getUserID() == userID)
                 {
                     cout << "The" << players.at(i)->getName() << "don't have money to play" << endl;
                     waitXTime(2);
                     exit = true;
                 }
             }
             phaseOfPlaying = 1;
             this->writeTableFile();
             this->showPlay(xy);
         }
         if ((nextPlayerIndex == 0 && phaseOfPlaying == 2) && !exit)
         {
             restartDeck();
             dealOneCardToAllPlayers();
             restartDeck();
             dealerOfTable->hit(players);
             dealOneCardToAllPlayers();
             restartDeck();
             phaseOfPlaying = 3;
             this->writeTableFile();
             this->showPlay(xy);
         }
         //TODO:implement take insurance
         if ((phaseOfPlaying == 1 || phaseOfPlaying == 3) && !exit)
         {
             for (size_t i = nextPlayerIndex; i < actualPlayers.size(); i++)
             {
                 Human *h = dynamic_cast<Human *>(actualPlayers.at(i));
                 if (h != NULL)
                 {
                     if (actualPlayers.at(i)->getUserID() != userID)
                     {
                         bossUserID = actualPlayers.at(i)->getUserID();
                         this->writeTableFile();
                         while (bossUserID != userID && phaseOfPlaying != 4)
{
                             waitXTime(1);
                             this->readTableFile();
                             this->showPlay(xy);
                             cout << "Waiting for other players...";
                             cursorxy(0, 23);
                         }
                     }
                     else
                     {
                         if (phaseOfPlaying == 1)
{
                             unsigned int betValue;
                             betValue = actualPlayers.at(i)->bet(*this);
                             this->readTableFile();
                             actualPlayers.at(i)->setCurrentMoney(actualPlayers.at(i)->getCurrentMoney() - betValue);
                             actualPlayers.at(i)->setActualBet(betValue);
                             //TODO: change for playerID after
                             nextPlayerIndex = i + 1;
                             this->writeTableFile();
                             this->showPlay(xy);
                         }
                         else
{
                             while (actualPlayers.at(i)->getHandScore() < 21 && actualPlayers.at(i)->play(*this) != "stand")
{
                                 this->showPlay(xy);
                                 restartDeck();
                             }
                             cout << "You stand with: " << actualPlayers.at(i)->getHandScore() << endl;
                             //TODO: change for playerID after
                             nextPlayerIndex = i + 1;
                             this->writeTableFile();
                             waitXTime(2);
                         }
                     }
                 }
                 else
                 {
                     if (phaseOfPlaying == 1)
                     {
                         unsigned int betValue;
                         betValue = actualPlayers.at(i)->bet(*this);
                         if (betValue == 0)
{
                             actualPlayers.erase(actualPlayers.begin() + i);
                         }
                         //TODO: change for playerID after
                         nextPlayerIndex = i + 1;
                         this->writeTableFile();
                         waitXTime(1);
                         this->showPlay(xy);
                     }
                     else
                     {
                         while (actualPlayers.at(i)->getHandScore() < 21 && actualPlayers.at(i)->play(*this) != "stand")
{
                             waitXTime(1);
                             this->showPlay(xy);
                             restartDeck();
                         }
                         //TODO: change for playerID after
                         nextPlayerIndex = i + 1;
                         this->writeTableFile();
                     }
                 }
             }
             if (nextPlayerIndex == actualPlayers.size() && phaseOfPlaying == 1)
             {
                 nextPlayerIndex = 0;
                 phaseOfPlaying = 2;
                 this->writeTableFile();
             }
             if ((nextPlayerIndex == actualPlayers.size() && phaseOfPlaying == 3) || phaseOfPlaying == 4)
             {
                 if (nextPlayerIndex == actualPlayers.size() && phaseOfPlaying == 3)
                 {
                     while (dealerOfTable->getHandScore() < 21 && dealerOfTable->play(*this) != "stand")
                     {
                         waitXTime(1);
                         this->showPlay(xy);
                         restartDeck();
                     }
                     nextPlayerIndex = 0;
                     phaseOfPlaying = 4;
                     this->writeTableFile();
                 }
                 unsigned int actualBet;
                 for (size_t j = nextPlayerIndex; j < actualPlayers.size(); j++)
                 {
                     actualBet = actualPlayers.at(j)->getActualBet();
                     if (actualPlayers.at(j)->getHandScore() == 21 && actualPlayers.at(j)->getHandSize() == 2 && dealerOfTable->getHandScore() < 21)
                     {
                         payToPlayer(actualPlayers.at(j), actualBet * 2.5);
                         cout << actualPlayers.at(j)->getName() << " won: " << actualBet * 2.5 << "$\n";
                     }
                     else if (actualPlayers.at(j)->getHandScore() <= 21 && actualPlayers.at(j)->getHandScore() == dealerOfTable->getHandScore())
                     {
                         payToPlayer(actualPlayers.at(j), actualBet);
                         cout << actualPlayers.at(j)->getName() << " won: " << actualBet << "$\n";
                     }
                     else if (actualPlayers.at(j)->getHandScore() > dealerOfTable->getHandScore() && actualPlayers.at(j)->getHandScore() <= 21)
                     {
                         payToPlayer(actualPlayers.at(j), actualBet * 2);
                         cout << actualPlayers.at(j)->getName() << " won: " << actualBet * 2 << "$\n";
                     }
                     else if (dealerOfTable->getHandScore() > 21 && actualPlayers.at(j)->getHandScore() <= 21)
                     {
                         payToPlayer(actualPlayers.at(j), actualBet * 2);
                         cout << actualPlayers.at(j)->getName() << " won: " << actualBet * 2 << "$\n";
                     }
                     else
                     {
                         cout << actualPlayers.at(j)->getName() << " lost!" << actualBet << "$\n";
                     }
                     if (phaseOfPlaying == 4)
                     {
                         actualPlayers.at(j)->clearHand();
                         actualPlayers.at(j)->clearHand2();
                         actualPlayers.at(j)->setActualBet(0);
                         actualPlayers.at(j)->setRoundsPlayed(actualPlayers.at(j)->getRoundsPlayed() + 1);
                         nextPlayerIndex = j + 1;
                         waitXTime(2);
                         this->showPlay(xy);
                     }
                 }
                 if (nextPlayerIndex == actualPlayers.size() && phaseOfPlaying == 4)
                 {
                     dealerOfTable->clearHand();
                     this->showPlay(xy);
                     phaseOfPlaying = 0;
                     nextPlayerIndex = 0;
                     for (size_t i = 0; i < actualPlayers.size(); i++)
                     {
                         players.at(i) = actualPlayers.at(i);
                     }
                     players = actualPlayers;
                     this->writeTableFile();
                 }
             }
             if (phaseOfPlaying == 0)
             {
                 cout << "Do you want play another round? (y/n)" << endl;
                 char option = readCharYorN();
                 if (option == 'n')
                 {
                     exit = true;
                 }
             }
         }
     }
     //sair da mesa
     this->readTableFile();
     bool HumanStillOnTable = false;
     for (size_t i = 0; i < players.size(); i++)
     {
         Human *h = dynamic_cast<Human *>(players.at(i));
         if (h != NULL)
         {
             if (players.at(i)->getUserID() == userID)
             {
                 delete humanPlayer;
                 players.erase(players.begin() + i);
                 i--;
             }
             else
             {
                 HumanStillOnTable = true;
                 bossUserID = players.at(i)->getUserID();
             }
         }
     }
     this->writeTableFile();
     if (!HumanStillOnTable)
     {
         remove(tableFILE.c_str());
     }
 }
readTableFile()
void Table::readTableFile ()
Reads the table file.
Author
Renato Campos
Date
18/11/2016
Definition at line 686 of file Table.cpp.
References waitXTime().
{
     stringstream sstream;
     string tableFILE, line;
     sstream << this->tableID;
     sstream >> tableFILE;
     tableFILE.insert(0, "table");
     tableFILE += "_temp.txt";
     ifstream inFile(tableFILE);
     for (int j = 0; j < 3; j++)
     {
         if (inFile.is_open())
         {
             getline(inFile, line);
             this->moneyOfTable = stoi(line);
             this->players.clear();
             getline(inFile, line);
             if (line == "{")
             {
                 while (line != "}")
                 {
                     getline(inFile, line);
                     if (line.substr(0,1) == "0")
                     {
                         Player *playerReaded = new Bot0(line);
                         players.push_back(playerReaded);
                     }
                     else if (line.substr(0, 1) == "1")
                     {
                         Player *playerReaded = new Bot1(line);
                         players.push_back(playerReaded);
                     }
                     else if (line.substr(0, 1) == "2")
                     {
                         Player *playerReaded = new Bot2(line);
                         players.push_back(playerReaded);
                     }
                     else if (line.substr(0, 1) == "3")
                     {
                         Player *playerReaded = new Human(line);
                         players.push_back(playerReaded);
                     }
                 }
             }
             this->actualPlayers.clear();
             getline(inFile, line);
             if (line == "{")
             {
                 while (line != "}")
                 {
                     getline(inFile, line);
                     if (line.substr(0, 1) == "0")
                     {
                         Player *playerReaded = new Bot0(line);
                         actualPlayers.push_back(playerReaded);
                     }
                     else if (line.substr(0, 1) == "1")
                     {
                         Player *playerReaded = new Bot1(line);
                         actualPlayers.push_back(playerReaded);
                     }
                     else if (line.substr(0, 1) == "2")
                     {
                         Player *playerReaded = new Bot2(line);
                         actualPlayers.push_back(playerReaded);
                     }
                     else if (line.substr(0, 1) == "3")
                     {
                         Player *playerReaded = new Human(line);
                         actualPlayers.push_back(playerReaded);
                     }
                 }
             }
             getline(inFile, line);
             this->nextPlayerIndex = stoi(line);
             getline(inFile, line);
             this->bossUserID = stoi(line);
             getline(inFile, line);
             this->phaseOfPlaying = stoi(line);
             inFile.close();
             return;
         }
         else
         {
             waitXTime(1);
         }
     }
     //TODO: throw exception
     cout << "Fail to read table file" << endl;
 }
removePlayer()
void Table::removePlayer (string & name)
Removes the player described by his name.
Author
Renato Campos
Date
18/11/2016
Parameters
[in] name The player's name.
Definition at line 72 of file Table.cpp.
Referenced by Casino::manageTables().
{
     for (size_t i = 0; i < players.size(); i++)
     {
         if (players.at(i)->getName() == name)
         {
             players.at(i)->setOnTable(-1);
             players.erase(players.begin() + i);
             return;
         }
     }
     throw PlayerIsntOnTableException(name);
 }
resetBot1Counters()
void Table::resetBot1Counters ()
Resets All bots of type 1 counters.
Author
Renato Campos
Date
18/11/2016
Definition at line 641 of file Table.cpp.
 {
     for (size_t i = 0; i < players.size(); i++) {
         players.at(i)->resetCount();
     }
 }
restartDeck()
unsigned int Table::restartDeck ()
Restart deck.
Author
Renato Campos
Date
18/11/2016
Returns
0 - deck restarted successfully; 1 - deck not ready to be restarted.
Definition at line 559 of file Table.cpp.
 {
     if (dealerOfTable->getDiscardedDeck().size() >= 3 * dealerOfTable->getDeck().size()) {
         dealerOfTable->addCardsToDeck(dealerOfTable->getDiscardedDeck()); //already shuffles the deck
         for (size_t i = 0; i < players.size(); i++) {
             players.at(i)->resetCount();
         }
         dealerOfTable->clearDiscardedDeck();
         return 0;
     }
     return 1;
 }
setDealer()
void Table::setDealer (Dealer * dealerOfTable)
Sets a dealer.
Author
Renato Campos
Date
18/11/2016
Parameters
[in,out] dealerOfTable Pointer to the dealer of table.
Definition at line 45 of file Table.cpp.
References Dealer::setTable().
{
     this->dealerOfTable->setTable(-1);
     this->dealerOfTable = dealerOfTable;
     dealerOfTable->setTable(tableID);
 }
setID()
void Table::setID (int ID)
Sets an identifier.
Author
Renato Campos
Date
18/11/2016
Parameters
ID The identifier.
Definition at line 51 of file Table.cpp.
Referenced by Casino::readTablesFile().
{
     this->tableID = ID;
 }
setMaxBet()
void Table::setMaxBet (unsigned int maxBet)
Sets maximum bet.
Author
Renato Campos
Date
18/11/2016
Parameters
maxBet The maximum bet.
Definition at line 41 of file Table.cpp.
{
     this->maxBet = aMaxBet;
 }
setMinBet()
void Table::setMinBet (unsigned int minBet)
Sets minimum bet.
Author
Renato Campos
Date
18/11/2016
Parameters
minBet The minimum bet.
Definition at line 370 of file Table.cpp.
{
     this->minBet = aMinBet;
 }
setNextID()
static void Table::setNextID (unsigned int tableNextID) static
Sets next identifier.
Author
Renato Campos
Date
18/11/2016
Parameters
tableNextID Identifier for the next table.
Definition at line 678 of file Table.cpp.
Referenced by Casino::readTablesFile().
{
     nextID = tableNextID;
 }
showPlay()
void Table::showPlay (pair< short, short > xy)
Plays and Displays in terminal the blackjack game.
Author
Renato Campos
Date
18/11/2016
Definition at line 818 of file Table.cpp.
References clearScreen(), cursorxy(), and TooManyPlayersException::maxNumberOfPlayers.
{
     //system("cls");
     string text = "TableID: ";
     cursorxy(6, 0);
     cout << text << this->getTableID() << endl;
     text = "Dealer  Score:";
     cursorxy((xy.first - text.length() - 6) / 2,1);
     cout << text << setw(3) << dealerOfTable->getHandScore() << endl;;
     cursorxy((xy.first - 72) / 2, 2);
     cout << (char)218;
     for (int i = 0; i < 70; i++)
     {
         cout << (char)196;
     }
     cout << (char)191 << endl;
     cursorxy((xy.first - 72) / 2, 3);
     cout << (char)179;
     for (int i = 0; i < 13; i++)
     {
         cursorxy((xy.first - 72) / 2, 3+i);
         cout << (char)179 << setw(71) << (char)179 << endl;
     }
     cursorxy((xy.first - 72) / 2, 16);
     cout << (char)192;
     for (int i = 0; i < 70; i++)
     {
         cout << (char)196;
     }
     cout << (char)217 << endl;
     //draw cards of dealer
     if (dealerOfTable->getHand().size() != 0)
     {
         cursorxy((xy.first - text.length()) / 2, 3);
         cout << (char)201 << (char)205;
         for (size_t i = 1; i < dealerOfTable->getHand().size(); i++)
         {
             cout << (char)201 << (char)205;
         }
         cout << (char)205 << (char)205 << (char)187;
         cursorxy((xy.first - text.length()) / 2, 4);
         cout << (char)186;
         if (dealerOfTable->getHand().at(0).rank == "10" && dealerOfTable->getHand().size() != 1)
         {
             cout << "1";
         }
         else if (dealerOfTable->getHand().at(0).rank != "10" && dealerOfTable->getHand().size() == 1)
         {
             cout << dealerOfTable->getHand().at(0).rank << " ";
         }
         else if (dealerOfTable->getHand().at(0).rank == "10" && dealerOfTable->getHand().size() == 1)
         {
             cout << "10";
         }
         else if (dealerOfTable->getHand().at(0).rank != "10" && dealerOfTable->getHand().size() != 1)
         {
             cout << dealerOfTable->getHand().at(0).rank;
         }
         for (size_t i = 1; i < dealerOfTable->getHand().size(); i++)
         {
             cout << (char)186;
             if (dealerOfTable->getHand().at(i).rank == "10" && i != dealerOfTable->getHand().size()-1)
             {
                 cout << "1";
             }
             else if (dealerOfTable->getHand().at(i).rank != "10" && i == dealerOfTable->getHand().size()-1)
             {
                 cout << dealerOfTable->getHand().at(i).rank << " ";
             }
             else
             {
                 cout << dealerOfTable->getHand().at(i).rank;
             }
         }
         if (dealerOfTable->getHand().back().suits == "Heart")
         {
             cout << (char)3;
         }
         else if (dealerOfTable->getHand().back().suits == "Diamond")
         {
             cout << (char)4;
         }
         else if (dealerOfTable->getHand().back().suits == "Club")
         {
             cout << (char)5;
         }
         else if (dealerOfTable->getHand().back().suits == "Spade")
         {
             cout << (char)6;
         }
         cout << (char)186;
         cursorxy((xy.first - text.length()) / 2, 5);
         cout << (char)200 << (char)205;
         for (size_t i = 1; i < dealerOfTable->getHand().size(); i++)
         {
             cout << (char)200 << (char)205;
         }
         cout << (char)205 << (char)205 << (char)188;
     }
     //draw players
     short x, y;
     string rank;
     for (size_t i = 0; i < maxNumberOfPlayers; i++)
     {
         //draw info about players
         if (i == 0)
         {
             x = (xy.first - 72) / 2 - 16;
             y = 8;
         }
         else if (i == 1)
         {
             x = (xy.first - 72) / 2 + 1;
             y = 17;
         }
         else if (i == 2)
         {
             x = (xy.first - 72) / 2 + 18;
             y = 17;
         }
         else if (i == 3)
         {
             x = (xy.first - 72) / 2 + 36;
             y = 17;
         }
         else if (i == 4)
         {
             x = (xy.first - 72) / 2 + 53;
             y = 17;
         }
         else if (i == 5)
         {
             x = (xy.first + 72) / 2 + 2;
             y = 8;
         }
         cursorxy(x, y);
         if (i < actualPlayers.size())
         {
             cout << "Name:" << setw(11) << actualPlayers.at(i)->getName();
             cursorxy(x, y + 1);
             cout << "Money:" << setw(10) << actualPlayers.at(i)->getCurrentMoney();
             cursorxy(x, y + 2);
             cout << "Bet:" << setw(12) << actualPlayers.at(i)->getActualBet();
             cursorxy(x, y + 3);
             cout << "Score:" << setw(10) << actualPlayers.at(i)->getHandScore();
         }
         else
         {
             cout << "Name:" << setw(11) << " ";
             cursorxy(x, y + 1);
             cout << "Money:" << setw(10) << " ";
             cursorxy(x, y + 2);
             cout << "Bet:" << setw(12) << " ";
             cursorxy(x, y + 3);
             cout << "Score:" << setw(10) << " ";
         }
         if (i < actualPlayers.size())
         {
             //draw cards
             if (i == 0)
             {
                 x = (xy.first - 72) / 2 + 1;
                 y = 8;
             }
             else if (i == 1)
             {
                 x = (xy.first - 72) / 2 + 1;
                 y = 13;
             }
             else if (i == 2)
             {
                 x = (xy.first - 72) / 2 + 18;
                 y = 13;
             }
             else if (i == 3)
             {
                 x = (xy.first - 72) / 2 + 36;
                 y = 13;
             }
             else if (i == 4)
             {
                 x = (xy.first - 72) / 2 + 53;
                 y = 13;
             }
             else if (i == 5)
             {
                 x = (xy.first - 72) / 2 + 53;
                 y = 8;
             }
             cursorxy(x, y);
             if (actualPlayers.at(i)->getHand().size() != 0)
             {
                 cout << (char)201 << (char)205;
                 for (size_t k = 1; k < actualPlayers.at(i)->getHand().size(); k++)
                 {
                     cout << (char)201 << (char)205;
                 }
                 cout << (char)205 << (char)205 << (char)187;
                 cursorxy(x, y + 1);
                 rank = actualPlayers.at(i)->getHand().at(0).rank;
                 if (rank == "10")
                 {
                     rank = "1";
                 }
                 cout << (char)186 << rank;
                 for (size_t j = 1; j < actualPlayers.at(i)->getHand().size(); j++)
                 {
                     rank = actualPlayers.at(i)->getHand().at(j).rank;
                     if (rank == "10" && j != actualPlayers.at(i)->getHand().size() - 1)
                     {
                         rank = "1";
                     }
                     else if (rank != "10" && j == actualPlayers.at(i)->getHand().size() - 1)
                     {
                         rank += " ";
                     }
                     cout << (char)186 << rank;
                 }
                 if (actualPlayers.at(i)->getHand().back().suits == "Heart")
                 {
                     cout << (char)3;
                 }
                 else if (actualPlayers.at(i)->getHand().back().suits == "Diamond")
                 {
                     cout << (char)4;
                 }
                 else if (actualPlayers.at(i)->getHand().back().suits == "Club")
                 {
                     cout << (char)5;
                 }
                 else if (actualPlayers.at(i)->getHand().back().suits == "Spade")
                 {
                     cout << (char)6;
                 }
                 cout << (char)186;
                 cursorxy(x, y + 2);
                 cout << (char)200 << (char)205;
                 for (size_t k = 1; k < actualPlayers.at(i)->getHand().size(); k++)
                 {
                     cout << (char)200 << (char)205;
                 }
                 cout << (char)205 << (char)205 << (char)188;
             }
         }
     }
     cursorxy(0, 23);
     string clearScreen(xy.first - 10, ' ');
     for (int i = 0; i < 9; i++)
     {
         cout << clearScreen << endl;
     }
     cursorxy(0, 23);
 }
showTableInfo()
void Table::showTableInfo (pair< short, short > xy)
Shows the table information.
Author
Renato Campos
Date
18/11/2016
Parameters
xy - the coordinates to set the cursor.
Definition at line 572 of file Table.cpp.
References cursorxy().
{
     string text;
     cursorxy(xy.first, xy.second);
     cout << (char)201; //
     for (unsigned int i = 0; i <= 28; i++)
     {
         cout << (char)205; //
     }
     cout << (char)187; //
     xy.second++;
     cursorxy(xy.first, xy.second);
     text = "  TableID: ";
     cout << (char)186 //
         << text << setw(30 - text.length()) << (char)186; //
     cursorxy(xy.first + text.length() + 1, xy.second);
     cout << this->getTableID();
     xy.second++;
     cursorxy(xy.first + 30, xy.second);
     cout << (char)186; //
     cursorxy(xy.first, xy.second);
     cout << (char)186; //
     cout << "  minBet:" << this->getMinBet();
     cursorxy(xy.first + 16, xy.second);
     cout << "maxBet:" << this->getMaxBet();
     xy.second++;
     cursorxy(xy.first, xy.second);
     cout << (char)204; //
     for (unsigned int i = 0; i <= 28; i++)
     {
         cout << (char)205; //
     }
     cout << (char)185 /**/;
     xy.second++;
     cursorxy(xy.first, xy.second);
     text = "  Players:";
     cout << (char)186  << text << setw(30 - text.length()) << (char)186;
     xy.second++;
     cursorxy(xy.first, xy.second);
     for (size_t i = 0; i < this->getPlayers().size(); i++)
     {
         text = this->getPlayers().at(i)->getName();
         cout << (char)186  << "   " << text << setw(30 - (3 + text.length())) << (char)186;
         xy.second++;
         cursorxy(xy.first, xy.second);
     }
     cout << (char)186 << setw(30) << (char)186;
     xy.second++;
     cursorxy(xy.first, xy.second);
     text = "  Money of Table: ";
     cout << (char)186 << text << setw(30 - text.length()) << (char)186;
     cursorxy(xy.first+ text.length()+1, xy.second);
     cout << this->getInitialMoney();
     xy.second++;
     cursorxy(xy.first, xy.second);
     cout << (char)200;
     for (unsigned int i = 0; i <= 28; i++)
     {
         cout << (char)205;
     }
     cout << (char)188;
 }
simulation()
void Table::simulation (unsigned int roundsLeft)
Simulates a blackjack game for the given rounds.
Author
Renato Campos
Date
18/11/2016
Parameters
roundsLeft The rounds to be played.
Definition at line 388 of file Table.cpp.
Referenced by main().
{
     //sequence : get Initial Bets then deal one card to each player and to the dealer (2x times) (first Dealer card face down)
     //if dealer's card is an Ace, ask players if they want to take insurance()
     //If they do, take each players insurance (it should be half of their original bet) and flip over dealer's second card to see whether or not dealer has a blackjack.
     //If dealer has a blackjack, collect bets from anyone that didnt buy insurance.Players that did buy insurance receive their original bets back.Players with blackjack will receive their original bet, even if they didnt purchase insurance.
     //Ask players with both cards equal if they want to split.
     bool dealerBlackJack = false;
     string lastOptionSelected;
     unsigned int actualBet;
     if (players.size() == 0)
     {
         throw NoPlayersOnTableException(new Table(this->getTableID()));
     }
     for (size_t i = 0; i < players.size(); i++)
     {
         Human *h = dynamic_cast<Human *>(players.at(i));
         if (h != NULL)
         {
             throw HumanOnTableException(players.at(i));
         }
     }
     while (roundsLeft > 0)
     {
         dealerBlackJack = false;
         cout << "Rounds left." << roundsLeft << "\n";
         actualPlayers = players;
         restartDeck();
         getInitialBets();
         dealOneCardToAllPlayers();
         restartDeck();
         dealerOfTable->hit(players);
         dealOneCardToAllPlayers();
         restartDeck();
         if (dealerOfTable->hit(players) == "A") {
             for(size_t i = 0; i < actualPlayers.size(); i++){
                 if(actualPlayers.at(i)->takeInsurance(*this)){
                     moneyOfTable += actualPlayers.at(i)->getActualBet() / 2;
                     if ((dealerOfTable->getHandScore() == 21) && (actualPlayers.at(i)->getHandScore() == 21)) {
                         dealerBlackJack = true;
                         payToPlayer(actualPlayers.at(i), actualPlayers.at(i)->getActualBet());
                         actualPlayers.erase(actualPlayers.begin(), actualPlayers.begin() + i); i--;
                     }
                 }
             }
         }
         if (dealerBlackJack == true) {
             actualPlayers.clear();
         }
         for (size_t i = 0; i < actualPlayers.size(); i++) {
             if (actualPlayers.at(i)->surrender(*this)) {
                 actualPlayers.at(i)->clearHand();
                 actualPlayers.at(i)->clearHand2();
                 actualPlayers.at(i)->setRoundsPlayed(players.at(i)->getRoundsPlayed() + 1);
                 actualPlayers.erase(actualPlayers.begin() + i);
                 i--;
             }
         }
         for(size_t j=0; j < actualPlayers.size(); j++) {
             actualPlayers.at(j)->split(dealerOfTable); //carefull, when splitting you have to bet again
         }
         for (size_t i = 0; i < actualPlayers.size(); i++) {
             do {
                 restartDeck();
                 if (lastOptionSelected == "double" || actualPlayers.at(i)->getHandScore() == 21) {
                     break; //break of do while
                 }
             }
                 while (lastOptionSelected == actualPlayers.at(i)->play(*this) && lastOptionSelected != "stand");
             cout << "Name: " << actualPlayers.at(i)->getName() << "; Money:" << actualPlayers.at(i)->getCurrentMoney() << "; Handscore: " << actualPlayers.at(i)->getHandScore() << "\n";
             cout << "In " << actualPlayers.at(i)->getName() << "'s hand: ";
             cout << actualPlayers.at(i)->getHand();
             cout << "\n";
         }
         if (dealerBlackJack == false) {
             do {
                 restartDeck();
                 cout << "Dealer handscore. " << dealerOfTable->getHandScore() << "\n";
                 if (dealerOfTable->getHandScore() >= 21) {
                     break;
                 }
             } while (dealerOfTable->play(*this) != "stand");
         }
         cout << "Dealer stands, with " << dealerOfTable->getHandScore() << " points. In his hand:\n";
         cout << dealerOfTable->getHand();
         actualPlayers = players;
         for (size_t i = 0; i < actualPlayers.size(); i++) {
             actualBet = actualPlayers.at(i)->getActualBet();
             if (actualPlayers.at(i)->getHandScore() > 21) {
                 //cout  << players.at(i)->getName() << " has " << players.at(i)->getHandScore() << " points, so he got busted!\n";
             }
             if (actualPlayers.at(i)->getHandScore() == 21 && actualPlayers.at(i)->getHandSize() == 2 && dealerOfTable->getHandScore() < 21) {
                 payToPlayer(actualPlayers.at(i), actualBet * 2.5);
                 //cout << players.at(i)->getName() << " has " << players.at(i)->getHandScore() << " so he did a blackjack!\n";
             }
             else if (actualPlayers.at(i)->getHandScore() <= 21 && actualPlayers.at(i)->getHandScore() == dealerOfTable->getHandScore() ) {
                 payToPlayer(actualPlayers.at(i), actualBet);
                 //cout << actualPlayers.at(i)->getName() << " has " << actualPlayers.at(i)->getHandScore() << " points, which is equal to the Dealer!\n";
             }
             else if (actualPlayers.at(i)->getHandScore() > dealerOfTable->getHandScore() && actualPlayers.at(i)->getHandScore() <= 21) {
                 payToPlayer(actualPlayers.at(i), actualBet * 2);
                 //cout << actualPlayers.at(i)->getName() << " has " << actualPlayers.at(i)->getHandScore() << " points, so he won the bet!\n";
             }
             else if (dealerOfTable->getHandScore() > 21 && actualPlayers.at(i)->getHandScore() <= 21) {
                 payToPlayer(actualPlayers.at(i), actualBet * 2);
                 //cout << "Dealer got busted! Player " << actualPlayers.at(i)->getName() << " will receive 2 times his original bet!\n";
             }
             else if (actualPlayers.at(i)->getHandScore() != 21 && dealerOfTable->getHandScore() == 21) {
                 //cout << "Dealer has blackjack! " << actualPlayers.at(i)->getName() << " lost his bet!\n";
             }
             actualPlayers.at(i)->clearHand();
             actualPlayers.at(i)->clearHand2();
             actualPlayers.at(i)->setRoundsPlayed(actualPlayers.at(i)->getRoundsPlayed() + 1);
             dealerOfTable->clearHand();
         }
         roundsLeft--;
     }
     for (size_t i = 0; i < players.size(); i++) {
         cout << players.at(i)->getName() << " has finished with " << players.at(i)->getCurrentMoney() << "$ in his hand!\n";
     }
     this->closeTable();
 }
writeTableFile()
void Table::writeTableFile ()
Writes the table file.
Author
Renato Campos
Date
18/11/2016
Definition at line 777 of file Table.cpp.
References waitXTime().
{
     stringstream sstream;
     string tableFILE;
     sstream << this->tableID;
     sstream >> tableFILE;
     tableFILE.insert(0, "table");
     tableFILE += "_temp.txt";
     ofstream outFile(tableFILE);
     for (int j = 0; j < 3; j++)
     {
         if (outFile.is_open())
         {
             outFile << this->moneyOfTable << endl << "{" << endl;
             for (size_t i = 0; i < players.size(); i++)
             {
                 players.at(i)->saveInfo(outFile);
                 outFile << endl;
             }
             outFile << "}" << endl << "{" << endl;
             for (size_t i = 0; i < actualPlayers.size(); i++)
             {
                 actualPlayers.at(i)->saveInfo(outFile);
                 outFile << endl;
             }
             outFile << "}" << endl;
             outFile << this->nextPlayerIndex << endl
                 << bossUserID << endl
                 << phaseOfPlaying << endl;
             outFile.close();
             return;
         }
         else
         {
             waitXTime(1);
         }
     }
     //TODO: throw exception
     cout << "Fail to save table file" << endl;
 }
Member Data Documentation
actualPlayers
vector<Player*> Table::actualPlayers private
The actual players.
Definition at line 139 of file Table.h.
bossUserID
unsigned int Table::bossUserID private
Definition at line 142 of file Table.h.
dealerOfTable
Dealer* Table::dealerOfTable private
The dealer of table.
Definition at line 135 of file Table.h.
initialMoney
unsigned int Table::initialMoney private
The initial money.
Definition at line 127 of file Table.h.
maxBet
unsigned int Table::maxBet private
The maximum bet.
Definition at line 125 of file Table.h.
maxNumberOfPlayers
unsigned int Table::maxNumberOfPlayers private
The maximum number of players.
Definition at line 131 of file Table.h.
minBet
unsigned int Table::minBet private
The minimum bet.
Definition at line 123 of file Table.h.
moneyOfTable
float Table::moneyOfTable private
The money of the table.
Definition at line 129 of file Table.h.
nextID
unsigned int Table::nextID = 0 static private
Identifier of the next table.
Definition at line 120 of file Table.h.
nextPlayerIndex
unsigned int Table::nextPlayerIndex private
Definition at line 141 of file Table.h.
phaseOfPlaying
unsigned int Table::phaseOfPlaying private
Definition at line 143 of file Table.h.
players
vector<Player*> Table::players private
The players.
Definition at line 137 of file Table.h.
tableID
int Table::tableID private
Identifier for the table.
Definition at line 133 of file Table.h.
The documentation for this class was generated from the following files:
Table.h
Table.cpp