Aeda-Casino: Casino Class Reference
Casino Class Reference
A casino.
#include <Casino.h>
Public Member Functions
void showUsers (int n)
Display accounts infos.
Casino (unsigned int totalMoney)
Constructor.
Casino (unsigned int totalMoney, vector< Table *> &tables, vector< Player *> &players)
Constructor.
bool login (pair< int, int > xy)
login system.
string getUserLoginName ()
login system.
void addTablesToCasino (vector< Table *> tables)
Adds the tables to casino.
void addTableToCasino (Table *table)
Adds a table to casino.
void removeTableFromCasino (Table *table)
Removes the table from casino.
void addPlayerToCasino (Player *player1)
Adds a player to casino.
void removePlayerFromCasino (string name)
Removes the player from casino.
void addPlayersToCasino (vector< Player *> &playersVector)
Adds the players to casino.
void addPlayersToTable (vector< Player *> &playersVector, Table *table)
Adds the players to a Table of the casino.
void addPlayerToTable (Player *player1, Table *table)
Adds a player to a table of the casino.
void addDealerToCasino (Dealer *newDealer)
Adds a dealer to the casino.
void removeDealerFromCasino (Dealer *dealer)
Removes a dealer from the casino.
void setPlayersFile (string playerFile)
Sets players file.
void setDealersFile (string dealersFile)
Sets dealers file.
void setTablesFile (string tablesFile)
Sets tables file.
void setUsersFile (string usersFile)
Sets users file.
void readPlayersFile ()
Reads players .txt file. The players file should be placed in the project directory.
void readDealersFile ()
Reads dealers .txt file. The dealers file should be placed in the project directory.
void readTablesFile ()
Reads tables .txt file. The tables file should be placed in the project directory.
void readLoginFile ()
Reads login .txt file. The login file should be placed in the project directory.
void savePlayersFile ()
Saves the players in a txt file.
void saveDealersFile ()
Saves the dealers in a txt file.
void saveTablesFile ()
Saves the tables in a txt file.
void saveLoginFile ()
Saves login .txt file.
void fillBestPlayersSet ()
Fills best players set with player that have played at least 1 round.
template<class T >
void showStatistics (set< Player *, T > setOfPlayers, int numberOfPlayersToShow) const
Displays casino's statistics in a user friendly way on the terminal.
void showStatisticsMenu (pair< short, short > xy)
Lets user select the order that the players will be dispayed on the scoreboard.
void showPlayers (pair< short, short > xy) const
Displays the players that are logged in a user friendly way on the terminal.
void showDealers (pair< short, short > xy) const
Displays casino's dealers in a user friendly way on the terminal.
void showTables (pair< short, short > xy)
Displays casino's tables in a user friendly way on the terminal.
vector< Table * > getTables () const
Gets the tables.
void selectTable (pair< short, short > xy)
Select table using the given <x,y> coordinates.
void setTableToPlay (int tableID)
Sets table to play.
Table * getTableToPlay () const
Gets table to play.
void manage (pair< short, short > xy)
Manages casino. Enables the user to select between menus.
void create (pair< short, short > xy)
Creates a menu for casino.
void eliminate (pair< short, short > xy)
Open a delete menu.
void manageTables (pair< short, short > xy, unsigned int tableID)
Manage tables.
unsigned int findTable (unsigned int tableID)
Searches for a table (sequential search).
unsigned int findDealer (unsigned int dealerID)
Searches for a dealer (sequential search).
unsigned int findPlayer (string name)
Searches for a player (sequential search).
Private Attributes
string playersFile
The players file.
string dealersFile
The dealers file.
string tablesFile
The tables file.
string usersFile
The users file.
unsigned int totalMoney
The total money.
int tableToPlay
The table to play.
vector< Dealer * > dealers
The dealers.
vector< Table * > tables
The tables.
vector< Player * > players
The players.
loginHash userslogin
An unordered_set representing the hash table.
pair< string, string > userLOGIN
The users actual logged.
set< Player *, CompareByAverageProfit > bestPlayers
Detailed Description
A casino.
Author
Ineeve
Date
19/11/2016
Definition at line 413 of file Casino.h.
Constructor & Destructor Documentation
Casino() [1/2]
Casino::Casino (unsigned int totalMoney)
Constructor.
Author
Ineeve
Date
19/11/2016
Parameters
totalMoney The total money.
Definition at line 32 of file Casino.cpp.
References totalMoney.
 {
     this->totalMoney = totalMoney;
 }
Casino() [2/2]
Casino::Casino (unsigned int totalMoney, vector< Table *> & tables, vector< Player *> & players)
Constructor.
Author
Ineeve
Date
19/11/2016
Parameters
totalMoney The total money.
[in,out] tables Vector of pointers to tables.
[in,out] players Vector of pointers to players.
Definition at line 37 of file Casino.cpp.
References addPlayersToCasino(), addTablesToCasino(), dealers, tables, and totalMoney.
 {
     addTablesToCasino(tablesVector);
     addPlayersToCasino(playersVector);
     for (size_t i = 0; i < tables.size(); i++) {
         dealers.push_back(tables.at(i)->getDealer());
     }
     this->totalMoney = totalMoney;
 }
Member Function Documentation
addDealerToCasino()
void Casino::addDealerToCasino (Dealer * newDealer)
Adds a dealer to the casino.
Author
Ineeve
Date
19/11/2016
Parameters
[in,out] newDealer Pointer to the dealer that should be added to the casino.
Definition at line 267 of file Casino.cpp.
References dealers, and Dealer::getID().
Referenced by create(), and readDealersFile().
{
     for (size_t i = 0; i < dealers.size(); i++)
     {
         if (newDealer->getID() == dealers.at(i)->getID())
         {
             throw DealerAlreadyExistException(newDealer);
         }
     }
     dealers.push_back(newDealer);
 }
addPlayersToCasino()
void Casino::addPlayersToCasino (vector< Player *> & playersVector)
Adds the players to casino.
Author
Ineeve
Date
19/11/2016
Parameters
[in,out] playersVector Vector of pointers to the players that should be added.
Definition at line 220 of file Casino.cpp.
References players.
Referenced by Casino().
 {
     players.insert(players.end(), newPlayers.begin(), newPlayers.end());
 }
addPlayersToTable()
void Casino::addPlayersToTable (vector< Player *> & playersVector, Table * table)
Adds the players to a Table of the casino.
Author
Ineeve
Date
19/11/2016
Parameters
[in,out] playersVector Vector of pointers to players.
[in,out] table Pointer to the table in which the players will be added.
Definition at line 226 of file Casino.cpp.
References addPlayerToTable().
 {
     for (size_t i = 0; i < playersVector.size(); i++) {
         addPlayerToTable(playersVector.at(i), table);
     }
 }
addPlayerToCasino()
void Casino::addPlayerToCasino (Player * player1)
Adds a player to casino.
Author
Ineeve
Date
19/11/2016
Parameters
[in,out] player1 Pointer to the player to be logged in the casino.
Definition at line 191 of file Casino.cpp.
References Player::getName(), and players.
Referenced by create(), and readTablesFile().
 {
     for (size_t i = 0; i < players.size(); i++)
     {
         if (player1->getName() == players.at(i)->getName())
         {
             throw PlayerAlreadyExistException(player1);
         }
     }
     players.push_back(player1);
 }
addPlayerToTable()
void Casino::addPlayerToTable (Player * player1, Table * table)
Adds a player to a table of the casino.
Author
Ineeve
Date
19/11/2016
Parameters
[in,out] player1 Pointer to the player that should be added to the table.
[in,out] table Pointer to the table.
Definition at line 233 of file Casino.cpp.
References Table::addPlayer(), players, tables, TooManyPlayersException::what(), and PlayerNotLoggedException::what().
Referenced by addPlayersToTable().
 {
     bool foundPlayer = false;
     bool foundTable = false;
     try {
         for (size_t i = 0; i < tables.size(); i++) {
             if (tables.at(i) == table) {
                 foundTable = true;
             }
         }
         if (foundTable == false) {
             throw TableNotInCasinoException(table);
         }
         for (size_t i = 0; i < players.size(); i++) {
             if (players.at(i) == player1) {
                 foundPlayer = true;
                 table->addPlayer(player1);
                 break;
             }
         }
         if (foundPlayer == false) {
             throw PlayerNotLoggedException(player1);
         }
     }
     catch (TooManyPlayersException &e) {
         e.what();
     }
     catch (PlayerNotLoggedException &p) {
         p.what();
     }
 }
addTablesToCasino()
void Casino::addTablesToCasino (vector< Table *> tables)
Adds the tables to casino.
Author
Ineeve
Date
19/11/2016
Parameters
[in,out] tables Vector of pointers to tables.
Definition at line 154 of file Casino.cpp.
References addTableToCasino().
Referenced by Casino().
 {
     for (size_t i = 0; i < tables.size(); i++) {
         addTableToCasino(tables.at(i));
     }
 }
addTableToCasino()
void Casino::addTableToCasino (Table * table)
Adds a table to casino.
Author
Ineeve
Date
19/11/2016
Parameters
[in,out] table Pointer of the table to be added.
Definition at line 161 of file Casino.cpp.
References Table::getInitialMoney(), sortFunctionTables(), tables, totalMoney, and ExistingTableException::what().
Referenced by addTablesToCasino(), create(), and readTablesFile().
 {
     try {
         for (size_t i = 0; i < tables.size(); i++) {
             if (tables.at(i) == table) {
                 throw ExistingTableException(table);
             }
         }
         tables.push_back(table);
         totalMoney -= table->getInitialMoney();
         sort(tables.begin(), tables.end(), sortFunctionTables);
     }
     catch (ExistingTableException &e) {
         e.what();
     }
 }
create()
void Casino::create (pair< short, short > xy)
Creates a menu for casino.
Author
Ineeve
Date
19/11/2016
Parameters
xy The <x,y> coordinates.
Definition at line 735 of file Casino.cpp.
References addDealerToCasino(), addPlayerToCasino(), addTableToCasino(), createMenu(), cursorxy(), dealers, Dealer::getTableOn(), readUnsignedInt(), readUnsignedIntBetween(), showDealers(), and userslogin.
Referenced by manage().
{
     unsigned int exit = 0;
     unsigned int choice;
     string text, name, pass;
     int x = (xy.first - 36) / 2 + 4;
     char ch = 0;
     pair <string, string> newUser;
     loginHash::iterator it;
     while (!exit)
     {
         createMenu(xy, choice);
         switch (choice)
         {
         case 0:
             exit = 1;
             break;
         case 1:
             try
             {
                 unsigned int minBet, maxBet, numberMaxOfPlayer, initialMoney, dealerID, found = 0;
                 Dealer *dealerOfTable;
                 dealersPriority dq;
                 for (size_t i = 0; i < dealers.size(); i++)
                 {
                     dq.push(dealers.at(i));
                 }
                 system("CLS");
                 cout << "Initial Money?" << endl;
                 initialMoney = readUnsignedIntBetween(10000, 50000);
                 cout << "Min Bet?" << endl;
                 minBet = readUnsignedIntBetween(1, initialMoney / 1000);
                 cout << "Max Bet?" << endl;
                 maxBet = readUnsignedIntBetween(minBet, 32 * minBet);
                 cout << "Number Max Of Players?" << endl;
                 numberMaxOfPlayer = readUnsignedIntBetween(1, 6);
                 this->showDealers(xy);
                 dealerID = dq.top()->getID();
                 cout << "The dealers with ID: " << dealerID << " will be set for this table" << endl;
                 dealerOfTable = dq.top();
                 if (dealerOfTable->getTableOn() == -1)
                 {
                     Table *newTable = new Table(minBet, maxBet, initialMoney, numberMaxOfPlayer, dealerOfTable);
                     this->addTableToCasino(newTable);
                 }
                 else
                 {
                     throw DealerIsOnTableAlreadyException(new Dealer(dealerID));
                 }
                 cout << "Tables was created with success" << endl;
                 system("pause");
             }
             catch (DealerNotExistException)
             {
                 cout << "Tables wasn't created with success" << endl;
                 cout << "The Dealer doesn't exist, pls try again" << endl;
                 system("pause");
             }
             catch (DealerIsOnTableAlreadyException)
             {
                 cout << "Tables wasn't created with success" << endl;
                 cout << "The Dealer have one table already, pls try again" << endl;
                 system("pause");
             }
             break;
         case 2:
             try
             {
                 Dealer *newDealer = new Dealer();
                 this->addDealerToCasino(newDealer);
                 cout << "Dealer was created with success" << endl;
                 system("pause");
             }
             catch (DealerAlreadyExistException)
             {
                 cout << "Dealer wasn't created with success" << endl;
                 cout << "This Dealer already Exist" << endl;
                 system("pause");
             }
             break;
         case 3:
             try
             {
                 Player *newBot = new Bot0();
                 string name;
                 while (name.length() == 0)
                 {
                     cout << "What name do you want for bot?" << endl;
                     getline(cin, name);
                 }
                 cout << "How many initial money do you want for bot?" << endl;
                 unsigned int money = readUnsignedInt();
                 cout << "What Bot do you want create (0 , 1 , 2)?" << endl;
                 unsigned int botInteligent = readUnsignedIntBetween(0, 2);
                 if (botInteligent == 0)
                 {
                     newBot = new Bot0(name, money);
                 }
                 if (botInteligent == 1)
                 {
                     newBot = new Bot1(name, money);
                 }
                 if (botInteligent == 2)
                 {
                     newBot = new Bot2(name, money);
                 }
                 this->addPlayerToCasino(newBot);
                 cout << "Player was created with success" << endl;
                 system("pause");
             }
             catch (PlayerAlreadyExistException)
             {
                 cout << "Player wasn't created with success" << endl;
                 cout << "This Player already Exist" << endl;
                 system("pause");
             }
             break;
         case 4:
             system("CLS");
             cout << setw((xy.first - 36) / 2 - 1) << (char)201; //
             for (unsigned int i = 0; i <= 36; i++)
             {
                 cout << (char)205; //
             }
             cout << (char)187 << endl; //
             text = "Login";
             cout << setw((xy.first - 36) / 2 - 1) << (char)186 //
                 << setw((38 + text.length()) / 2) << text
                 << setw(38 - (38 + text.length()) / 2) << (char)186 << endl; //
             cout << setw((xy.first - 36) / 2 - 1) << (char)204; //
             for (unsigned int i = 0; i <= 36; i++)
             {
                 cout << (char)205; //
             }
             cout << (char)185 /**/ << endl;
             text = "UserName:";
             cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << " " << text << setw(38 - (4 + text.length())) << (char)186 << endl;
                             cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)218;
             for (unsigned int i = 0; i <= 28; i++)
             {
                 cout << (char)196;
             }
             cout << (char)191 << setw(4) << (char)186 << endl;
             cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)179 << setw(38 - 8) << (char)179 << setw(4) << (char)186 << endl;
             cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)192;
             for (unsigned int i = 0; i <= 28; i++)
             {
                 cout << (char)196;
             }
             cout << (char)217 << setw(4) << (char)186 << endl;
             text = "Password:";
             cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << " " << text << setw(38 - (4 + text.length())) << (char)186 << endl;
                             cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)218;
             for (unsigned int i = 0; i <= 28; i++)
             {
                 cout << (char)196;
             }
             cout << (char)191 << setw(4) << (char)186 << endl;
             cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)179 << setw(38 - 8) << (char)179 << setw(4) << (char)186 << endl;
             cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)192;
             for (unsigned int i = 0; i <= 28; i++)
             {
                 cout << (char)196;
             }
             cout << (char)217 << setw(4) << (char)186 << endl;
             cout << setw((xy.first - 36) / 2 - 1) << (char)200;
             for (unsigned int i = 0; i <= 36; i++)
             {
                 cout << (char)205;
             }
             cout << (char)188 << endl << endl;
             cursorxy((xy.first - 36) / 2 + 4, 5);
             getline(cin, name);
             cursorxy((xy.first - 36) / 2 + 4, 9);
             while (ch != 13) //character 13 is enter
             {
                 ch = _getch();
                 cursorxy(x, 9);
                 if (ch == 8)
                 {
                     if (!pass.empty())
                     {
                         x--;
                         cursorxy(x, 9);
                         cout << ' ' ;
                         cursorxy(x, 9);
                         pass.pop_back();
                     }
                 }
                 else
                 {
                     cout << '*';
                     pass.push_back(ch);
                     x++;
                 }
             }
             cursorxy(0, 24);
             newUser.first = name;
             newUser.second = pass;
             it = userslogin.find(newUser);
             if (it == userslogin.end())
             {
                 userslogin.insert(newUser);
                 cout << "Account was created with success!" << endl;
                 system("pause");
             }
             else{
                 cout << "Account wasn't created with success!" << endl;
                 system("pause");
             }
             break;
         default:
             break;
         }
     }
 }
eliminate()
void Casino::eliminate (pair< short, short > xy)
Open a delete menu.
Author
Ineeve
Date
19/11/2016
Parameters
xy The <x,y> coordinates.
Definition at line 953 of file Casino.cpp.
References deleteMenu(), PlayerStillOnTableException::getTableId(), DealerStillOnTableException::getTableID(), readUnsignedInt(), removeDealerFromCasino(), removePlayerFromCasino(), removeTableFromCasino(), showDealers(), showPlayers(), showTables(), showUsers(), and userslogin.
Referenced by manage().
{
     unsigned int exit = 0;
     unsigned int choice;
     while (!exit)
     {
         deleteMenu(xy, choice);
         switch (choice)
         {
         case 0:
             exit = 1;
             break;
         case 1:
             try
             {
                 this->showTables(xy);
                 unsigned int tableID = readUnsignedInt();
                 Table *table = new Table(tableID);
                 this->removeTableFromCasino(table);
                 cout << "The tablet was deleted with success" << endl;
                 system("pause");
             }
             catch (TableNotInCasinoException)
             {
                 cout << "The tablet wasnt deleted with success" << endl;
                 cout << "The tablet doesn't exist" << endl;
                 system("pause");
             }
             break;
         case 2:
             try
             {
                 this->showDealers(xy);
                 unsigned int dealerID = readUnsignedInt();
                 Dealer *dealer = new Dealer(dealerID);
                 this->removeDealerFromCasino(dealer);
                 cout << "The dealer was deleted with success" << endl;
                 system("pause");
             }
             catch (DealerNotExistException)
             {
                 cout << "The dealer wasnt deleted with success" << endl;
                 cout << "The dealer doesn't exist" << endl;
                 system("pause");
             }
             catch (DealerStillOnTableException dealer)
             {
                 cout << "The dealer wasnt deleted with success" << endl;
                 cout << "The dealer still on table : " << dealer.getTableID() << " please remove from table first" << endl;
                 system("pause");
             }
             break;
         case 3:
             try
             {
                 this->showPlayers(xy);
                 string name;
                 while (name.length() == 0)
                 {
                     cout << "What is the name of bot to remove?" << endl;
                     getline(cin, name);
                 }
                 this->removePlayerFromCasino(name);
                 cout << "The player was deleted with success" << endl;
                 system("pause");
             }
             catch (PlayerNotExistException)
             {
                 cout << "The player wasnt deleted with success" << endl;
                 cout << "The player doesn't exist" << endl;
                 system("pause");
             }
             catch (PlayerStillOnTableException player)
             {
                 cout << "The player wasnt deleted with success" << endl;
                 cout << "The player still on table : " << player.getTableId() << " please remove from table first" << endl;
                 system("pause");
             }
             break;
         case 4:
             try
             {
                 system("cls");
                 cout << "How many accounts do you want to show?" << endl;
                 int n;
                 stringstream ss;
                 string line;
                 getline(cin, line);
                 ss << line;
                 ss >> n;
                 this->showUsers(n);
                 cout << "What is the username?" << endl;
                 string name;
                 getline(cin, name);
                 cout << "What is the password?" << endl;
                 string pass;
                 getline(cin, pass);
                 pair<string, string> user(name, pass);
                 loginHash::iterator it = userslogin.find(user);
                 if (it != userslogin.end())
                 {
                     cout << "Do you want remove(0)/edit(1)?" << endl;
                     stringstream ss2;
                     string line2;
                     getline(cin, line2);
                     ss2 << line2;
                     ss2 >> n;
                     if (n == 0)
                     {
                         userslogin.erase(it);
                         cout << "Account was removed with success!" << endl;
                         system("pause");
                     }
                     else if(n == 1) {
                         cout << "What is the new password?" << endl;
                         getline(cin, pass);
                         pair<string, string> newUser(name, pass);
                         userslogin.erase(it);
                         userslogin.insert(newUser);
                     }
                 }
                 else
                 {
                     cout << "Account wasnt removed with success!" << endl;
                     system("pause");
                 }
             }
             catch (exception& e)
             {
                 cout << e.what() << endl;
             }
             break;
         default:
             break;
         }
     }
 }
fillBestPlayersSet()
void Casino::fillBestPlayersSet ()
Fills best players set with player that have played at least 1 round.
Author
Ineeve
Date
30/12/2016
Definition at line 1265 of file Casino.cpp.
References bestPlayers, and players.
Referenced by manage().
{
     for (auto i = players.begin(); i != players.end(); i++) {
         if (bestPlayers.find((*i)) == bestPlayers.end() && (*i)->getRoundsPlayed() > 0) {
             bestPlayers.insert((*i));
         }
     }
 }
findDealer()
unsigned int Casino::findDealer (unsigned int dealerID)
Searches for a dealer (sequential search).
Author
Ineeve
Date
19/11/2016
Parameters
dealerID Identifier for the dealer.
Returns
The index of the dealer on the dealers vector.
Definition at line 1242 of file Casino.cpp.
References dealers.
Referenced by manageTables().
{
     for (size_t i = 0; i < dealers.size(); i++)
     {
         if (dealers.at(i)->getID() == dealerID)
         {
             return i;
         }
     }
     throw DealerNotExistException(new Dealer(dealerID));
 }
findPlayer()
unsigned int Casino::findPlayer (string name)
Searches for a player (sequential search).
Author
Ineeve
Date
19/11/2016
Parameters
name The name of the player.
Returns
The index of the player in the players vector.
Definition at line 1253 of file Casino.cpp.
References players.
Referenced by manageTables(), and readTablesFile().
{
     for (size_t i = 0; i < players.size(); i++)
     {
         if (players.at(i)->getName() == name)
         {
             return i;
         }
     }
     throw PlayerNotExistException(name);
 }
findTable()
unsigned int Casino::findTable (unsigned int tableID)
Searches for a table (sequential search).
Author
Ineeve
Date
19/11/2016
Parameters
tableID Identifier for the table.
Returns
The index of the table on the tables vector.
Definition at line 1231 of file Casino.cpp.
References tables.
Referenced by manage(), and manageTables().
{
     for (size_t i = 0; i < tables.size(); i++)
     {
         if (tables.at(i)->getTableID() == tableID)
         {
             return i;
         }
     }
     throw TableNotInCasinoException(new Table(tableID));
 }
getTables()
vector< Table * > Casino::getTables () const
Gets the tables.
Author
Ineeve
Date
19/11/2016
Returns
A vector of pointers to the casino's tables.
Definition at line 653 of file Casino.cpp.
References tables.
{
     return this->tables;
 }
getTableToPlay()
Table * Casino::getTableToPlay () const
Gets table to play.
Author
Ineeve
Date
19/11/2016
Returns
Pointer to the table to play.
Definition at line 677 of file Casino.cpp.
References tables, and tableToPlay.
Referenced by main().
{
     if (this->tableToPlay != -1)
     {
         for (size_t i = 0; i < tables.size(); i++)
         {
             if (this->tableToPlay == tables.at(i)->getTableID())
             {
                 return tables.at(i);
             }
         }
     }
     throw TableNotInCasinoException(new Table(tableToPlay));
 }
getUserLoginName()
string Casino::getUserLoginName ()
login system.
Author
Joo Carvalho
Date
26/12/2016
Definition at line 150 of file Casino.cpp.
References userLOGIN.
Referenced by main().
{
     return userLOGIN.first;
 }
login()
bool Casino::login (pair< int, int > xy)
login system.
Author
Joo Carvalho
Date
26/12/2016
Parameters
xy A pair containing the horizontal and vertical lengths of the terminal.
Definition at line 47 of file Casino.cpp.
References cursorxy(), drawTitle(), userLOGIN, and userslogin.
Referenced by main().
{
     drawTitle(xy);
     string text, name, pass;
     cout << setw((xy.first - 36) / 2 - 1) << (char)201; //
     for (unsigned int i = 0; i <= 36; i++)
     {
         cout << (char)205; //
     }
     cout << (char)187 << endl; //
     text = "Login";
     cout << setw((xy.first - 36) / 2 - 1) << (char)186 //
         << setw((38 + text.length()) / 2) << text
         << setw(38 - (38 + text.length()) / 2) << (char)186 << endl; //
     cout << setw((xy.first - 36) / 2 - 1) << (char)204; //
     for (unsigned int i = 0; i <= 36; i++)
     {
         cout << (char)205; //
     }
     cout << (char)185 /**/ << endl;
     text = "UserName:";
     cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << " " << text << setw(38 - (4 + text.length())) << (char)186 << endl;
     cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)218;
     for (unsigned int i = 0; i <= 28; i++)
     {
         cout << (char)196;
     }
     cout << (char)191 << setw(4) << (char)186 << endl;
     cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)179 << setw(38 - 8) << (char)179 << setw(4) << (char)186 << endl;
     cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)192;
     for (unsigned int i = 0; i <= 28; i++)
     {
         cout << (char)196;
     }
     cout << (char)217 << setw(4) << (char)186 << endl;
     text = "Password:";
     cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << " " << text << setw(38 - (4 + text.length())) << (char)186 << endl;
     cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)218;
     for (unsigned int i = 0; i <= 28; i++)
     {
         cout << (char)196;
     }
     cout << (char)191 << setw(4) << (char)186 << endl;
     cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)179 << setw(38 - 8) << (char)179 << setw(4) << (char)186 << endl;
     cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(4) << (char)192;
     for (unsigned int i = 0; i <= 28; i++)
     {
         cout << (char)196;
     }
     cout << (char)217 << setw(4) << (char)186 << endl;
     cout << setw((xy.first - 36) / 2 - 1) << (char)200;
     for (unsigned int i = 0; i <= 36; i++)
     {
         cout << (char)205;
     }
     cout << (char)188 << endl << endl;
     cursorxy((xy.first - 36) / 2 + 4, 17);
     getline(cin, name);
     cursorxy((xy.first - 36) / 2 + 4, 21);
     int x = (xy.first - 36) / 2 + 4;
     char ch = 0;
     while (ch != 13) //character 13 is enter
     {
         ch = _getch();
         cursorxy(x, 21);
         if (ch == 8)
         {
             if (!pass.empty())
             {
                 x--;
                 cursorxy(x, 21);
                 cout << ' ';
                 cursorxy(x, 21);
                 pass.pop_back();
             }
         }
         else
         {
             cout << '*';
             pass.push_back(ch);
             x++;
         }
     }
     cursorxy(0, 24);
     this->userLOGIN.first = name;
     this->userLOGIN.second = pass;
     if (userslogin.find(this->userLOGIN) != userslogin.end())
     {
         cout << "Login in Sucess" << endl;
         return true;
     }
     else
     {
         cout << "Login Fail" << endl;
         userslogin.insert(this->userLOGIN);
         throw PlayerNotExistException(name);
     }
 }
manage()
void Casino::manage (pair< short, short > xy)
Manages casino. Enables the user to select between menus.
Author
Ineeve
Date
19/11/2016
Parameters
xy The <x,y> coordinates.
Definition at line 691 of file Casino.cpp.
References create(), eliminate(), fillBestPlayersSet(), findTable(), manageCasino(), manageTables(), readUnsignedInt(), showStatisticsMenu(), and showTables().
Referenced by main().
{
     unsigned int exit = 0;
     unsigned int choice, tableID;
     while (!exit)
     {
         manageCasino(xy, choice);
         switch (choice)
         {
         case 0:
             exit = 1;
             break;
         case 1:
             this->create(xy);
             break;
         case 2:
             this->eliminate(xy);
             break;
         case 3:
             this->showTables(xy);
             try
             {
                 cout << "Select table by ID" << endl;
                 tableID = readUnsignedInt();
                 this->findTable(tableID);
                 this->manageTables(xy, tableID);
             }
             catch (TableNotInCasinoException)
             {
                 cout << "This table not exist" << endl;
                 system("pause");
             }
             break;
         case 4:
             system("cls");
             fillBestPlayersSet();
             this->showStatisticsMenu(xy);
             system("pause");
             break;
         default:
             break;
         }
     }
 }
manageTables()
void Casino::manageTables (pair< short, short > xy, unsigned int tableID)
Manage tables.
Author
Ineeve
Date
19/11/2016
Parameters
xy The <x,y> coordinates.
tableID Identifier for the table.
Definition at line 1091 of file Casino.cpp.
References dealers, findDealer(), findPlayer(), findTable(), Table::getPlayers(), manageTableMenu(), players, readUnsignedInt(), Table::removePlayer(), showDealers(), showPlayers(), and tables.
Referenced by manage().
{
     unsigned int exit = 0;
     unsigned int choice, dealerID;
     string playerName;
     while (!exit)
     {
         manageTableMenu(xy, choice);
         switch (choice)
         {
         case 0:
             exit = 1;
             break;
         case 1:
             try
             {
                 showDealers(xy);
                 dealerID = readUnsignedInt();
                 unsigned int dealerIndex = this->findDealer(dealerID);
                 if (dealers.at(dealerIndex)->getTableOn() != -1)
                 {
                     throw DealerIsOnTableAlreadyException(dealers.at(dealerIndex));
                 }
                 tables.at(this->findTable(tableID))->setDealer(dealers.at(dealerIndex));
                 cout << "Dealer was set with success" << endl;
                 system("pause");
             }
             catch (DealerNotExistException)
             {
                 cout << "Dealer wasn't set with success" << endl;
                 cout << "This Dealer not exist" << endl;
                 system("pause");
             }
             catch (DealerIsOnTableAlreadyException)
             {
                 cout << "Dealer wasn't set with success" << endl;
                 cout << "This Dealer have one table for him already" << endl;
                 system("pause");
             }
             catch (TableNotInCasinoException &table)
             {
                 throw table;
             }
             break;
         case 2:
             try
             {
                 if (tables.at(findTable(tableID))->getPlayers().size() == tables.at(findTable(tableID))->getNumberMaxOfPlayers())
                 {
                     throw TooManyPlayersException(tables.at(findTable(tableID))->getNumberMaxOfPlayers(), tables.at(findTable(tableID))->getNumberMaxOfPlayers() + 1);
                 }
                 showPlayers(xy);
                 cout << "Select the player that you want to add to the table" << endl;
                 playerName = "";
                 while (playerName.length() == 0)
                 {
                     getline(cin, playerName);
                 }
                 unsigned int playerIndex = findPlayer(playerName);
                 if (players.at(playerIndex)->getOnTable() != -1)
                 {
                     throw PlayerStillOnTableException(players.at(playerIndex));
                 }
                 tables.at(findTable(tableID))->addPlayer(players.at(playerIndex));
                 cout << "Player was added with success to table" << endl;
                 system("pause");
             }
             catch (TableNotInCasinoException &table)
             {
                 throw table;
             }
             catch (PlayerNotExistException)
             {
                 cout << "The player wasn't added to table" << endl;
                 cout << "The player does not exist" << endl;
                 system("pause");
             }
             catch (PlayerStillOnTableException)
             {
                 cout << "The player wasn't added to table" << endl;
                 cout << "The player is on other table already" << endl;
                 system("pause");
             }
             catch (TooManyPlayersException)
             {
                 cout << "The player wasn't added to table" << endl;
                 cout << "The table is full" << endl;
                 system("pause");
             }
             break;
         case 3:
             try
             {
                 Table *table = tables.at(findTable(tableID));
                 if (table->getPlayers().size() == 0)
                 {
                     throw NoPlayersOnTableException(table);
                 }
                 for (size_t i = 0; i < table->getPlayers().size(); i++)
                 {
                     cout << table->getPlayers().at(i)->getName() << endl;
                 }
                 playerName = "";
                 while (playerName.length() == 0)
                 {
                     getline(cin, playerName);
                 }
                 table = tables.at(findTable(tableID));
                 table->removePlayer(playerName);
                 cout << "Player was removed from table with success" << endl;
                 system("pause");
             }
             catch (TableNotInCasinoException &table)
             {
                 throw table;
             }
             catch (PlayerNotExistException)
             {
                 cout << "The player wasn't remove from table" << endl;
                 cout << "The player does not exist" << endl;
                 system("pause");
             }
             catch (PlayerIsntOnTableException)
             {
                 cout << "The player wasn't remove from table" << endl;
                 cout << "The player wasn't on table" << endl;
                 system("pause");
             }
             catch (NoPlayersOnTableException)
             {
                 cout << "The table dont have players to remove" << endl;
                 system("pause");
             }
             break;
         default:
             break;
         }
     }
 }
readDealersFile()
void Casino::readDealersFile ()
Reads dealers .txt file. The dealers file should be placed in the project directory.
Author
Ineeve
Date
19/11/2016
Definition at line 377 of file Casino.cpp.
References addDealerToCasino(), dealers, dealersFile, DealerAlreadyExistException::getID(), and Dealer::setNextID().
Referenced by main().
{
     ifstream inFile(dealersFile);
     string line;
     unsigned int nextID;
     for (int i = 0; i < 3; i++)
     {
         if (inFile.is_open())
         {
             if (!dealers.empty()) dealers.clear();
             getline(inFile, line);
             nextID = stoi(line);
             while (getline(inFile, line))
             {
                 Dealer *newDealer = new Dealer(stoi(line));
                 try
                 {
                     this->addDealerToCasino(newDealer);
                 }
                 catch (DealerAlreadyExistException dealer)
                 {
                     cout << "Dealer with ID : " << dealer.getID() << " already exist" << endl;
                 }
             }
             Dealer::setNextID(nextID);
             return;
         }
     }
     unsigned int maxID = 0;
     for (size_t i = 0; i < dealers.size(); i++)
     {
         if (dealers.at(i)->getID() >= maxID)
         {
             maxID = dealers.at(i)->getID() + 1;
         }
     }
     Dealer::setNextID(maxID);
     cout << "Fail to open dealers file" << endl;
 }
readLoginFile()
void Casino::readLoginFile ()
Reads login .txt file. The login file should be placed in the project directory.
Author
Joo Carvalho
Date
26/12/2016
Definition at line 530 of file Casino.cpp.
References usersFile, and userslogin.
Referenced by main().
{
     ifstream inFile(usersFile);
     string line, name, pass;
     for (int i = 0; i < 3; i++)
     {
         if (inFile.is_open())
         {
             while (getline(inFile, line))
             {
                 name = line.substr(0, line.find(";"));
                 line.erase(0, line.find(";") + 1);
                 pass = line.substr(0, line.find(";"));
                 pair <string, string> user(name, pass);
                 userslogin.insert(user);
             }
             return;
         }
     }
     cout << "Fail to read tables file" << endl;
 }
readPlayersFile()
void Casino::readPlayersFile ()
Reads players .txt file. The players file should be placed in the project directory.
Author
Ineeve
Date
19/11/2016
Definition at line 311 of file Casino.cpp.
References players, playersFile, Player::setInitialMoney(), Player::setOnTable(), and sortFunctionPlayers().
Referenced by main().
{
     ifstream inFile(playersFile);
     string line;
     stringstream ssLine;
     string player;
     string name;
     unsigned int initialMoney, age, tableOnID;
     for (int i = 0; i < 3; i++)
     {
         if (inFile.is_open())
         {
             if (!players.empty()) players.clear();
             while (getline(inFile, line))
             {
                 player = line.substr(0, line.find_first_of(" ; "));
                 line.erase(0, line.find_first_of(" ; ") + 3);
                 name = line.substr(0, line.find_first_of(";") - 1);
                 line.erase(0, line.find_first_of(";") + 2);
                 initialMoney = stoi(line.substr(0, line.find_first_of(" ; ")), nullptr, 10);
                 line.erase(0, line.find_first_of(" ; ") + 3);
                 if (player == "3")
                 {
                     ssLine << line;
                     ssLine >> age;
                     ssLine.clear();
                     Human *newHuman = new Human(name, age, -1);
                     newHuman->setInitialMoney(initialMoney);
                     players.push_back(newHuman);
                 }
                 if (player == "0")
                 {
                     ssLine << line;
                     ssLine >> tableOnID;
                     ssLine.clear();
                     Bot0 *newBot0 = new Bot0(name, initialMoney);
                     newBot0->setOnTable(tableOnID);
                     players.push_back(newBot0);
                 }
                 if (player == "1")
                 {
                     ssLine << line;
                     ssLine >> tableOnID;
                     ssLine.clear();
                     Bot1 *newBot1 = new Bot1(name, initialMoney);
                     newBot1->setOnTable(tableOnID);
                     players.push_back(newBot1);
                 }
                 if (player == "2")
                 {
                     ssLine << line;
                     ssLine >> tableOnID;
                     ssLine.clear();
                     Bot2 *newBot2 = new Bot2(name, initialMoney);
                     newBot2->setOnTable(tableOnID);
                     players.push_back(newBot2);
                 }
             }
             sort(players.begin(), players.end(), sortFunctionPlayers);
             return;
         }
     }
     cout << "Fail to open players file" << endl;
 }
readTablesFile()
void Casino::readTablesFile ()
Reads tables .txt file. The tables file should be placed in the project directory.
Author
Ineeve
Date
19/11/2016
Definition at line 416 of file Casino.cpp.
References Table::addPlayer(), addPlayerToCasino(), addTableToCasino(), dealers, findPlayer(), Player::getName(), players, Table::setID(), Table::setNextID(), sortFunctionDealers(), tables, and tablesFile.
Referenced by main().
{
     ifstream inFile(tablesFile);
     string line;
     unsigned int tableID;
     unsigned int minBet;
     unsigned int maxBet;
     unsigned int initialMoney;
     unsigned int maxNumberOfPlayers;
     unsigned int dealerID;
     unsigned int nextID;
     Dealer *dealerOfTable = new Dealer();
     for (int i = 0; i < 3; i++)
     {
         if (inFile.is_open())
         {
             if (!tables.empty()) tables.clear();
             getline(inFile, line);
             nextID = stoi(line);
             while (getline(inFile, line))
             {
                 tableID = stoi(line.substr(0, line.find_first_of(" ; ")));
                 line.erase(0, line.find_first_of(" ; ") + 3);
                 minBet = stoi(line.substr(0, line.find_first_of(" ; ")));
                 line.erase(0, line.find_first_of(" ; ") + 3);
                 maxBet = stoi(line.substr(0, line.find_first_of(" ; ")));
                 line.erase(0, line.find_first_of(" ; ") + 3);
                 initialMoney = stoi(line.substr(0, line.find_first_of(" ; ")));
                 line.erase(0, line.find_first_of(" ; ") + 3);
                 maxNumberOfPlayers = stoi(line.substr(0, line.find_first_of(" ; ")));
                 line.erase(0, line.find_first_of(" ; ") + 3);
                 dealerID = stoi(line.substr(0, line.find_first_of(" ; ")));
                 line.erase(0, line.find_first_of(" ; ") + 3);
                 for (size_t i = 0; i < dealers.size(); i++)
                 {
                     if (dealers.at(i)->getID() == dealerID)
                     {
                         dealerOfTable = dealers.at(i);
                         dealers.at(i)->setTable(tableID);
                         break;
                     }
                 }
                 Table *newTable = new Table(minBet, maxBet, initialMoney, maxNumberOfPlayers, dealerOfTable);
                 newTable->setID(tableID);
                 if (line == "{")
                 {
                     while (line != "}")
                     {
                         getline(inFile, line);
                         if (line.substr(0, 1) == "0")
{
                             Player *playerReaded = new Bot0(line);
                             newTable->addPlayer(playerReaded);
                             try
{
                                 players.at(findPlayer(playerReaded->getName())) = playerReaded;
                             }
                             catch (PlayerNotExistException)
{
                                 addPlayerToCasino(playerReaded);
                             }
                         }
                         else if (line.substr(0, 1) == "1")
{
                             Player *playerReaded = new Bot1(line);
                             newTable->addPlayer(playerReaded);
                             try
{
                                 players.at(findPlayer(playerReaded->getName())) = playerReaded;
                             }
                             catch (PlayerNotExistException)
{
                                 addPlayerToCasino(playerReaded);
                             }
                         }
                         else if (line.substr(0, 1) == "2")
{
                             Player *playerReaded = new Bot2(line);
                             newTable->addPlayer(playerReaded);
                             try
{
                                 players.at(findPlayer(playerReaded->getName())) = playerReaded;
                             }
                             catch (PlayerNotExistException)
{
                                 addPlayerToCasino(playerReaded);
                             }
                         }
                         else if (line.substr(0, 1) == "3")
{
                             Player *playerReaded = new Human(line);
                             newTable->addPlayer(playerReaded);
                             try
{
                                 players.at(findPlayer(playerReaded->getName())) = playerReaded;
                             }
                             catch (PlayerNotExistException)
{
                                 addPlayerToCasino(playerReaded);
                             }
                         }
                     }
                 }
                 this->addTableToCasino(newTable);
             }
             Table::setNextID(nextID);
             sort(dealers.begin(), dealers.end(), sortFunctionDealers);
             return;
         }
     }
     cout << "Fail to read tables file" << endl;
 }
removeDealerFromCasino()
void Casino::removeDealerFromCasino (Dealer * dealer)
Removes a dealer from the casino.
Author
Ineeve
Date
19/11/2016
Parameters
[in,out] dealer Pointer to the dealer that should be removed from the casino.
Definition at line 278 of file Casino.cpp.
References dealers, and Dealer::getID().
Referenced by eliminate().
{
     for (size_t i = 0; i < dealers.size(); i++)
     {
         if (dealers.at(i)->getID() == dealer->getID())
         {
             if (dealers.at(i)->getTableOn() != -1)
             {
                 throw DealerStillOnTableException(dealers.at(i));
             }
             delete dealers.at(i);
             dealers.erase(dealers.begin() + i);
             return;
         }
     }
     throw DealerNotExistException(dealer);
 }
removePlayerFromCasino()
void Casino::removePlayerFromCasino (string name)
Removes the player from casino.
Author
Ineeve
Date
19/11/2016
Parameters
name The name of the player to be removed.
Definition at line 203 of file Casino.cpp.
References players.
Referenced by eliminate().
{
     for (size_t i = 0; i < players.size(); i++)
     {
         if (players.at(i)->getName() == name)
         {
             if (players.at(i)->getOnTable() != -1)
             {
                 throw PlayerStillOnTableException(players.at(i));
             }
             delete players.at(i);
             players.erase(players.begin() + i);
             return;
         }
     }
     throw PlayerNotExistException(name);
 }
removeTableFromCasino()
void Casino::removeTableFromCasino (Table * table)
Removes the table from casino.
Author
Ineeve
Date
19/11/2016
Parameters
[in,out] table Pointer of the table to be removed.
Definition at line 178 of file Casino.cpp.
References Table::getTableID(), and tables.
Referenced by eliminate().
{
     for (size_t i = 0; i < tables.size(); i++)
     {
         if (tables.at(i)->getTableID() == table->getTableID())
         {
             delete tables.at(i);
             tables.erase(tables.begin() + i);
             return;
         }
     }
     throw TableNotInCasinoException(table);
 }
saveDealersFile()
void Casino::saveDealersFile ()
Saves the dealers in a txt file.
Author
Ineeve
Date
19/11/2016
Definition at line 586 of file Casino.cpp.
References dealers, dealersFile, and Dealer::getNextID().
Referenced by main().
{
     ofstream outFile(dealersFile);
     for (int i = 0; i < 3; i++)
     {
         if (outFile.is_open())
         {
             outFile << Dealer::getNextID() << endl;
             for (size_t i = 0; i < dealers.size(); i++)
             {
                 outFile << dealers.at(i)->getID() << endl;
             }
             return;
         }
     }
     cout << "Fail to open dealers file" << endl;
 }
saveLoginFile()
void Casino::saveLoginFile ()
Saves login .txt file.
Author
Joo Carvalho
Date
26/12/2016
Definition at line 637 of file Casino.cpp.
References usersFile, and userslogin.
Referenced by main().
{
     ofstream outFile(usersFile);
     for (int i = 0; i < 3; i++)
     {
         if (outFile.is_open())
         {
             for (loginHash::iterator it = userslogin.begin(); it != userslogin.end(); it++)
             {
                 outFile << it->first << ";" << it->second << ";" << endl;
             }
             return;
         }
     }
     cout << "Fail to open tables file" << endl;
 }
savePlayersFile()
void Casino::savePlayersFile ()
Saves the players in a txt file.
Author
Ineeve
Date
19/11/2016
Definition at line 551 of file Casino.cpp.
References players, and playersFile.
Referenced by main().
{
     ofstream outFile(playersFile);
     for (int j = 0; j < 3; j++)
     {
         if (outFile.is_open())
         {
             for (size_t i = 0; i < players.size(); i++)
             {
                 Human *h = dynamic_cast<Human *>(players.at(i));
                 Bot0 *b0 = dynamic_cast<Bot0 *>(players.at(i));
                 Bot1 *b1 = dynamic_cast<Bot1 *>(players.at(i));
                 Bot2 *b2 = dynamic_cast<Bot2 *>(players.at(i));
                 if (h != NULL)
                 {
                     outFile << "3 ; " << players.at(i)->getName() << " ; " << players.at(i)->getInitialMoney() << " ; " << players.at(i)->getAge() << endl;
                 }
                 if (b0 != NULL)
                 {
                     outFile << "0 ; " << players.at(i)->getName() << " ; " << players.at(i)->getInitialMoney() << " ; " << players.at(i)->getOnTable() << endl;
                 }
                 if (b1 != NULL)
                 {
                     outFile << "1 ; " << players.at(i)->getName() << " ; " << players.at(i)->getInitialMoney() << " ; " << players.at(i)->getOnTable() << endl;
                 }
                 if (b2 != NULL)
                 {
                     outFile << "2 ; " << players.at(i)->getName() << " ; " << players.at(i)->getInitialMoney() << " ; " << players.at(i)->getOnTable() << endl;
                 }
             }
             return;
         }
     }
     cout << "Fail to open players file" << endl;
 }
saveTablesFile()
void Casino::saveTablesFile ()
Saves the tables in a txt file.
Author
Ineeve
Date
19/11/2016
Definition at line 603 of file Casino.cpp.
References Table::getNextId(), tables, and tablesFile.
Referenced by main().
{
     ofstream outFile(tablesFile);
     for (int i = 0; i < 3; i++)
     {
         if (outFile.is_open())
         {
             outFile << Table::getNextId() << endl;
             for (size_t i = 0; i < tables.size(); i++)
             {
                 outFile << tables.at(i)->getTableID() << " ; " << tables.at(i)->getMinBet() << " ; " << tables.at(i)->getMaxBet() << " ; " << tables.at(i)->getInitialMoney() << " ; " << tables.at(i)->getNumberMaxOfPlayers() << " ; " << tables.at(i)->getDealer()->getID() << " ; ";
                 if (tables.at(i)->getPlayers().size() != 0)
                 {
                     outFile << "{" << endl;
                 }
                 else
                 {
                     outFile << endl;
                 }
                 for (size_t j = 0; j < tables.at(i)->getPlayers().size(); j++)
                 {
                     tables.at(i)->getPlayers().at(j)->saveInfo(outFile);
                     outFile << endl;
                 }
                 if (tables.at(i)->getPlayers().size() != 0)
                 {
                     outFile << "}" << endl;
                 }
             }
             return;
         }
     }
     cout << "Fail to open tables file" << endl;
 }
selectTable()
void Casino::selectTable (pair< short, short > xy)
Select table using the given <x,y> coordinates.
Author
Ineeve
Date
19/11/2016
Parameters
xy The <x,y> coordinates.
Definition at line 657 of file Casino.cpp.
References readInt(), setTableToPlay(), showTables(), and tables.
Referenced by main().
{
     this->showTables(xy);
     cout << "Select table by ID" << endl;
     unsigned int tableID = readInt();
     for (size_t i = 0; i < tables.size(); i++)
     {
         if (tables.at(i)->getTableID() == tableID)
         {
             this->setTableToPlay(tableID);
             cout << "Table select with success" << endl;
             return;
         }
     }
     throw TableNotInCasinoException(new Table(tableID));
 }
setDealersFile()
void Casino::setDealersFile (string dealersFile)
Sets dealers file.
Author
Ineeve
Date
19/11/2016
Parameters
dealersFile A string already formatted to save the dealers in a file.
Definition at line 299 of file Casino.cpp.
References dealersFile.
Referenced by main().
{
     this->dealersFile = dealersFile;
 }
setPlayersFile()
void Casino::setPlayersFile (string playerFile)
Sets players file.
Author
Ineeve
Date
19/11/2016
Parameters
playerFile A string already formatted to save the players in a file.
Definition at line 295 of file Casino.cpp.
References playersFile.
Referenced by main().
{
     this->playersFile = playerFile;
 }
setTablesFile()
void Casino::setTablesFile (string tablesFile)
Sets tables file.
Author
Ineeve
Date
19/11/2016
Parameters
tablesFile A string already formatted to save the tables in a file.
Definition at line 303 of file Casino.cpp.
References tablesFile.
Referenced by main().
{
     this->tablesFile = tablesFile;
 }
setTableToPlay()
void Casino::setTableToPlay (int tableID)
Sets table to play.
Author
Ineeve
Date
19/11/2016
Parameters
tableID Identifier for the table.
Definition at line 673 of file Casino.cpp.
References tableToPlay.
Referenced by selectTable().
{
     this->tableToPlay = tableID;
 }
setUsersFile()
void Casino::setUsersFile (string usersFile)
Sets users file.
Author
Joao Carvalho
Date
26/12/2016
Parameters
usersFile A string already formatted to save players in a file.
Definition at line 307 of file Casino.cpp.
References usersFile.
Referenced by main().
{
     this->usersFile = usersFile;
 }
showDealers()
void Casino::showDealers (pair< short, short > xy) const
Displays casino's dealers in a user friendly way on the terminal.
Author
Ineeve
Date
19/11/2016
Parameters
xy The cursor coordinates.
Definition at line 1421 of file Casino.cpp.
References dealers.
Referenced by create(), eliminate(), and manageTables().
{
     system("cls");
     dealersPriority dq;
     for (size_t i = 0; i < dealers.size(); i++)
     {
         dq.push(dealers.at(i));
     }
     string text;
     stringstream sstext;
     cout << setw((xy.first - 50) / 2 - 1) << (char)218; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)191 << endl; //
     cout << setw((xy.first - 50) / 2 - 1) << (char)179; //
     cout << setw((50 + 12) / 2 + 1) << "Dealers Info" << setw(50 - (50 + 12) / 2 + 1) << (char)179 << endl;
     cout << setw((xy.first - 50) / 2 - 1) << (char)195; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)180 << endl; //
     cout << setw((xy.first - 50) / 2 - 1) << (char)179; //
     cout << setw(10) << "DealerID" << setw(15) << "On Table" << setw(27) << (char)179 << endl;
     cout << setw((xy.first - 50) / 2 - 1) << (char)195; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)180 << endl; //
     while (!dq.empty())
     {
         cout << setw((xy.first - 50) / 2 - 1) << (char)179; //
         if (dq.top()->getTableOn() != -1)
         {
             sstext.clear();
             sstext << dq.top()->getTableOn();
             sstext >> text;
         }
         else
         {
             text = "Dealer isn't allocated";
         }
         cout << setw(10) << dq.top()->getID() << setw(7) << " " << text << setw(35-text.length()) << (char)179 << endl;
         dq.pop();
     }
     cout << setw((xy.first - 50) / 2 - 1) << (char)192; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)217 << endl; //
 }
showPlayers()
void Casino::showPlayers (pair< short, short > xy) const
Displays the players that are logged in a user friendly way on the terminal.
Author
Ineeve
Date
19/11/2016
Parameters
xy The cursor coordinates.
Definition at line 1370 of file Casino.cpp.
References players.
Referenced by eliminate(), and manageTables().
{
     system("cls");
     string text, name;
     stringstream sstext;
     cout << setw((xy.first - 50) / 2 - 1) << (char)218; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)191 << endl; //
     cout << setw((xy.first - 50) / 2 - 1) << (char)179; //
     cout << setw((50 + 12) / 2 + 1) << "Players Info" << setw(50 - (50 + 12) / 2 + 1) << (char)179 << endl;
     cout << setw((xy.first - 50) / 2 - 1) << (char)195; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)180 << endl; //
     cout << setw((xy.first - 50) / 2 - 1) << (char)179; //
     cout << setw(13) << "Player Name" << setw(21) << "On Table" << setw(18) << (char)179 << endl;
     cout << setw((xy.first - 50) / 2 - 1) << (char)195; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)180 << endl; //
     for (size_t i = 0; i < players.size(); i++)
     {
         cout << setw((xy.first - 50) / 2 - 1) << (char)179; //
         name = players.at(i)->getName();
         cout << setw(2) << " " << name << setw(24 - name.length()) << " ";
         if (players.at(i)->getOnTable() != -1)
         {
             sstext.clear();
             sstext << players.at(i)->getOnTable();
             sstext >> text;
         }
         else
         {
             text = "Player isn't allocated";
         }
         cout << text << setw(26 - text.length()) << (char)179 << endl;
     }
     cout << setw((xy.first - 50) / 2 - 1) << (char)192; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)217 << endl; //
 }
showStatistics()
template<class T > void Casino::showStatistics (set< Player *, T > setOfPlayers, int numberOfPlayersToShow) const
Displays casino's statistics in a user friendly way on the terminal.
Parameters
setOfPlayers a std::set of players order as user selected.
numberOfPlayersToShow Number of players to display.
Author
Ineeve
Date
19/11/2016
Definition at line 1004 of file Casino.h.
References readInt().
Referenced by showStatisticsMenu().
 {
     int userInput;
     system("CLS");
     cout << "Statistics\n\n\n\n";
     cout << setw(15) << "NAME" << setw(25) << "BRAIN LEVEL" << setw(15) << "ROUNDS PLAYED" << setw(18) << "AVG. PROFIT" << setw(15) << "AGE" << endl;
     int counter = 0;
     for (auto i = setOfPlayers.begin(); i != setOfPlayers.end(); i++) {
         if (counter >= numberOfPlayersToShow) {
             break;
         }
         (*i)->showStatistics();
         counter++;
     }
     cout << "0. Back\n";
     while ((userInput = readInt()) != 0) {
         cout << "Please insert a valid option\n";
     }
     return;
 }
showStatisticsMenu()
void Casino::showStatisticsMenu (pair< short, short > xy)
Lets user select the order that the players will be dispayed on the scoreboard.
Parameters
xy Cursor coordinates.
Author
Ineeve
Date
30/12/2016
Definition at line 1315 of file Casino.cpp.
References bestPlayers, readIntBetween(), showStatistics(), and statisticsMenu().
Referenced by manage().
 {
     set<Player*, CompareByAge> setByAge;
     set<Player*, CompareByName> setByName;
     set<Player*, CompareByIntelligence> setBySmart;
     int r, exit = 0;
     unsigned int choice;
     int numberOfPlayers;
     while (!exit)
     {
         statisticsMenu(xy, choice);
         numberOfPlayers = bestPlayers.size();
         if (choice != 0) {
             cout << "How many players do you want to see? ";
             if ((r = readIntBetween(0,65536)) < numberOfPlayers) {
                 numberOfPlayers = r;
             }
         }
         switch (choice)
         {
         case 0: //break
             exit = 1;
             break;
         case 1: //Order by avg.profit
             showStatistics(bestPlayers, numberOfPlayers);
             break;
         case 2: //Order by age
             for (auto i = bestPlayers.begin(); i != bestPlayers.end(); i++) {
                     setByAge.insert((*i));
             }
             showStatistics(setByAge, numberOfPlayers);
             break;
         case 3: //Order by name
             for (auto i = bestPlayers.begin(); i != bestPlayers.end(); i++) {
                 setByName.insert((*i));
             }
             showStatistics(setByName, numberOfPlayers);
             break;
         case 4: //Order by Intelligence
             for (auto i = bestPlayers.begin(); i != bestPlayers.end(); i++) {
                 setBySmart.insert((*i));
             }
             showStatistics(setBySmart, numberOfPlayers);
             break;
         default:
             break;
         }
     }
 }
showTables()
void Casino::showTables (pair< short, short > xy)
Displays casino's tables in a user friendly way on the terminal.
Author
Ineeve
Date
19/11/2016
Parameters
xy The cursor coordinates.
Definition at line 1476 of file Casino.cpp.
References tables.
Referenced by eliminate(), manage(), and selectTable().
{
     system("CLS");
     bool found = false;
     pair <short, short> coordXY;
     coordXY.first = (xy.first % 32) / 2 - 1;
     for (size_t i = 0; i < tables.size(); i++)
     {
         tables.at(i)->showTableInfo(coordXY);
         coordXY.first += 32;
         if (coordXY.first + 32 > xy.first)
         {
             coordXY.first = (xy.first % 32) / 2 - 1;
             coordXY.second += 14;
         }
     }
     cout << endl << endl << endl;
 }
showUsers()
void Casino::showUsers (int n)
Display accounts infos.
Author
Joao Carvalho
Date
30/12/2016
Parameters
n Number of users.
Definition at line 1273 of file Casino.cpp.
References userslogin.
Referenced by eliminate().
{
     system("cls");
     string text, name;
     stringstream sstext;
     int i = 0;
     cout << (char)218; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)191 << endl; //
     cout << (char)179; //
     cout << setw((50 + 13) / 2 + 1) << "Accounts Info" << setw(50 - (50 + 13) / 2 + 1) << (char)179 << endl;
     cout << (char)195; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)180 << endl; //
     cout << (char)179; //
     cout << setw(13) << "username" << setw(21) << "pass" << setw(18) << (char)179 << endl;
     cout << (char)195; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)180 << endl; //
     for (loginHash::iterator it = userslogin.begin(); it != userslogin.end() && i < n; it++)
     {
         i++;
         name = it->first;
         text = it->second;
         cout << setw(5) << " " << name << setw(26-name.length()) << " " << text << endl;
     }
     cout << (char)192; //
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)196; //
     }
     cout << (char)217 << endl; //
 }
Member Data Documentation
bestPlayers
set<Player *, CompareByAverageProfit> Casino::bestPlayers private
Definition at line 438 of file Casino.h.
Referenced by fillBestPlayersSet(), and showStatisticsMenu().
dealers
vector<Dealer*> Casino::dealers private
The dealers.
Definition at line 428 of file Casino.h.
Referenced by addDealerToCasino(), Casino(), create(), findDealer(), manageTables(), readDealersFile(), readTablesFile(), removeDealerFromCasino(), saveDealersFile(), and showDealers().
dealersFile
string Casino::dealersFile private
The dealers file.
Definition at line 418 of file Casino.h.
Referenced by readDealersFile(), saveDealersFile(), and setDealersFile().
players
vector<Player*> Casino::players private
The players.
Definition at line 432 of file Casino.h.
Referenced by addPlayersToCasino(), addPlayerToCasino(), addPlayerToTable(), fillBestPlayersSet(), findPlayer(), manageTables(), readPlayersFile(), readTablesFile(), removePlayerFromCasino(), savePlayersFile(), and showPlayers().
playersFile
string Casino::playersFile private
The players file.
Definition at line 416 of file Casino.h.
Referenced by readPlayersFile(), savePlayersFile(), and setPlayersFile().
tables
vector<Table *> Casino::tables private
The tables.
Definition at line 430 of file Casino.h.
Referenced by addPlayerToTable(), addTableToCasino(), Casino(), findTable(), getTables(), getTableToPlay(), manageTables(), readTablesFile(), removeTableFromCasino(), saveTablesFile(), selectTable(), and showTables().
tablesFile
string Casino::tablesFile private
The tables file.
Definition at line 420 of file Casino.h.
Referenced by readTablesFile(), saveTablesFile(), and setTablesFile().
tableToPlay
int Casino::tableToPlay private
The table to play.
Definition at line 426 of file Casino.h.
Referenced by getTableToPlay(), and setTableToPlay().
totalMoney
unsigned int Casino::totalMoney private
The total money.
Definition at line 424 of file Casino.h.
Referenced by addTableToCasino(), and Casino().
userLOGIN
pair<string, string> Casino::userLOGIN private
The users actual logged.
Definition at line 436 of file Casino.h.
Referenced by getUserLoginName(), and login().
usersFile
string Casino::usersFile private
The users file.
Definition at line 422 of file Casino.h.
Referenced by readLoginFile(), saveLoginFile(), and setUsersFile().
userslogin
loginHash Casino::userslogin private
An unordered_set representing the hash table.
Definition at line 434 of file Casino.h.
Referenced by create(), eliminate(), login(), readLoginFile(), saveLoginFile(), and showUsers().
The documentation for this class was generated from the following files:
Casino.h
Casino.cpp