Aeda-Casino: Bot0 Class Reference
Bot0 Class Reference
Bot of type 0. The most basic bot, always bets the minimum allowed, stands on 17 (or more).
#include <Player.h>
Inherits Player.
Public Member Functions
Bot0 ()
Default constructor.
Bot0 (string name, unsigned int initialMoney)
Constructor.
Bot0 (string &line)
Constructor.
string play (Table &table)
Plays accordingly to an algorithm. Never doubles, always stands on 17 or higher, always hits if less than 17.
bool takeInsurance (Table &table)
Take insurance always returns false on Bot0.
virtual ostream & saveInfo (ostream &out)
Writes Bot0 info to stream.
Public Member Functions inherited from Player
void hit (Card newCard)
Hits the given new card. Saves the card on the hand. Updates the handscore.
void hit2 (Card newCard)
Hits the given new card. Saves the card on the hand2. Updates the hand2score.
virtual bool surrender (Table &table)
Surrenders or not. When this method is called, it will check if the player wants to surrender.
virtual bool split (Dealer *dealerOfTable)
Splits his hand or not. When this method is called it will apply an algorithm depending on the type of player, to check if the player wants to split his hand.
void doubleDown ()
Double down. Doubles down the current bet. When a player doubles down, he will hit a new card, double is bet, and won't be allowed to play anymore until the end of the round.
vector< Card > & getHand ()
Gets the hand.
vector< Card > & getHand2 ()
Gets the second hand.
unsigned int getHandSize () const
Gets hand size.
unsigned int getRoundsPlayed () const
Gets rounds played.
float getCurrentMoney () const
Gets current money.
float getAverageProfit () const
Gets average profit.
unsigned int getHandScore () const
Gets hand score.
unsigned int getHand2Score () const
Gets second hand score.
unsigned int getInitialMoney () const
Gets initial money.
string getName () const
Gets the name.
void setName (string newName)
Sets a name.
unsigned int setHandScore ()
Sets hand score.
unsigned int setHand2Score ()
Sets second hand score.
void setCurrentMoney (float money)
Sets current money.
void setRoundsPlayed (unsigned int rounds)
Sets rounds played.
void setInitialMoney (unsigned int money)
Sets initial money.
void addMoney (float value)
Adds money to the player.
void showStatistics ()
Shows the statistics.
virtual unsigned int bet (Table &table)
Bets an amount of money. If player is a kind of bot, it will bet accordingly to algorithms that are available on the internet.
void clearHand ()
Clears the hand.
void clearHand2 ()
Clears the second hand.
void setActualBet (unsigned int bet)
Sets actual bet.
unsigned int getActualBet ()
Gets actual bet.
virtual int getCurrentCount () const
Gets current count. Different kinds of players may hold different counts.
virtual void addCount (Card &card1)
Updates the current count with a given card.
virtual void resetCount ()
Resets the current count. Should be called when the deck is reshuffled or the table closes.
unsigned int getAge () const
Gets the age.
void setAge (unsigned int age)
Sets an age.
void setOnTable (int tableID)
Sits on a table. -1 if the player is not on any table.
int getOnTable () const
Gets if the player is on table or not.
void removeCardFromFirstHandAndSetItOnSecondHand ()
Removes the card from first hand sets it on the second hand.
virtual void setUserID (unsigned int userID)
Does nothing in class Player. But it is necessary for the human class.
virtual unsigned int getUserID () const
Returns 0;.
Detailed Description
Bot of type 0. The most basic bot, always bets the minimum allowed, stands on 17 (or more).
Author
Joao Carvalho
Date
19/11/2016
Definition at line 841 of file Player.h.
Constructor & Destructor Documentation
Bot0() [1/3]
Bot0::Bot0 () inline
Default constructor.
Author
Joao Carvalho
Date
19/11/2016
Definition at line 853 of file Player.h.
 {};
Bot0() [2/3]
Bot0::Bot0 (string name, unsigned int initialMoney)
Constructor.
Author
Joao Carvalho
Date
19/11/2016
Parameters
name The name.
initialMoney The initial money.
Definition at line 343 of file Player.cpp.
 {
     this->setOnTable(-1);
     this->setName(name);
     this->setInitialMoney(initialMoney);
 }
Bot0() [3/3]
Bot0::Bot0 (string & line)
Constructor.
Author
Joao Carvalho
Date
19/11/2016
Parameters
line Line containes all information.
Definition at line 290 of file Player.cpp.
References Card::rank, Card::score, and Card::suits.
{
     line.erase(0, line.find_first_of("; ") + 2);
     this->setName(line.substr(0, line.find_first_of("; ")));
     line.erase(0, line.find_first_of("; ") + 2);
     this->setInitialMoney(stoi(line.substr(0, line.find_first_of("; "))));
     line.erase(0, line.find_first_of("; ") + 2);
     this->setCurrentMoney(stoi(line.substr(0, line.find_first_of("; "))));
     line.erase(0, line.find_first_of("; ") + 2);
     this->clearHand();
     if (line.at(0) == '{')
     {
         line.erase(0, 1);
         Card newCard;
         while (line.at(0) != '}')
         {
             newCard.rank = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.suits = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.score = stoi(line.substr(0, line.find_first_of("; ")));
             line.erase(0, line.find_first_of("; ") + 2);
             this->hit(newCard);
         }
         line.erase(0, line.find_first_of("; ") + 2);
     }
     this->clearHand2();
     if (line.at(0) == '{')
     {
         line.erase(0, 1);
         Card newCard;
         while (line.at(0) != '}')
         {
             newCard.rank = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.suits = line.substr(0, line.find_first_of("/"));
             line.erase(0, line.find_first_of("/") + 1);
             newCard.score = stoi(line.substr(0, line.find_first_of("; ")));
             line.erase(0, line.find_first_of("; ") + 2);
             this->hit2(newCard);
         }
         line.erase(0, line.find_first_of("; ") + 2);
     }
     this->setRoundsPlayed(stoi(line.substr(0, line.find_first_of("; "))));
     line.erase(0, line.find_first_of("; ") + 2);
     this->setAge(stoi(line.substr(0, line.find_first_of("; "))));
     line.erase(0, line.find_first_of("; ") + 2);
     this->setOnTable(stoi(line.substr(0, line.find_first_of("; "))));
     line.erase(0, line.find_first_of("; ") + 2);
     this->setActualBet(stoi(line.substr(0, line.find_first_of("; "))));
     line.erase(0, line.find_first_of("; ") + 2);
 }
Member Function Documentation
play()
string Bot0::play (Table & table) virtual
Plays accordingly to an algorithm. Never doubles, always stands on 17 or higher, always hits if less than 17.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
A string, "hit" or "stand".
Implements Player.
Definition at line 360 of file Player.cpp.
References Dealer::discard(), Table::getDealer(), and Table::getPlayers().
 {
     string options[] = { "hit","stand" };
     unsigned int handScore = getHandScore();
     if (handScore < 17) {
         hit(table.getDealer()->discard(table.getPlayers()));
         return options[0]; // 0 means hit
     }
     return options[1]; // means stand
 }
saveInfo()
ostream & Bot0::saveInfo (ostream & out) virtual
Writes Bot0 info to stream.
Parameters
[in,out] out ostream in which Bot0 info will be saved.
Returns
Bot0 info in a ostream.
Author
Joao Carvalho
Date
19/11/2016
Reimplemented from Player.
Definition at line 354 of file Player.cpp.
References Player::saveInfo().
{
     out << "0; ";
     Player::saveInfo(out);
     return out;
 }
takeInsurance()
bool Bot0::takeInsurance (Table & table) virtual
Take insurance always returns false on Bot0.
Author
Joao Carvalho
Date
19/11/2016
Parameters
[in,out] table The table.
Returns
False.
Reimplemented from Player.
Definition at line 350 of file Player.cpp.
{
     return false;
 }
The documentation for this class was generated from the following files:
Player.h
Player.cpp