Aeda-Casino: cmdUI.cpp File Reference
cmdUI.cpp File Reference
#include "cmdUI.h"
Functions
void clearScreen ()
Clears the terminal.
void cursorxy (short x, short y)
Set cursor on <x,y> coordinates.
void displayMenu0 (pair< int, int > xy, string title, vector< string > menuOptions)
pair< int, int > centerWindow ()
Center the terminal window. The returned length is measured in characters.
void drawTitle (pair< short, short > xy)
Displays the title.
void start_menu (pair< short, short > xy, int &choice)
Displays the main menu.
void manageCasino (pair< short, short > xy, unsigned int &choice)
Displays the manage casino menu and reads user choice.
void createMenu (pair< short, short > xy, unsigned int &choice)
Creates a menu.
void deleteMenu (pair< short, short > xy, unsigned int &choice)
Displays a delete menu and reads user choice.
void manageTableMenu (pair< short, short > xy, unsigned int &choice)
Displays the manage table menu and reads user choice.
void statisticsMenu (pair< short, short > xy, unsigned int &choice)
Displays the statistics menu and reads user choice.
Function Documentation
centerWindow()
pair< int, int > centerWindow ()
Center the terminal window. The returned length is measured in characters.
Author
Ineeve
Date
19/11/2016
Returns
A pair <x,y>. x= terminal horizontal length, y = terminal vertical length.
Definition at line 48 of file cmdUI.cpp.
Referenced by main().
{
 #ifdef _WIN32
         HWND hwnd = GetConsoleWindow();
         RECT desktop;
         const HWND hDesktop = GetDesktopWindow();
         GetWindowRect(hDesktop, &desktop);
         MoveWindow(hwnd, desktop.right * 0.175, desktop.bottom * 0.2, desktop.right * 0.65, desktop.bottom * 0.6, TRUE);
         HANDLE screen = GetStdHandle(STD_OUTPUT_HANDLE);
         COORD max_size = GetLargestConsoleWindowSize(screen);
         int console_x = max_size.X*desktop.right*0.65 / desktop.right - 1;
         int console_y = max_size.Y*desktop.bottom*0.6 / desktop.bottom - 1;
         if (console_x < 56)
         {
             console_x = max_size.X*desktop.right*0.9 / desktop.right + 3;
             console_y = max_size.Y*desktop.bottom*0.9 / desktop.bottom - 1;
             MoveWindow(hwnd, desktop.right * 0.025, desktop.bottom * 0.025, desktop.right * 0.95, desktop.bottom * 0.9, TRUE);
         }
         else if (console_y <= 15)
         {
             console_y = max_size.Y*desktop.bottom*0.9 / desktop.bottom - 1;
             MoveWindow(hwnd, desktop.right * 0.2, desktop.bottom * 0.1, desktop.right * 0.6, desktop.bottom * 0.8, TRUE);
         }
         /*PCONSOLE_FONT_INFOEX cmd_font;
         GetCurrentConsoleFontEx(GetStdHandle(STD_OUTPUT_HANDLE), false, cmd_font);
         cout << cmd_font->FaceName << endl;
         system("pause");*/
         pair <int, int> xy = { console_x,console_y };
         return xy;
 #else
     pair <int, int> xy = {-1,-1};
     return xy;
 #endif
 }
clearScreen()
void clearScreen ()
Clears the terminal.
Author
Ineeve
Date
19/11/2016
Definition at line 6 of file cmdUI.cpp.
Referenced by Table::showPlay().
                    {
     system("CLS");
 }
createMenu()
void createMenu (pair< short, short > xy, unsigned int & choice)
Creates a menu.
Author
Ineeve
Date
19/11/2016
Parameters
xy A pair containing the horizontal and vertical lengths of the terminal.
[in,out] choice The user choice.
Definition at line 140 of file cmdUI.cpp.
References displayMenu0(), and readIntBetween().
Referenced by Casino::create().
{
     vector <string> options = { "-. Create ..." ,"  1. Table" ,"  2. Dealer", "  3. Player (BOT)", "  4. Account", "-. Delete...", "-. Manage Tables", "-. Stats" , "" ,"0. Back" };
     system("CLS");
     displayMenu0(xy, "1. Create ...", options);
     choice = readIntBetween(0, 4);
 }
cursorxy()
void cursorxy (short x, short y)
Set cursor on <x,y> coordinates.
Author
Ineeve
Date
19/11/2016
Parameters
x The x coordinate.
y The y coordinate.
Definition at line 10 of file cmdUI.cpp.
Referenced by Casino::create(), Casino::login(), Table::play(), Table::showPlay(), Table::showTableInfo(), and start_menu().
{
 #ifdef _WIN32
         COORD p = { x, y };
         SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE), p);
 #endif
 }
deleteMenu()
void deleteMenu (pair< short, short > xy, unsigned int & choice)
Displays a delete menu and reads user choice.
Author
Ineeve
Date
19/11/2016
Parameters
xy A pair containing the horizontal and vertical lengths of the terminal.
[in,out] choice The user choice.
Definition at line 147 of file cmdUI.cpp.
References displayMenu0(), and readIntBetween().
Referenced by Casino::eliminate().
{
     vector <string> options = { "-. Create ..." , "-. Delete...", "  1. Table" ,"  2. Dealer", "  3. Player (BOT)", "  4. Account", "-. Manage Tables", "-. Stats" ,"" , "0. Back" };
     system("CLS");
     displayMenu0(xy, "2. Delete ...", options);
     choice = readIntBetween(0, 4);
 }
displayMenu0()
void displayMenu0 (pair< int, int > xy, string title, vector< string > menuOptions)
Definition at line 17 of file cmdUI.cpp.
Referenced by createMenu(), deleteMenu(), manageCasino(), manageTableMenu(), start_menu(), and statisticsMenu().
{
     string text;
     cout << setw((xy.first - 36) / 2 - 1) << (char)201; //‚ïî
     for (unsigned int i = 0; i <= 36; i++)
     {
         cout << (char)205; //‚ïê
     }
     cout << (char)187 << endl; //‚ïó
     text = title;
     cout << setw((xy.first - 36) / 2 - 1) << (char)186 //‚ïë
         << setw((38 + text.length()) / 2) << text
         << setw(38 - (38 + text.length()) / 2) << (char)186 << endl; //‚ïë
     cout << setw((xy.first - 36) / 2 - 1) << (char)204; //‚ï†
     for (unsigned int i = 0; i <= 36; i++)
     {
         cout << (char)205; //‚ïê
     }
     cout << (char)185 /*‚ï£*/ << endl;
     for (size_t i = 0; i < menuOptions.size(); i++)
     {
         text = menuOptions.at(i);
         cout << setw((xy.first - 36) / 2 - 1) << (char)186 << setw(7) << " " << text << setw(38 - (7 + text.length())) << (char)186 << endl;
     }
     cout << setw((xy.first - 36) / 2 - 1) << (char)200;
     for (unsigned int i = 0; i <= 36; i++)
     {
         cout << (char)205;
     }
     cout << (char)188 << endl << endl;
 }
drawTitle()
void drawTitle (pair< short, short > xy)
Displays the title.
Author
Jo„o Carvalho
Date
26/12/2016
Parameters
xy A pair containing the horizontal and vertical lengths of the terminal.
Definition at line 85 of file cmdUI.cpp.
Referenced by Casino::login(), and start_menu().
{
     cout << endl << endl;
     if (xy.first >= 78)
     {
         cout << setw((xy.first - 78) / 2 - 1) << " " << " _______    _        __      _____  _    _    _____     __     _____  _    _  " << endl
             << setw((xy.first - 78) / 2 - 1) << " " << "/_____  |  | |      /  \\    /  __/ | \\  / /  |___  |   /  \\   /  __/ | \\  / / " << endl
             << setw((xy.first - 78) / 2 - 1) << " " << "  | | | |  | |     /    \\   | |    | | / /       | |  /    \\  | |    | | / /  " << endl
             << setw((xy.first - 78) / 2 - 1) << " " << "  | |_| |  | |    |  /\\  |  | |    | |/ /        | | |  /\\  | | |    | |/ /   " << endl
             << setw((xy.first - 78) / 2 - 1) << " " << "  |  __  | | |    | |__| |  | |    |    |    _   | | | |__| | | |    |    |   " << endl
             << setw((xy.first - 78) / 2 - 1) << " " << "  | |  | | | |    |  __  |  | |    | |\\ \\   | |  | | |  __  | | |    | |\\ \\   " << endl
             << setw((xy.first - 78) / 2 - 1) << " " << "  | |__| | | \\__  | |  | |  | |__  | | \\ \\  | |__| | | |  | | | |__  | | \\ \\  " << endl
             << setw((xy.first - 78) / 2 - 1) << " " << "  |______|  \\___/ |_|  |_|  \\____\\ |_/  \\_\\ |______| |_|  |_| \\____\\ |_/  \\_\\ " << endl;
     }
     else
     {
         cout << setw((xy.first - 44) / 2) << (char)218 << (char)196 << (char)196 << (char)196 << (char)196 << (char)191 << (char)218 << (char)191 << " " << (char)218 << (char)196 << (char)196 << (char)196 << (char)191 << (char)218 << (char)196 << (char)196 << (char)196 << (char)191 << (char)218 << (char)191 << "     " << (char)218 << (char)191 << (char)218 << (char)196 << (char)196 << (char)196 << (char)191 << (char)218 << (char)196 << (char)196 << (char)196 << (char)191 << (char)218 << (char)191 << endl
             << setw((xy.first - 44) / 2) << (char)192 << (char)191 << (char)218 << (char)196 << (char)191 << (char)179 << (char)179 << (char)179 << " " << (char)179 << (char)218 << (char)196 << (char)191 << (char)179 << (char)179 << (char)218 << (char)196 << (char)196 << (char)217 << (char)179 << (char)179 << (char)218 << (char)191 << "   " << (char)179 << (char)179 << (char)179 << (char)218 << (char)196 << (char)191 << (char)179 << (char)179 << (char)218 << (char)196 << (char)196 << (char)217 << (char)179 << (char)179 << (char)218 << (char)191 << endl
             << setw((xy.first - 44) / 2) << " " << (char)179 << (char)192 << (char)196 << (char)217 << (char)179 << (char)179 << (char)179 << " " << (char)179 << (char)192 << (char)196 << (char)217 << (char)179 << (char)179 << (char)179 << "   " << (char)179 << (char)192 << (char)217 << (char)192 << (char)191 << "  " << (char)179 << (char)179 << (char)179 << (char)192 << (char)196 << (char)217 << (char)179 << (char)179 << (char)179 << "   " << (char)179 << (char)192 << (char)217 << (char)192 << (char)191 << endl
             << setw((xy.first - 44) / 2) << " " << (char)179 << (char)218 << (char)196 << (char)191 << (char)179 << (char)179 << (char)179 << " " << (char)179 << (char)218 << (char)196 << (char)191 << (char)179 << (char)179 << (char)179 << "   " << (char)179 << (char)218 << (char)196 << (char)191 << (char)179 << (char)218 << (char)191 << (char)179 << (char)179 << (char)179 << (char)218 << (char)196 << (char)191 << (char)179 << (char)179 << (char)179 << "   " << (char)179 << (char)218 << (char)196 << (char)191 << (char)179 << endl
             << setw((xy.first - 44) / 2) << (char)218 << (char)217 << (char)192 << (char)196 << (char)217 << (char)179 << (char)179 << (char)192 << (char)191 << (char)179 << (char)179 << " " << (char)179 << (char)179 << (char)179 << (char)192 << (char)196 << (char)196 << (char)191 << (char)179 << (char)179 << " " << (char)179 << (char)179 << (char)179 << (char)192 << (char)217 << (char)179 << (char)179 << (char)179 << " " << (char)179 << (char)179 << (char)179 << (char)192 << (char)196 << (char)196 << (char)191 << (char)179 << (char)179 << " " << (char)179 << (char)179 << endl
             << setw((xy.first - 44) / 2) << (char)192 << (char)196 << (char)196 << (char)196 << (char)196 << (char)217 << (char)192 << (char)196 << (char)217 << (char)192 << (char)217 << " " << (char)192 << (char)217 << (char)192 << (char)196 << (char)196 << (char)196 << (char)217 << (char)192 << (char)217 << " " << (char)192 << (char)217 << (char)192 << (char)196 << (char)196 << (char)217 << (char)192 << (char)217 << " " << (char)192 << (char)217 << (char)192 << (char)196 << (char)196 << (char)196 << (char)217 << (char)192 << (char)217 << " " << (char)192 << (char)217 << endl;
     }
     cout << endl << endl;
 }
manageCasino()
void manageCasino (pair< short, short > xy, unsigned int & choice)
Displays the manage casino menu and reads user choice.
Author
Ineeve
Date
19/11/2016
Parameters
xy A pair containing the horizontal and vertical lengths of the terminal.
[in,out] choice The user choice.
Definition at line 133 of file cmdUI.cpp.
References displayMenu0(), and readIntBetween().
Referenced by Casino::manage().
{
     vector <string> options = {"1. Create ..." ,"2. Delete...", "3. Manage Tables", "4. Best Platers" , "" , "0. Return to MENU" };
     system("CLS");
     displayMenu0(xy, "MANAGE CASINO", options);
     choice = readIntBetween(0, 4);
 }
manageTableMenu()
void manageTableMenu (pair< short, short > xy, unsigned int & choice)
Displays the manage table menu and reads user choice.
Author
Ineeve
Date
19/11/2016
Parameters
xy A pair containing the horizontal and vertical lengths of the terminal.
[in,out] choice The user choice.
Definition at line 154 of file cmdUI.cpp.
References displayMenu0(), and readIntBetween().
Referenced by Casino::manageTables().
{
     vector <string> options = { "-. Create ..." , "-. Delete...", "-. Manage Tables","  1. Set dealer", "  2. Add Player", "  3. Remove Player" , "-. Stats" ,"" , "0. Back" };
     system("CLS");
     displayMenu0(xy, "3. Manage Tables ...", options);
     choice = readIntBetween(0, 3);
 }
start_menu()
void start_menu (pair< short, short > xy, int & choice)
Displays the main menu.
Author
Ineeve
Date
19/11/2016
Parameters
xy A pair containing the horizontal and vertical lengths of the terminal.
[in,out] choice The user choice.
Definition at line 110 of file cmdUI.cpp.
References cursorxy(), displayMenu0(), drawTitle(), and readIntBetween().
Referenced by main().
{
     //display author rights
     system("CLS");
     cursorxy((xy.first - 50) / 2 - 2, xy.second - 2);
     cout << (char)201; //‚ïî
     for (unsigned int i = 0; i <= 50; i++)
     {
         cout << (char)205; //‚ïê
     }
     cout << (char)187 << endl; //‚ïó
     cout << setw((xy.first - 50) / 2 - 1) << (char)186 /*‚ïë*/ << setw((50 - 31) / 2) << " " << "BlackJack " << (char)184 << " Console Application" << setw(12) << (char)186 /*‚ïë*/ << endl;
     cout << setw((xy.first - 50) / 2 - 1) << (char)186 /*‚ïë*/ << setw((50 + 43) / 2) << "AEDA 2016/2017 Grupo D, All Rights Reserved" << setw(6) << (char)186 /*‚ïë*/ << endl;
     cursorxy(0, 0);
     //draw of title (different draw if screen is small)
     drawTitle(xy);
     //display menu
     vector <string> options = {"1. Play" ,"2. Simulation", "3. Choose Table", "4. Manage Casino", "" ,"0. EXIT"};
     displayMenu0(xy, "MENU", options);
     choice = readIntBetween(0, 4);
 }
statisticsMenu()
void statisticsMenu (pair< short, short > xy, unsigned int & choice)
Displays the statistics menu and reads user choice.
Author
Ineeve
Date
30/12/2016
Parameters
xy A pair containing the horizontal and vertical lengths of the terminal.
[in,out] choice The user choice.
Definition at line 161 of file cmdUI.cpp.
References displayMenu0(), and readIntBetween().
Referenced by Casino::showStatisticsMenu().
{
     vector <string> options = { "1. Order By Average Profit", "2. Order By Age", "3. Order By Name" , "4. Order By Intelligence", "0. Back" };
     system("CLS");
     displayMenu0(xy, "4. Statistics Menu", options);
     choice = readIntBetween(0, 4);
 }