var hierarchy =
[
    [ "Card", "struct_card.html", null ],
    [ "Casino", "class_casino.html", null ],
    [ "CompareByAge", "struct_compare_by_age.html", null ],
    [ "CompareByAverageProfit", "struct_compare_by_average_profit.html", null ],
    [ "CompareByIntelligence", "struct_compare_by_intelligence.html", null ],
    [ "CompareByName", "struct_compare_by_name.html", null ],
    [ "Dealer", "class_dealer.html", null ],
    [ "DealerAlreadyExistException", "class_dealer_already_exist_exception.html", null ],
    [ "DealerIsOnTableAlreadyException", "class_dealer_is_on_table_already_exception.html", null ],
    [ "DealerNotExistException", "class_dealer_not_exist_exception.html", null ],
    [ "dealersComparison", "structdealers_comparison.html", null ],
    [ "DealerStillOnTableException", "class_dealer_still_on_table_exception.html", null ],
    [ "ExistingTableException", "class_existing_table_exception.html", null ],
    [ "HumanOnTableException", "class_human_on_table_exception.html", null ],
    [ "NameTooShortException", "class_name_too_short_exception.html", null ],
    [ "NoPlayersOnTableException", "class_no_players_on_table_exception.html", null ],
    [ "Player", "class_player.html", [
      [ "Bot0", "class_bot0.html", null ],
      [ "Bot1", "class_bot1.html", null ],
      [ "Bot2", "class_bot2.html", null ],
      [ "Human", "class_human.html", null ]
    ] ],
    [ "PlayerAlreadyExistException", "class_player_already_exist_exception.html", null ],
    [ "PlayerIsntOnTableException", "class_player_isnt_on_table_exception.html", null ],
    [ "PlayerNotExistException", "class_player_not_exist_exception.html", null ],
    [ "PlayerNotLoggedException", "class_player_not_logged_exception.html", null ],
    [ "PlayerStillOnTableException", "class_player_still_on_table_exception.html", null ],
    [ "Table", "class_table.html", null ],
    [ "TableNotInCasinoException", "class_table_not_in_casino_exception.html", null ],
    [ "TooManyPlayersException", "class_too_many_players_exception.html", null ],
    [ "TooYoungException", "class_too_young_exception.html", null ],
    [ "userLoginHash", "structuser_login_hash.html", null ]
];