Aeda-Casino: Card Struct Reference
Card Struct Reference
A card.
#include <utils.h>
Public Member Functions
bool operator== (const Card &a) const
Equality operator.
bool operator== (const string &a) const
Equality operator.
ostream & operator<< (ostream &out)
Public Attributes
string rank
The rank.
string suits
The suits.
unsigned int score
The score.
Detailed Description
A card.
Author
Renato Campos
Date
19/11/2016
Definition at line 28 of file utils.h.
Member Function Documentation
operator<<()
ostream& Card::operator<< (ostream & out) inline
Definition at line 71 of file utils.h.
References BinaryInt(), createDeck(), FileCopy(), FileExist(), getHumanPlay(), operator<<(), readBinary(), readCharYorN(), readFloat(), readInt(), readIntBetween(), readNameOfFile(), readUnsignedInt(), readUnsignedIntBetween(), saveChanges(), Users(), and waitXTime().
{
         out << this->rank;
         if (this->suits == "Heart")
         {
             out << (char)3;
         }
         if (this->suits == "Diamond")
         {
             out << (char)4;
         }
         if (this->suits == "Club")
         {
             out << (char)5;
         }
         if (this->suits == "Spade")
         {
             out << (char)6;
         }
         return out;
     }
operator==() [1/2]
bool Card::operator== (const Card & a) const inline
Equality operator.
Author
Renato Campos
Date
19/11/2016
Parameters
a The Card to process.
Returns
True if the parameters are considered equivalent.
Definition at line 49 of file utils.h.
References rank.
     {
         return (this->rank == a.rank);
     }
operator==() [2/2]
bool Card::operator== (const string & a) const inline
Equality operator.
Author
Renato Campos
Date
19/11/2016
Parameters
a The rank to process.
Returns
True if the parameters are considered equivalent.
Definition at line 67 of file utils.h.
     {
         return (this->rank == a);
     }
Member Data Documentation
rank
string Card::rank
The rank.
Definition at line 30 of file utils.h.
Referenced by Bot0::Bot0(), Bot1::Bot1(), Bot2::Bot2(), createDeck(), Human::Human(), operator<<(), and operator==().
score
unsigned int Card::score
The score.
Definition at line 34 of file utils.h.
Referenced by Bot1::addCount(), Bot2::addCount(), Bot0::Bot0(), Bot1::Bot1(), Bot2::Bot2(), createDeck(), Human::Human(), Bot1::play(), and Bot1::split().
suits
string Card::suits
The suits.
Definition at line 32 of file utils.h.
Referenced by Bot0::Bot0(), Bot1::Bot1(), Bot2::Bot2(), createDeck(), Human::Human(), and operator<<().
The documentation for this struct was generated from the following file:
utils.h