Aeda-Casino: utils.cpp File Reference
utils.cpp File Reference
#include "utils.h"
Functions
std::ostream & operator<< (std::ostream &out, const Card &c)
Stream insertion operator. Makes the display of a card on the terminal.
std::ostream & operator<< (std::ostream &out, const vector< Card > &v)
Stream insertion operator.
vector< Card > createDeck ()
Creates the deck.
string getHumanPlay ()
Gets human play.
unsigned short int readUnsignedIntBetween (unsigned int minValue, unsigned int maxValue)
Reads unsigned int between a minimum and a maximum values. Ask for user input.
int readIntBetween (int min, int max)
Reads int between a minimum and a maximum values. Ask for user input.
unsigned int readUnsignedInt ()
Reads unsigned int. Asks for user input.
int readInt ()
Reads a int value. Asks for user input.
int readBinary ()
Reads a 0 or a 1 from user input.
float readFloat ()
Reads a float from user input.
char readCharYorN ()
Reads character "y" or "n". Case insensitive.
void Users (vector< int > &usersVEC, int &user)
Reads and parses the users file to usersVec.
void FileCopy (string filetxt, string filetxt_temp)
Copies text between files.
bool FileExist (string filetxt_temp)
Checks if the file with name filetxt_temp exists.
int BinaryInt (int id, vector< int > VEC)
Performs a binary search of id in VEC.
int saveChanges (vector< int > &usersVEC, int &user, pair< int, int > xy, int &save)
Asks user to save the current status when exiting.
int readNameOfFile (string &fileName)
Ask user to input a file name.
void waitXTime (unsigned int time)
Sleeps for a given time.
Function Documentation
BinaryInt()
int BinaryInt (int id, vector< int > VEC)
Performs a binary search of id in VEC.
Author
Renato Campos
Date
19/11/2016
Parameters
id The identifier.
VEC The vector.
Returns
The index of id in Vec, or -1 if id was not found.
Definition at line 255 of file utils.cpp.
Referenced by Card::operator<<(), and saveChanges().
{
     int lowindex = 0;
     int highindex = VEC.size() - 1;
     int i = -1;
     while (lowindex <= highindex)
     {
         i = (highindex + lowindex) / 2;
         if (id == VEC.at(i))
         {
             return i;
         }
         else if (id < VEC.at(i))
         {
             highindex = i - 1;
         }
         else if (id > VEC.at(i))
         {
             lowindex = i + 1;
         }
     }
     return -1;
 }
createDeck()
vector< Card > createDeck ()
Creates the deck.
Author
Renato Campos
Date
19/11/2016
Returns
The new deck.
Definition at line 15 of file utils.cpp.
References Card::rank, Card::score, and Card::suits.
Referenced by Dealer::Dealer(), and Card::operator<<().
{
     vector <string> suits = {"Heart" ,"Diamond" ,"Club" ,"Spade"};
     string ranks = "A234567890JQK";
     Card newCard;
     vector <Card> deck;
     for (unsigned int i = 0; i < ranks.length(); i++)
     {
         for (size_t j = 0; j < suits.size(); j++)
         {
             if (i == 0)
             {
                 newCard.suits = suits.at(j);
                 newCard.rank = ranks.at(i);
                 newCard.score = 11;
             }
             else if (i < 9)
             {
                 newCard.suits = suits.at(j);
                 newCard.rank = ranks.at(i);
                 newCard.score = i + 1;
             }
             else if (i == 9)
             {
                 newCard.suits = suits.at(j);
                 newCard.rank = "10";
                 newCard.score = i + 1;
             }
             else if (i >= 1)
             {
                 newCard.suits = suits.at(j);
                 newCard.rank = ranks.at(i);
                 newCard.score = 10;
             }
             deck.push_back(newCard);
         }
     }
     return deck;
 }
FileCopy()
void FileCopy (string filetxt, string filetxt_temp)
Copies text between files.
Author
Renato Campos
Date
19/11/2016
Parameters
filetxt The file name;
filetxt_temp The temporary file name;
Definition at line 227 of file utils.cpp.
Referenced by Card::operator<<().
{
     ofstream File(filetxt);
     ifstream File_temp(filetxt_temp);
     string line;
     if (File.is_open() && File_temp.is_open())
     {
         while (getline(File_temp, line))
         {
             File << line << endl;
         }
         File.close();
         File_temp.close();
     }
 }
FileExist()
bool FileExist (string filetxt_temp)
Checks if the file with name filetxt_temp exists.
Author
Renato Campos
Date
19/11/2016
Parameters
filetxt_temp The temporary file name;
Returns
True if it exists, false otherwise.
Definition at line 242 of file utils.cpp.
Referenced by Card::operator<<(), and Table::play().
{
     ifstream file(filetxt_temp);
     if (file.is_open())
     {
         file.close();
         return true;
     }
     else
     {
         return false;
     }
 }
getHumanPlay()
string getHumanPlay ()
Gets human play.
Author
Renato Campos
Date
19/11/2016
Returns
The human play.
Definition at line 55 of file utils.cpp.
Referenced by Card::operator<<(), and Human::play().
 {
     string option;
     getline(cin, option);
     while (option != "hit" && option != "stand" && option != "HIT" && option != "STAND" && option != "Hit" && option != "Stand" && option != "EXIT" && option != "Exit" && option != "exit") {
         cout << "Please insert a valid entry: ";
         getline(cin, option);
     }
     if (option == "HIT" || option == "Hit") {
         option = "hit";
     }
     else if (option == "Stand" || option == "STAND") {
         option = "stand";
     }
     else if (option == "Exit" || option == "EXIT")
     {
         option = "exit";
     }
     return option;
 }
operator<<() [1/2]
std::ostream & operator<< (std::ostream & out, const Card & c)
Stream insertion operator. Makes the display of a card on the terminal.
Author
Renato Campos
Date
19/11/2016
Parameters
[in,out] out The outstream.
c The Card to process.
Returns
The ostream produced.
Definition at line 6 of file utils.cpp.
References Card::rank, and Card::suits.
Referenced by Card::operator<<().
{
     return out << c.rank << c.suits;
 }
operator<<() [2/2]
std::ostream & operator<< (std::ostream & out, const vector< Card > & v)
Stream insertion operator.
Author
Renato Campos
Date
19/11/2016
Parameters
[in,out] out The outstream.
v The vector of cards to process.
Returns
The ostream produced.
Definition at line 9 of file utils.cpp.
{
     for (size_t i = 0; i < v.size(); i++) {
         out << v.at(i) << " ; ";
     }
     return out << "\n";
 }
readBinary()
int readBinary ()
Reads a 0 or a 1 from user input.
Author
Renato Campos
Date
19/11/2016
Returns
The user input.
Definition at line 133 of file utils.cpp.
Referenced by Card::operator<<(), Human::split(), and Human::takeInsurance().
                 {
     int value;
     cin >> value;
     while (value != 0 || value != 1){
         cout << endl;
         cin.clear();
         cin.ignore();
         cout << "Valor inválido, insira 0 ou 1: ";
     }
     cin.ignore();
     cout << endl;
     return value;
 }
readCharYorN()
char readCharYorN ()
Reads character "y" or "n". Case insensitive.
Author
Renato Campos
Date
19/11/2016
Returns
The character inserted by the user: "y" or "n".
Definition at line 161 of file utils.cpp.
Referenced by Card::operator<<(), and Table::play().
                     {
     char newChar;
     cout << "Insira o caracter: ";
     while (!(cin >> newChar) || (newChar != 'n' && newChar != 'N' && newChar != 'Y' && newChar != 'y')) {
         cout << endl;
         cin.clear();
         cin.ignore();
         cout << "Caracter invalido, insira um novo caracter: ";
     }
     cin.ignore();
     cout << endl;
     return newChar;
 }
readFloat()
float readFloat ()
Reads a float from user input.
Author
Renato Campos
Date
19/11/2016
Returns
The float inputed by the user.
Definition at line 148 of file utils.cpp.
Referenced by Card::operator<<().
                   {
     float newFloat;
     cout << "Insira um novo valor: ";
     while (!(cin >> newFloat)) {
         cout << endl;
         cin.clear();
         cin.ignore();
         cout << "Valor invalido, insira um novo valor: ";
     }
     cin.ignore();
     cout << endl;
     return newFloat;
 }
readInt()
int readInt ()
Reads a int value. Asks for user input.
Author
Renato Campos
Date
19/11/2016
Returns
The int inserted by the user.
Definition at line 119 of file utils.cpp.
Referenced by Card::operator<<(), and Casino::selectTable().
               {
     int newInt;
     cout << "Insira um valor: ";
     while (!(cin >> newInt)) {
         cout << endl;
         cin.clear();
         cin.ignore();
         cout << "Valor inválido, insira um novo valor unsigned int: ";
     }
     cin.ignore();
     cout << endl;
     return newInt;
 }
readIntBetween()
int readIntBetween (int min, int max)
Reads int between a minimum and a maximum values. Ask for user input.
Author
Renato Campos
Date
19/11/2016
Parameters
min The minimum.
max The maximum.
Returns
The int between the parameters set.
Definition at line 91 of file utils.cpp.
Referenced by createMenu(), deleteMenu(), manageCasino(), manageTableMenu(), Card::operator<<(), and start_menu().
{
     int newInt;
     cout << "Insert a value: ";
     while(!(cin >> newInt) || newInt > max || newInt < min) {
         cout << endl;
         cin.clear();
         cin.ignore();
         cout << "Wrong value, value between " << min << " - " << max;
     }
     cin.ignore();
     cout << endl;
     return newInt;
 }
readNameOfFile()
int readNameOfFile (string & fileName)
Ask user to input a file name.
Author
Renato Campos
Date
19/11/2016
Parameters
[in,out] fileName A string that will be updated with the user input.
Returns
0 in case of success.
Definition at line 338 of file utils.cpp.
Referenced by Card::operator<<().
{
     cout << "Name of File?" << endl;
     cin >> fileName;
     while (fileName.find(".txt") != fileName.length() - 4)
     {
         cout << "Write name of file again" << endl;
         cin >> fileName;
     }
     return 0;
 }
readUnsignedInt()
unsigned int readUnsignedInt ()
Reads unsigned int. Asks for user input.
Author
Renato Campos
Date
19/11/2016
Returns
The unsigned int.
Definition at line 105 of file utils.cpp.
Referenced by Casino::create(), Casino::eliminate(), main(), Casino::manage(), Casino::manageTables(), and Card::operator<<().
{
     unsigned int newUnsignedInt;
     cout << "Insira um valor: ";
     while (!(cin >> newUnsignedInt)) {
         cout << endl;
         cin.clear();
         cin.ignore();
         cout << "Valor inválido, insira um novo valor unsigned int: ";
     }
     cin.ignore();
     cout << endl;
     return newUnsignedInt;
 }
readUnsignedIntBetween()
unsigned short int readUnsignedIntBetween (unsigned int minValue, unsigned int maxValue)
Reads unsigned int between a minimum and a maximum values. Ask for user input.
Author
Renato Campos
Date
19/11/2016
Parameters
minValue The minimum value.
maxValue The maximum value.
Returns
A unsigned int between the parameters set.
Definition at line 76 of file utils.cpp.
Referenced by Human::bet(), Casino::create(), Card::operator<<(), and Table::play().
{
     unsigned int short newInt;
     cout << "Insert Value ( " << minValue << " - " << maxValue << " ) : ";
     while (!(cin >> newInt) || newInt > maxValue || newInt < minValue) {
         cout << endl;
         cin.clear();
         cin.ignore();
         cout << "Invalid Value: Insert a new one: ";
     }
     cin.ignore();
     cout << endl;
     return newInt;
 }
saveChanges()
int saveChanges (vector< int > & usersVEC, int & user, pair< int, int > xy, int & save)
Asks user to save the current status when exiting.
Author
Renato Campos
Date
19/11/2016
Parameters
[in,out] usersVEC The users vector.
[in,out] user The user id.
xy Pair with horizontal and vertical lengths of the terminal.
[in,out] save Boolean that holds user option to save or not the changes made.
Returns
0 in case of operation success.
Definition at line 278 of file utils.cpp.
References BinaryInt(), and Users().
Referenced by main(), and Card::operator<<().
{
     char decision;
     Users(usersVEC, user);
     if (usersVEC.size() == 1)
     {
         system("cls");
         cout << setw((xy.first - 50) / 2) << (char)201;
         for (int i = 0; i < 50; i++)
         {
             cout << (char)205;
         }
         cout << (char)187 << endl;
         cout << setw((xy.first - 50) / 2) << (char)186 << setw(51) << (char)186 << endl;
         string text = "Do you want save all changes?";
         cout << setw((xy.first - 50) / 2) << (char)186 << setw((50 + text.length()) / 2) << text << setw(51 - (50 + text.length()) / 2) << (char)186 << endl;
         cout << setw((xy.first - 50) / 2) << (char)186 << setw(51) << (char)186 << endl;
         cout << setw((xy.first - 50) / 2) << (char)200;
         for (int i = 0; i < 50; i++)
         {
             cout << (char)205;
         }
         cout << (char)188 << endl;
         cout << endl << "Yes 'Y' or No 'N': ";
         cin >> decision;
         while (!(decision == 'Y' || decision == 'y' || decision == 'N' || decision == 'n'))
         {
             cout << endl << "Yes 'Y' or No 'N': ";
             cin >> decision;
         }
         //alteracao
         if (decision == 'Y' || decision == 'y')
         {
             remove("users_temp.txt");
             save = 1;
         }
         else if (decision == 'N' || decision == 'n')
         {
             remove("users_temp.txt");//delete file temp
             save = 0;
         }
     }
     else
     {
         //elimina usuario no vetor
         usersVEC.erase(usersVEC.begin() + BinaryInt(user, usersVEC));
         ofstream UserFileO("users_temp.txt");
         if (UserFileO.is_open())
         {
             for (unsigned int i = 0; i < usersVEC.size(); i++)
             {
                 UserFileO << usersVEC.at(i) << endl;
             }
             UserFileO.close();
         }
     }
     return 0;
 }
Users()
void Users (vector< int > & usersVEC, int & user)
Reads and parses the users file to usersVec.
Author
Renato Campos
Date
19/11/2016
Parameters
[in,out] usersVEC The users vector.
[in,out] user The user id.
Definition at line 177 of file utils.cpp.
Referenced by main(), Card::operator<<(), and saveChanges().
{
     string line;
     ifstream UserFileI("users_temp.txt");
     int find = 0;
     if (UserFileI.is_open())
     {
         usersVEC.clear();
         while (getline(UserFileI, line)) //enquanto houver linhas no ficheiro
         {
             usersVEC.push_back(stoi(line, nullptr, 10));
         }
         UserFileI.close();
         for (unsigned int i = 0; i < usersVEC.size(); i++)
         {
             if (user == usersVEC.at(i))
             {
                 find = 1;
             }
         }
         if (find == 0)
         {
             if (usersVEC.size() != 0)
             {
                 usersVEC.push_back(usersVEC.back() + 1);
                 user = usersVEC.back();
             }
             else
             {
                 usersVEC.push_back(1);
                 user = usersVEC.back();
             }
         }
     }
     else
     {
         usersVEC.push_back(1);
         user = usersVEC.back();
     }
     ofstream UserFileO("users_temp.txt");
     if (UserFileO.is_open())
     {
         for (unsigned int i = 0; i < usersVEC.size(); i++)
         {
             UserFileO << usersVEC.at(i) << endl;
         }
         UserFileO.close();
     }
 }
waitXTime()
void waitXTime (unsigned int time)
Sleeps for a given time.
Author
Renato Campos
Date
20/11/2016
Parameters
time The time in seconds.
Definition at line 349 of file utils.cpp.
Referenced by Card::operator<<(), Table::play(), Table::readTableFile(), and Table::writeTableFile().
{
     clock_t t1 = clock();
     float seconds_past = 0.0;
     while (seconds_past < time)
     {
         seconds_past = (clock() - t1) / CLOCKS_PER_SEC;
     }
     return;
 }